/* Traductions anglaises.
   Le français reste la langue de référence : toute clé absente
   d'ici retombe sur le texte français présent dans le HTML ou
   dans le module qui l'appelle.

   Les textes juridiques sont traduits pour être compris, mais
   le contrat reste soumis au droit français : la modale affiche
   un avertissement disant que seule la version française fait foi. */

export default {
  "a11y.changer_langue": "Change language",
  "a11y.changer_theme": "Change theme",
  "a11y.fermer": "Close",
  "a11y.informations_legales": "Legal information",
  "a11y.langues_disponibles": "Available languages",
  "a11y.navigation": "Navigation",
  "a11y.navigation_principale": "Main navigation",
  "a11y.theme_clair": "Switch to light theme",
  "a11y.theme_sombre": "Switch to dark theme",
  "accueil.1_19_restantes_78_mots_dictes": "1:19 left \u00b7 78 words dictated",
  "accueil.accepter": "Accept",
  "accueil.accueil": "Home",
  "accueil.aller_au_contenu": "Skip to content",
  "accueil.appuyez_sur_le_micro_pour_parler_a_votre_coach": "Press the mic to speak to your coach.",
  "accueil.arrete_de_repeter_dans_le_vide_entraine_toi_en_condi": "Stop rehearsing into the void. Practise under real conditions, see exactly where you lose points, and fix every answer with a detailed correction.",
  "accueil.aucune_promesse_de_note": "No promised grade",
  "accueil.axes_notes_a_chaque_passage_contenu_structure_eloque": "areas scored every run: content, structure, delivery and speaking pace",
  "accueil.brevet_3e": "Brevet \u00b7 Year 10",
  "accueil.certification": "Certification",
  "accueil.cette_information_sert_uniquement_a_appliquer_la_reg": "This is used only to apply the regulations. It is never shared.",
  "accueil.chaque_reponse_est_notee_sur_20_et_decomposee_ce_qui": "Every answer is scored out of 20 and broken down: what works, what's missing, and a short rewrite of what you could have said instead. No polite praise \u2014 if an answer is hollow, it says so.",
  "accueil.coach_ia": "AI Coach",
  "accueil.collez_votre_plan_votre_texte_ou_votre_sujet_et_disc": "Paste your outline, your script or your topic and talk it through before you start: structure, rewording, opening hook, panel questions. In writing or out loud.",
  "accueil.compte": "Account",
  "accueil.concision": "Concision",
  "accueil.concours": "Entrance exam",
  "accueil.connexion": "Log in",
  "accueil.continuer": "Continue",
  "accueil.continuez_a_vous_entrainer": "Keep practising",
  "accueil.criteres_notes": "Scored criteria",
  "accueil.decrivez_une_journee_type_de_votre_stage_que_faisiez": "\"Describe a typical day of your placement: what did you actually do?\"",
  "accueil.deux_simulations_offertes_sans_carte": "Two full sessions free when you create your account, no card. Ten minutes and you'll know where you stand.",
  "accueil.discussion_libre": "Open conversation",
  "accueil.documents_lus_puis_supprimes": "Documents read then deleted, never resold",
  "accueil.e_mail_de_votre_parent_ou_responsable_legal": "Email of your parent or legal guardian",
  "accueil.effacer": "Clear",
  "accueil.en_dessous_de_15_ans_son_accord_est_necessaire_pour_": "Under 15, their consent is required for us to process your data.",
  "accueil.entretien": "Interview",
  "accueil.essayer_gratuitement": "Try it free",
  "accueil.exemple_parent": "parent@example.com",
  "accueil.gerer_mon_abonnement": "Manage my subscription",
  "accueil.grand_oral": "Grand Oral",
  "accueil.l_analyse_d_eloquence_mesure_ce_que_tu_n_entends_pas": "The delivery analysis measures what you can't hear yourself: words per minute, vocabulary range, sentence length. Most candidates speak too fast without realising it.",
  "accueil.l_outil_ne_remplace_ni_un_professeur_ni_un_jury_il_t": "The tool replaces neither a teacher nor a panel. It puts you through the exam once, in private, so that the real day isn't your first time.",
  "accueil.le_moyen_le_plus_rapide_de_passer_son_oral_une_premi": "The fastest way to sit your oral exam once, in private. Your CVs, topics and recordings are handled for the length of the session, then deleted: never kept, never resold, never used to train a model.",
  "accueil.lecture_audio_activee": "Audio playback: on",
  "accueil.legal": "Legal",
  "accueil.les_questions_sont_generees_a_partir_de_tes_propres_": "Questions are generated from your own documents, then read aloud. You answer into the mic while the clock runs. It's the only way to know whether your answer holds up out loud and not just on paper.",
  "accueil.lus_le_temps_de_la_simulation_jamais_conserves_ni_re": "Read for the length of the session, never kept or resold.",
  "accueil.mentions_legales": "Legal notice",
  "accueil.mes_simulations_passees": "My past sessions",
  "accueil.methode_constat": "<span class=\"font-display text-3xl leading-none text-iris2\">\u201c</span> Most candidates prepare for an oral by re-reading their notes. On the day, they discover they have never once said their answers out loud.",
  "accueil.mon_espace": "My space",
  "accueil.note_sur_la_coherence_du_projet_et_la_culture_genera": "Scored on the coherence of your plan and general knowledge.",
  "accueil.note_sur_la_prise_de_recul_et_le_lien_au_projet_d_or": "Scored on perspective and the link to your study plans.",
  "accueil.note_sur_les_preuves_chiffrees_et_la_concision": "Scored on hard evidence and concision.",
  "accueil.paiement_securise_stripe": "Secure payment by Stripe",
  "accueil.parler_au_coach_ia": "Talk to the AI coach",
  "accueil.pitch": "Pitch",
  "accueil.plus_tard": "Later",
  "accueil.pose_dans_la_langue_de_l_epreuve_note_selon_le_cecrl": "Asked in the language of the exam, scored against the CEFR.",
  "accueil.pourquoi_preporal": "Why Oralixia?",
  "accueil.preporal_premium": "Oralixia Premium",
  "accueil.preporal_s_adresse_aussi_a_des_collegiens_et_lyceens": "Oralixia is also used by school pupils. French law sets different rules by age: we ask for an age bracket, never your date of birth.",
  "accueil.preuves_et_chiffres": "Evidence and figures",
  "accueil.produit": "Product",
  "accueil.progression_de_vos_notes_de_la_plus_ancienne_a_la_pl": "Your scores over time, oldest to most recent.",
  "accueil.qu_est_ce_qui_dans_votre_dossier_pourrait_faire_hesi": "\"What in your application might give the panel pause?\"",
  "accueil.quel_age_avez_vous": "How old are you?",
  "accueil.quelle_est_la_taille_de_votre_marche_et_comment_l_av": "\"How big is your market, and how did you size it?\"",
  "accueil.quelqu_un_vous_soutient_exactement_l_inverse_de_votr": "\"Someone argues the exact opposite of your conclusion. What do you say to them?\"",
  "accueil.question_3_5_mise_en_situation": "Question 3 / 5 \u00b7 Scenario",
  "accueil.questions_courtes_concretes_orientees_objection": "Short, concrete questions aimed at objections.",
  "accueil.refuser": "Decline",
  "accueil.relecture": "Review",
  "accueil.repeter_devant_quelqu_un_coute_cher_gene_et_n_est_pa": "Rehearsing in front of someone costs money, feels awkward, and can't be done ten times over. Oralixia does the opposite: the examiner asks its questions out loud, never tires, and tells you plainly what isn't working.",
  "accueil.resiliable_en_un_clic": "Cancel in one click",
  "accueil.retours_de_candidats_apres_leur_oral_verifies_avant_": "Feedback from candidates after their exam, checked before publication.",
  "accueil.sans_engagement_depuis_le_portail_client_stripe": "No commitment, from the Stripe customer portal.",
  "accueil.se_deconnecter": "Sign out",
  "accueil.simulateur": "Simulator",
  "accueil.simulateur_d_oral": "Oral exam simulator",
  "accueil.simulation_passee": "Past session",
  "accueil.simulations_illimitees_rapports_detailles_et_coach_i": "Unlimited sessions, detailed reports and unlimited AI coach.",
  "accueil.simulations_offertes_sans_carte": "full sessions free with your account, no card",
  "accueil.some_people_say_studying_abroad_is_essential_do_you_": "\"Some people say studying abroad is essential. Do you agree? Give reasons and examples.\"",
  "accueil.structure_de_la_reponse": "Answer structure",
  "accueil.temoignages": "Testimonials",
  "accueil.tes_documents_restent_a_toi": "Your documents stay yours",
  "accueil.tout_effacer": "Clear all",
  "accueil.types_d_oraux_couverts_entretien_grand_oral_brevet_c": "types of oral exam covered: job interview, Grand Oral, brevet, competitive entrance, pitch, subject viva",
  "accueil.un_entrainement_pas_une_garantie_de_reussite_c_est_e": "Training, not a guarantee of success. It's written into the terms of sale.",
  "accueil.un_jury_de_brevet_et_un_jury_de_grande_ecole_n_atten": "A brevet panel and a grande \u00e9cole panel expect different things. The examiner shifts its stance, vocabulary and marking grid to match the exam.",
  "accueil.vocabulaire_adapte_a_l_age_bienveillant_mais_exigean": "Age-appropriate vocabulary, kind but demanding.",
  "accueil.voir_les_offres": "See the plans",
  "accueil.vos_2_simulations_gratuites_sont_utilisees": "You've used your 2 free sessions",
  "accueil.votre_premiere_semaine_porte_sur_un_dossier_que_vous": "\"Your first week is on a file you don't know. Where do you start?\"",
  "accueil.votre_profil_manque_d_experience_sur_ce_perimetre_po": "\"Your profile lacks experience in this area. Why you rather than a seasoned candidate?\"",
  "accueil.vous_n_etes_pas_connecte": "You're not signed in.",
  "age.15_17": "Between 15 and 17",
  "age.consentement_envoye": "Thank you. A message will be sent to your legal guardian to confirm their consent.",
  "age.email_parent_requis": "Enter the e-mail address of your parent or legal guardian.",
  "age.majeur": "18 or over",
  "age.moins_15": "Under 15",
  "age.paiement_mineur": "You have declared that you are under {n}: payment must be made by your legal guardian, or with their express consent.",
  "appel.appeler_le_coach": "Call the coach",
  "appel.connexion": "Connecting\u2026",
  "appel.ecoute": "I'm listening\u2026",
  "appel.erreur": "I couldn't answer. Shall we try again?",
  "appel.fin_oral": "Thank you, the interview is over. I'm preparing your feedback.",
  "appel.indisponible": "Calling needs speech recognition, which this browser does not have. Safari, Chrome and Edge do.",
  "appel.ouverture_coach": "Hello, I'm your coach. Tell me which oral exam you are working on.",
  "appel.parole": "Answering\u2026",
  "appel.passer_a_l_oral": "Take the whole interview out loud",
  "appel.raccrocher": "Hang up",
  "appel.reflexion": "One moment\u2026",
  "appel.sous_titre_coach": "Speak normally. Pause to let the coach answer.",
  "appel.sous_titre_oral": "Answer out loud. Pause, and the examiner moves on.",
  "appel.termine": "Call ended.",
  "appel.titre_coach": "Call with the coach",
  "appel.titre_oral": "Spoken interview",
  "auth.adresse_email": "Email address",
  "auth.afficher_mot_de_passe": "Show password",
  "auth.avantage_appareils": "Pick up your access on any device",
  "auth.avantage_deux_simulations": "2 free sessions, from the moment you sign up",
  "auth.avantage_progression": "Follow your progress curve",
  "auth.avantage_relire": "Re-read your feedback whenever you like",
  "auth.bienvenue": "You're in.",
  "auth.compte_cree": "Account created. Your two free sessions are waiting.",
  "auth.confirmation_differente": "The two passwords do not match.",
  "auth.confirmer_mot_de_passe": "Confirm password",
  "auth.confirmez_boite_mail": "Account created. Open your inbox and click the link to activate it. Check your spam folder too.",
  "auth.connexion_en_cours": "Signing in\u2026",
  "auth.continuer_google": "Continue with Google",
  "auth.creation_en_cours": "Creating your account\u2026",
  "auth.creer_mon_compte": "Create my account",
  "auth.deconnecte": "You are signed out.",
  "auth.deja_inscrit": "This address already has an account. Sign in, or use \u201cForgot your password?\u201d.",
  "auth.email_au_dessus": "Enter your e-mail address above.",
  "auth.email_invalide": "Enter a valid e-mail address.",
  "auth.en_continuant": "By continuing, you accept the",
  "auth.err.deja_inscrit": "An account already exists for this address. Sign in instead.",
  "auth.err.generique": "Something went wrong.",
  "auth.err.identifiants": "Wrong e-mail or password.",
  "auth.err.mdp_court": "Your password must be at least 8 characters.",
  "auth.err.non_confirme": "Confirm your address first: the link is in your inbox.",
  "auth.et_la": "and the",
  "auth.exemple_email": "you@example.com",
  "auth.exemple_nom": "Dupont",
  "auth.exemple_prenom": "Camille",
  "auth.facultatif": "(optional)",
  "auth.force_bon": "Good password.",
  "auth.force_court": "Too short: eight characters minimum.",
  "auth.force_moyen": "Fine. A digit and a capital would make it sturdier.",
  "auth.google_inactif": "Google sign-in is not enabled on this site yet. Use your e-mail and password, or the passwordless link.",
  "auth.huit_caracteres": "8 characters minimum",
  "auth.indispo": "Unavailable: Supabase is not configured.",
  "auth.inscription": "Sign up",
  "auth.inscription_indispo": "Sign-up unavailable: Supabase is not configured.",
  "auth.lien_envoye": "Link sent. Open your inbox to sign in.",
  "auth.lien_sans_mot_de_passe": "Email me a link instead",
  "auth.masquer_mot_de_passe": "Hide password",
  "auth.mdp_envoye": "Message sent: follow the link to choose a new password.",
  "auth.mdp_requis": "Enter your password.",
  "auth.mot_de_passe": "Password",
  "auth.mot_de_passe_oublie": "Forgot your password?",
  "auth.nom": "Last name",
  "auth.ou": "or",
  "auth.politique_confidentialite": "privacy policy",
  "auth.prenom": "First name",
  "auth.prenom_requis": "Tell us your first name.",
  "auth.pseudonyme": "Nickname",
  "auth.pseudonyme_aide": "Shown at the top of the page instead of your address. Without one, it will read \u201cFirst name L.\u201d.",
  "auth.pseudonyme_exemple": "Cam",
  "auth.raison_simulation": "Create your free account to start your session: your two free sessions are tied to it.",
  "auth.se_connecter": "Sign in",
  "auth.supabase_absent": "Sign-in unavailable: Supabase is not configured.",
  "auth.volet_intro": "Two full sessions on the house when you create your account. No card required.",
  "avis.aucun_detail": "This page shows only genuine feedback from people who have actually run a session, checked before publication. We would rather show an empty page than invented testimonials \u2014 which are illegal anyway.",
  "avis.aucun_pour_epreuve": "No reviews for this exam yet.",
  "avis.aucun_titre": "No testimonials published yet.",
  "avis.collectes_depuis": ", collected since {date}",
  "avis.deposer_premier": "Leave the first review",
  "avis.depuis": "since {date}",
  "avis.en_attente": "Awaiting verification",
  "avis.epreuve_facultative": "Exam you prepared (optional)",
  "avis.etoile": "{n} star",
  "avis.etoiles": "{n} stars",
  "avis.merci_local": "Thank you! Your review is saved on this device; it will be published once checked.",
  "avis.merci_serveur": "Thank you! Your review will be published once checked.",
  "avis.nom_requis": "Give at least your first name.",
  "avis.note_sur_5": "{n} out of 5",
  "avis.statut_defaut": "Oralixia user",
  "avis.sur_n_verifie": "from {n} verified review",
  "avis.sur_n_verifies": "from {n} verified reviews",
  "avis.toutes_epreuves": "All exams",
  "avis.trop_court": "Your feedback is a little short \u2014 a few more words?",
  "avis.verifie": "{n} verified review",
  "avis.verifies": "{n} verified reviews",
  "avis.vide_lien": "Yours could be the first.",
  "avis.vide_texte": "The feedback shown here will come from real people who sat a session, checked before publication. Just finished an oral exam?",
  "avis.vide_titre": "No published reviews yet.",
  "bilan.chiffres.non": "Add a precise data point: a duration, a volume, a date, a number.",
  "bilan.chiffres.oui": "You back your points with figures or dates.",
  "bilan.debit.bon": "Pace of {n} words per minute: that is the rhythm of a controlled oral \u2014 keep it.",
  "bilan.debit.lent": "You speak at {n} words per minute: a little slow, which reads as hesitation. Link your ideas without hunting for the perfect word.",
  "bilan.debit.non_mesure": "Answer into the microphone rather than typing: Oralixia can then measure your pace and your pauses.",
  "bilan.debit.rapide": "You speak at {n} words per minute: that is fast. Take a breath after each idea \u2014 the panel needs to keep up.",
  "bilan.je.non": "Say \u201cI did\u201d, not \u201cwe did\u201d: the panel is assessing you.",
  "bilan.je.oui": "You own your role in the first person.",
  "bilan.long.bien": "An answer developed enough to convince.",
  "bilan.long.correct": "Decent length; one more example would make it unanswerable.",
  "bilan.long.court": "Too short: aim for 45 to 120 seconds, roughly 100 to 250 words.",
  "bilan.phrases_longues": "Your sentences average {n} words. Cut them in two: one idea, one sentence.",
  "bilan.plan": "Announce your structure out loud (\u201cfirst\u2026 then\u2026 finally\u201d): the panel marks what it can follow.",
  "bilan.plan.non": "Announce two or three points at the start: the panel follows better.",
  "bilan.plan.oui": "The structure of the answer is audible.",
  "bilan.preuve.non": "Finish with what it produced, not only with what you did.",
  "bilan.preuve.oui": "The reasoning runs all the way to the result or the example.",
  "bilan.reecriture": "Open like this: \u201c{debut}\u2026\u201d, then move on to a dated, quantified example, and close in one sentence on the result.",
  "bilan.sans_reponse": "Question left unanswered: take it again out loud, even imperfectly.",
  "bilan.tics.aucun": "No noticeable filler words: your delivery is clean.",
  "bilan.tics.reperes": "Filler words spotted: {liste}. Replace them with a one-second silence, which reads as confidence.",
  "bilan.tics.supprimer": "Filler words to cut: {liste}.",
  "bilan.vocabulaire": "Repetitive vocabulary: prepare five precise terms from the field and place them deliberately.",
  "chargement.correction.conseil.0": "The feedback is blunt: that is what makes it useful.",
  "chargement.correction.conseil.1": "Start again with your lowest-scoring question, not the first one.",
  "chargement.correction.conseil.2": "Running another session right after reading your feedback is the best moment to improve.",
  "chargement.correction.conseil.3": "An answer that runs long costs more marks than one that runs short.",
  "chargement.correction.etape.0": "Re-reading your answers",
  "chargement.correction.etape.1": "Assessing the substance, answer by answer",
  "chargement.correction.etape.2": "Measuring your pace and range of vocabulary",
  "chargement.correction.etape.3": "Writing your areas to work on",
  "chargement.correction.titre": "Analysing your performance",
  "chargement.questions.conseil.0": "Breathe before answering. Two seconds of silence beat three of \u201cum\u201d.",
  "chargement.questions.conseil.1": "A good answer has three beats: the situation, what you did, the result.",
  "chargement.questions.conseil.2": "The panel remembers your first and last sentence. Polish both.",
  "chargement.questions.conseil.3": "One concrete figure beats three adjectives.",
  "chargement.questions.conseil.4": "If a question catches you out, rephrase it: that buys you five seconds to think.",
  "chargement.questions.etape.0": "Reading your documents",
  "chargement.questions.etape.1": "Spotting what the panel will dig into",
  "chargement.questions.etape.2": "Writing the examiner's questions",
  "chargement.questions.etape.3": "Putting the session in order",
  "chargement.questions.titre": "Preparing your exam",
  "coach.accueil": "Hello, I'm your Oralixia coach. Tell me which oral you are preparing, or paste your outline, your text or your topic: I'll help you structure it, rephrase it and anticipate the panel's questions.",
  "coach.analyse_piece": "Can you look at this document and tell me what I should work on?",
  "coach.appuyez_micro": "Press the microphone to talk to your coach.",
  "coach.dernier_echange": "Last free exchange of the day.",
  "coach.dictee_absente": "Voice dictation is not available in this browser (try Chrome, Edge or Safari).",
  "coach.documents_joints": "Attached documents",
  "coach.echange_restant": "{n} free exchange left today",
  "coach.echanges_restants": "{n} free exchanges left today",
  "coach.je_vous_ecoute": "I'm listening\u2026",
  "coach.joindre": "Attach a document",
  "coach.lecture_activee": "Audio playback: on",
  "coach.lecture_coupee": "Audio playback: off",
  "coach.lecture_piece": "Reading {nom}\u2026",
  "coach.limite_atteinte": "You have used today's exchanges with the coach.",
  "coach.parler": "Speak",
  "coach.piece_echec": "This file could not be read.",
  "coach.piece_refusee": "This document could not be sent.",
  "coach.piece_trop_lourde": "File too large: 3 MB maximum.",
  "coach.piece_vide": "No usable text in this file.",
  "coach.placeholder_saisie": "Ask your question, or paste your speech\u2026",
  "coach.preparation": "Preparing\u2026",
  "coach.raison_compte": "Create your free account to talk to the coach: a few exchanges a day are on the house.",
  "coach.repli": "The coach cannot be reached right now (the API is not configured, or the network dropped). Meanwhile, a method that almost always works: an opening line, three ideas announced, one dated and quantified example per idea, then a conclusion that answers the question asked.",
  "coach.resume.axes": "Points flagged: {axes}",
  "coach.resume.eloquence": "Delivery: {n}/20.",
  "coach.resume.entete": "Session of {date} \u2014 {type}{precision}.",
  "coach.resume.ma_reponse": "My answer: {texte}",
  "coach.resume.note": "Overall score: {n}/100.",
  "coach.resume.note_20": "Score: {n}/20.",
  "coach.resume.sans_reponse": "(no answer)",
  "coach.resume.verdict": "Verdict: {v}",
  "coach.retirer_piece": "Remove",
  "coach.simulation_confiee": "Here is my session from {date}. What should I work on first?",
  "coach.trop_de_pieces": "Five attachments at most.",
  "compte.abonnement": "Subscription",
  "compte.abonnement_actif": "Subscription active. Thank you!",
  "compte.actif_jusquau": "Active until {date}",
  "compte.aucun_abonnement": "No subscription in progress. Your free sessions are still available.",
  "compte.changer_adresse": "Change address",
  "compte.changer_mot_de_passe": "Change password",
  "compte.choisir_photo": "Choose a photo",
  "compte.connexion": "Address and password",
  "compte.couleur_pastille": "Badge colour",
  "compte.delai": "The server did not answer. Try again.",
  "compte.echec": "Saving failed.",
  "compte.email_aide": "Changing your address needs confirming: a link goes to both the old and the new one.",
  "compte.email_confirmation": "A confirmation link goes to both the old and the new address. The change takes effect once both are confirmed.",
  "compte.email_identique": "Enter a new address.",
  "compte.enregistre": "Saved.",
  "compte.enregistrement": "Saving\u2026",
  "compte.enregistrer": "Save",
  "compte.envoi_photo": "Uploading the photo\u2026",
  "compte.gerer_abonnement": "Cancel or change plan",
  "compte.gerer_mon_compte": "Manage my account",
  "compte.hors_ligne": "Cannot save: you are not signed in.",
  "compte.identite_aide": "A photo replaces the silhouette. Without one, pick the shade of your badge.",
  "compte.identite_visuelle": "Photo and colour",
  "compte.intro": "Your identity, your subscription and your payment methods. None of it is visible to other candidates.",
  "compte.intro_anonyme": "Your details, your subscription and your free sessions are waiting behind your account.",
  "compte.mdp_envoye": "Message sent: follow the link to choose a new password.",
  "compte.mes_informations": "My details",
  "compte.mes_simulations": "My sessions",
  "compte.mode_local": "Local mode: your history is stored in this browser only. Add your Supabase keys to sync across devices.",
  "compte.mode_local_titre": "Accounts are unavailable in local mode",
  "compte.mon_abonnement": "My subscription",
  "compte.mon_compte": "My account",
  "compte.moyens_de_paiement": "Payment methods",
  "compte.offre_gratuite": "Free plan",
  "compte.ouvrir_portail": "Manage my payment methods",
  "compte.paiement_aide": "Your card details never pass through Oralixia and are not stored here: they are handled by Stripe, on its own pages.",
  "compte.photo_echec": "The photo could not be uploaded.",
  "compte.photo_enregistree": "Photo saved.",
  "compte.photo_retiree": "Photo removed.",
  "compte.photo_trop_lourde": "Photo too large: 2 MB maximum.",
  "compte.photo_url": "Could not find the photo's URL.",
  "compte.premium_actif": "Premium active",
  "compte.pseudo_aide": "Shown at the top of the page. Without a nickname it will read",
  "compte.reconduction": "Renews automatically. Cancel any time.",
  "compte.resiliation_aide": "A cancellation takes effect at the end of the period you already paid for: you keep access until then.",
  "compte.retirer_photo": "Remove photo",
  "compte.simulations_restantes": "free sessions left out of {total}",
  "compte.suppression_corps": "Hello,\n\nI am requesting the deletion of my Oralixia account.\n\nAccount address: {email}\n\nThank you.",
  "compte.suppression_objet": "Deletion of my Oralixia account",
  "compte.suppression_sans_contact": "No contact address is set on this site yet. Write to the publisher to request deletion.",
  "compte.supprimer_aide": "Permanently erases your profile, your past sessions and your usage counter. An active subscription must be cancelled first, from the payment portal.",
  "compte.supprimer_bouton": "Request deletion",
  "compte.supprimer_confirmation": "Permanently delete your account, your past sessions and your usage counter? This cannot be undone.",
  "compte.supprimer_titre": "Delete my account",
  "compte.titre_anonyme": "Sign in to manage your account",
  "cookies.texte": "We only use cookies that are needed for the site to work (session, preferences). No advertising cookies, no third-party trackers.",
  "cta.lancer_simulation": "Start my session",
  "cta.mes_simulations": "See my past sessions",
  "cta.premiere_simulation": "Start my first session",
  "cta.tous_temoignages": "See all testimonials",
  "demo.conseil": "<span class=\"font-medium text-iris2\">Tip \u00b7</span> Pause properly after every idea. Your pace drops naturally and the panel takes in more.",
  "demo.debit": "words / min<br>Too fast",
  "demo.phrases": "words / sentence<br>Shorten them",
  "demo.richesse": "range<br>Varied vocabulary",
  "ecoute.arreter": "Stop",
  "ecoute.bilan": "Listen to the report",
  "ecoute.ecouter": "Listen",
  "hist.a": "at",
  "hist.aucune": "No sessions yet. Run one and it will appear here with its score and its feedback.",
  "hist.courbe_a11y": "Score progress curve",
  "hist.courbe_attente": "Run a second session and your progress curve will appear here.",
  "hist.eloquence": "delivery",
  "hist.non_conserve": "Details not kept",
  "hist.progression": "Progress over {n} sessions",
  "hist.question": "question",
  "hist.questions": "questions",
  "hist.relire": "Re-read the questions and the feedback \u2192",
  "hist.vide": "History cleared.",
  "hist.vider_confirmer": "Permanently delete all your saved sessions?",
  "import.doc_ancien": "Old .doc format cannot be read: save as .docx or PDF.",
  "import.echec": "Import failed.",
  "import.format": "Unsupported format.",
  "import.importe": "{n} characters imported",
  "import.lecture": "Reading {f}\u2026",
  "import.lib_injoignable": "Reader library unreachable.",
  "import.ocr": "Scanned PDF detected, running text recognition\u2026",
  "import.ok": "Document imported. Check it and correct if needed.",
  "import.page": "Reading page {p}/{n}\u2026",
  "import.vide": "No usable text found in this file.",
  "legal.alerte.completer": "Fill in the <code>window.ORALIXIA_ENV</code> block in <code>index.html</code>.",
  "legal.alerte.manquantes": "The following mandatory legal notices are missing:",
  "legal.alerte.sanctions": "Selling without these notices carries penalties (art. L111-1 et seq. of the French Consumer Code).",
  "legal.alerte.titre": "Incomplete configuration \u2014 do not sell in this state.",
  "legal.cgv": "Terms of sale",
  "legal.cgv.1": "1. Purpose",
  "legal.cgv.1_corps": "These terms govern the sale of subscriptions and paid access to Oralixia, an oral-exam practice service published by {n}.",
  "legal.cgv.2": "2. Offers and prices",
  "legal.cgv.2_extra": "{nom}: {prix} incl. tax for six months of full access, preceded by {jours} days of free trial. The subscription is <strong>renewed automatically every six months</strong> until cancelled; nothing is charged during the trial.",
  "legal.cgv.2_gratuit": "Free offer: {n} complete sessions when the account is created, no card required.",
  "legal.cgv.2_mensuel": "{nom}: {prix} incl. tax per month, no commitment, renewed automatically each month until cancelled.",
  "legal.cgv.2_pass48": "{nom}: {prix} incl. tax, full access for 48 hours from payment. One-off payment, no renewal.",
  "legal.cgv.2_prix": "Prices are shown inclusive of all taxes, in euros. {n} may change them at any time; the price that applies is the one displayed at the time of the order.",
  "legal.cgv.3": "3. Order and payment",
  "legal.cgv.3_corps": "Payment is made online through Stripe (card and the methods Stripe offers). The order is confirmed once payment is confirmed. An invoice is available in your account area.",
  "legal.cgv.4": "4. Cancellation and renewal",
  "legal.cgv.4_essai": "Cancelling during the {jours}-day trial of the {nom} offer results in no charge at all.",
  "legal.cgv.4_l215": "In accordance with article L215-1 of the French Consumer Code, {n} informs the subscriber of their right not to renew their six-month subscription, no earlier than three months and no later than one month before the renewal date. Failing that information, the subscriber may end the contract free of charge at any time from the renewal date, and obtain a refund of the amounts charged after it.",
  "legal.cgv.4_pass48": "The 48-hour Pass is a one-off payment: it does not renew and does not need to be cancelled. When it expires, access returns to the free offer.",
  "legal.cgv.4_resilier": "The {m} and {e} subscriptions can be cancelled at any time from \u201cManage my account\u201d, which opens the Stripe customer portal. Cancellation takes effect at the end of the period already paid for: access is kept until then, and nothing is refunded pro rata. The portal also lets you switch between plans.",
  "legal.cgv.5": "5. Right of withdrawal",
  "legal.cgv.5_delai": "In accordance with articles L221-18 et seq. of the French Consumer Code, the consumer has 14 days to withdraw.",
  "legal.cgv.5_renonciation": "By subscribing, you expressly request immediate performance of the service and acknowledge that you lose your right of withdrawal once the service has been fully performed (art. L221-28 13\u00b0). For the monthly subscription, withdrawal remains possible as long as no paid session has been started.",
  "legal.cgv.6": "6. Availability",
  "legal.cgv.6_corps": "The service is provided \u201cas is\u201d. {n} uses reasonable means to keep it available but does not guarantee absolute continuity (maintenance, a third-party provider incident, unavailability of the AI model provider).",
  "legal.cgv.7": "7. Liability",
  "legal.cgv.7_corps": "Oralixia is a practice tool. No obligation of result is owed as to success in an exam, a competitive entrance test or a recruitment process.",
  "legal.cgv.8": "8. Subscription by a minor",
  "legal.cgv.8_annulation": "{n} may ask for confirmation at any time and cancel, free of charge, a subscription taken out by a minor without that consent.",
  "legal.cgv.8_gratuit": "Free use of the service remains open. For under-15s, creating an account requires the consent of the holder of parental authority (art. 45 of the French Data Protection Act).",
  "legal.cgv.8_principe": "The service is aimed in particular at secondary-school pupils. In accordance with articles 1145 et seq. of the French Civil Code, an unemancipated minor cannot take out a paid subscription alone: it must be taken out by the holder of parental authority, or with their express consent.",
  "legal.cgv.9": "9. Governing law",
  "legal.cgv.9_corps": "French law. Failing an amicable agreement, the French courts have jurisdiction.",
  "legal.cgv.titre": "Terms and conditions of sale",
  "legal.confidentialite": "Privacy (GDPR)",
  "legal.cookies": "Cookies",
  "legal.cookies.aucun_avant": "Oralixia uses",
  "legal.cookies.aucun_gras": "no advertising cookies and no marketing trackers",
  "legal.cookies.necessaires": "Strictly necessary cookies: authentication session (Supabase) and payment security (Stripe). They do not require prior consent.",
  "legal.cookies.stockage": "Browser local storage: free-session counter, history of your scores, reviews you left, display preferences. This information stays on your device; you can erase it from \u201cMy space\u201d or by clearing the site's data.",
  "legal.cookies.titre": "Cookies and local storage",
  "legal.cookies.utilisons": "What we use",
  "legal.mentions": "Legal notice",
  "legal.mentions.contact": "Contact",
  "legal.mentions.directeur": "Publication director",
  "legal.mentions.editeur": "Site publisher",
  "legal.mentions.hebergement": "Hosting",
  "legal.mentions.limites": "Limits of the service",
  "legal.mentions.limites_corps": "Oralixia is an AI-assisted practice tool. Questions, scores and advice are generated automatically, may contain errors, and are neither an official assessment nor a guarantee of success in an exam, a competitive entrance test or an interview.",
  "legal.mentions.mediation": "Consumer mediation",
  "legal.mentions.mediation_corps": "In the event of an unresolved dispute, a consumer may refer the matter free of charge to a consumer mediator: {m}. European online dispute resolution platform: ec.europa.eu/consumers/odr.",
  "legal.mentions.paiement": "Payment",
  "legal.mentions.paiement_corps": "Payments are handled by {p}. No card details pass through or are stored on Oralixia's servers.",
  "legal.mentions.pi": "Intellectual property",
  "legal.mentions.pi_corps": "Every element of the site (trade mark, logo, interface, texts, code) is protected. Any reproduction without written permission is prohibited. Content you upload remains yours.",
  "legal.mentions.siege": "Registered office",
  "legal.mentions.titre": "Legal notice",
  "legal.mentions.tva": "VAT",
  "legal.rgpd.documents": "Your documents",
  "legal.rgpd.documents_corps": "Uploaded files are read directly in your browser: they are never uploaded to our servers.",
  "legal.rgpd.documents_gras": "Your CVs, topics, notes and answers are not kept.",
  "legal.rgpd.documents_ia": "The extracted text is sent to the AI model provider for as long as it takes to generate the questions and the feedback, then is not stored on Oralixia's side. This content is neither sold, nor transferred, nor used to train a model.",
  "legal.rgpd.donnees": "Data processed",
  "legal.rgpd.donnees_abo": "Subscription: Stripe customer identifier, status and renewal date (performance of the contract and accounting obligation).",
  "legal.rgpd.donnees_audio": "Audio: speech recognition uses your browser's API. Depending on the browser, audio may be processed by its vendor (Google, Apple, Microsoft). Oralixia neither receives nor stores any recording.",
  "legal.rgpd.donnees_compte": "Account: e-mail address, identifier, creation date (legal basis: performance of the contract).",
  "legal.rgpd.donnees_historique": "History: type of oral, date, overall score and scores per criterion \u2014 to show your progress (performance of the contract). The content of your answers is not stored server-side.",
  "legal.rgpd.droits": "Your rights",
  "legal.rgpd.droits_corps": "Access, rectification, erasure, restriction, objection and portability: write to {email}. You may also lodge a complaint with the CNIL (cnil.fr).",
  "legal.rgpd.durees": "Retention periods",
  "legal.rgpd.durees_corps": "Account and history: until the account is deleted, then 30 days. Accounting records: 10 years (legal obligation). Browsing data: 13 months maximum.",
  "legal.rgpd.mineurs": "Minors",
  "legal.rgpd.mineurs_corps": "The service is aimed in particular at secondary-school pupils. For under-15s, creating an account requires the consent of the holder of parental authority.",
  "legal.rgpd.responsable": "Data controller",
  "legal.rgpd.soustraitants": "Processors",
  "legal.rgpd.soustraitants_corps": "Vercel (hosting), Supabase (database and authentication, EU region), Stripe (payment), and the AI model provider for generating questions and feedback. Some transfers outside the EU are covered by the European Commission's standard contractual clauses.",
  "legal.rgpd.titre": "Privacy policy (GDPR)",
  "legal.version_fr_fait_foi": "Translation provided for information only. Only the French version is binding: the contract is governed by French law.",
  "lien.desactive": "Link sign-in is disabled on this project.",
  "lien.expire": "This link has expired or has already been used. A sign-in link works only once. Request a new one, or sign in with your password.",
  "lien.incomplet": "The link you received is incomplete. Request a new one.",
  "lien.invalide": "This link is invalid. Request a new one.",
  "lien.refuse": "This link is no longer valid. Request a new one, or sign in with your password.",
  "lien.serveur": "The authentication service did not respond. Try again in a moment.",
  "lu.eloquence": "Delivery tips.",
  "lu.note_globale": "Your overall score is {n} out of 100.",
  "lu.note_sur_20": "Score: {n} out of 20.",
  "lu.par_critere": "Breakdown by criterion.",
  "lu.sur_100": "{nom}: {val} out of 100.",
  "micro.absent": "No microphone detected on this device.",
  "micro.interrompue": "Dictation stopped.",
  "micro.refuse": "Microphone denied. Allow microphone access in your browser.",
  "micro.refuse_systeme": "Microphone denied by the system.",
  "micro.reseau": "Speech recognition could not reach the network.",
  "micro.rien_entendu": "No speech detected.",
  "offre.equivalent": "{m} per month \u00b7 {e} less than six months at the monthly rate",
  "offre.essai": "{n} days free",
  "offre.extra.accroche": "A whole school year",
  "offre.extra.detail": "Six months of full access and unlimited AI coach. One week free, then renews every six months, cancel any time.",
  "offre.mensuel.accroche": "Most flexible",
  "offre.mensuel.detail": "Unlimited sessions, full reports, unlimited AI coach. No commitment, cancel in one click.",
  "offre.pass48.accroche": "The night before",
  "offre.pass48.detail": "Full access for 48 hours. One-off payment, no renewal.",
  "offre.periode.par_mois": "per month",
  "offre.periode.pour_6_mois": "for 6 months",
  "offre.periode.une_fois": "one-off",
  "offre.recommande": "Recommended",
  "page.titre.accueil": "Oralixia \u2014 Pass your oral first time",
  "page.titre.compte": "My account \u2014 Oralixia",
  "page.titre.simulateur": "Your oral in three steps \u2014 Oralixia",
  "page.titre.temoignages": "Testimonials \u2014 Oralixia",
  "paywall.annule": "Payment cancelled. Your free sessions are still available.",
  "paywall.confirmation_age": "I confirm that I am 18 or over, or that I have my legal guardian's consent to make this payment, and I accept the",
  "paywall.confirme": "Payment confirmed. Your Premium access is live \u2014 enjoy the practice.",
  "paywall.confirmer_age": "First confirm that you are {n} or have your legal guardian's consent.",
  "paywall.demarrage_echec": "Payment could not start. Try again in a moment.",
  "paywall.non_confirme": "We could not confirm this payment. If you have been charged, get in touch.",
  "paywall.portail_echec": "Could not open the subscription portal.",
  "paywall.portail_indispo": "Portal unavailable.",
  "paywall.reassurance": "Secure payment by Stripe \u00b7 Cancel in one click \u00b7 No card details on our servers",
  "paywall.recu": "Payment received. Your access will switch on within a few seconds.",
  "paywall.session_indispo": "Payment session unavailable.",
  "paywall.sur_fin": "Nicely done",
  "paywall.sur_quota": "Your {n} free sessions are used up",
  "paywall.titre_fin": "Take it up a level",
  "paywall.titre_quota": "Keep practising",
  "paywall.verif_impossible": "Payment cannot be verified right now. Reload the page in a moment.",
  "pied.droits": "Oralixia. All rights reserved. Oralixia is a practice tool: questions and feedback are generated automatically and are neither an official assessment nor a guarantee of success.",
  "quota.epuisees": "Free sessions used up",
  "quota.premium": "Premium \u00b7 unlimited sessions",
  "quota.restante": "{n} free session left",
  "quota.restantes": "{n} free sessions left",
  "rapport.a_renforcer": "To strengthen",
  "rapport.ce_qui_fonctionne": "What works",
  "rapport.micro_pour_mesure": "Answer into the microphone to measure this",
  "rapport.mots_min": "{n} words/min",
  "rapport.mots_par_phrase": "{n} words per sentence on average",
  "rapport.non_mesure": "not measured",
  "rapport.question_passee": "Question skipped.",
  "rapport.reponse_reecrite": "Rewritten answer",
  "rapport.rythme_ideal": "Ideal pace",
  "rapport.s_de_parole": "{n} s of speaking",
  "rapport.titre_pdf": "Oralixia - report of {date}",
  "rapport.trop_rapide": "Too fast",
  "rapport.un_peu_lent": "A little slow",
  "rapport.verdict.base": "Good base, needs tightening",
  "rapport.verdict.pret": "You are ready",
  "rapport.verdict.pret_detail": "Your answers are structured and backed by facts. Just take the weakest questions below again, then run one more pass under exam conditions.",
  "rapport.verdict.retravailler": "Needs work before the day",
  "rapport.verdict.retravailler_detail": "Work first on the points flagged question by question, then run another session: repetition is what builds the reflexes.",
  "rapport.vocabulaire_enrichir": "Vocabulary to broaden",
  "rapport.vocabulaire_varie": "Varied vocabulary",
  "rapport.votre_reponse": "What you answered",
  "refus.coach": "You have used your {n} coach exchanges for today. Come back tomorrow, or go Premium for unlimited access.",
  "refus.connexion": "Create a free account to start a session: your {n} free sessions are tied to it.",
  "refus.defaut": "Quota used up.",
  "refus.quota": "Your {n} free sessions have been used. Go Premium to carry on.",
  "relecture.envoyer_au_coach": "Analyse with the coach",
  "relecture.lu_entete": "Session of {date}.",
  "relecture.telecharger": "Download as PDF",
  "relecture.titre_pdf": "{type} of {date}",
  "secours.brevet.0.cat": "Presentation",
  "secours.brevet.0.q": "Describe {sujet|your work placement or your project} in a few sentences.",
  "secours.brevet.1.cat": "Discovery",
  "secours.brevet.1.q": "Describe a typical day: what were you actually doing?",
  "secours.brevet.2.cat": "Analysis",
  "secours.brevet.2.q": "What surprised you most, for better or worse?",
  "secours.brevet.3.cat": "Jobs",
  "secours.brevet.3.q": "Which job did you observe, and what does it really involve?",
  "secours.brevet.4.cat": "Skills",
  "secours.brevet.4.q": "What qualities does that job require?",
  "secours.brevet.5.cat": "Career plans",
  "secours.brevet.5.q": "Did this experience change anything about your plans?",
  "secours.brevet.6.cat": "Perspective",
  "secours.brevet.6.q": "If you could do this placement again, what would you do differently?",
  "secours.concours.0.cat": "Motivation",
  "secours.concours.0.q": "Why this school, and not another of the same standing?",
  "secours.concours.1.cat": "Personality",
  "secours.concours.1.q": "What is the hardest decision you have had to make?",
  "secours.concours.2.cat": "Background",
  "secours.concours.2.q": "Your file mentions {0|your studies}: what do you take from them?",
  "secours.concours.3.cat": "General knowledge",
  "secours.concours.3.q": "Which news story has struck you these past months, and why?",
  "secours.concours.4.cat": "Scenario",
  "secours.concours.4.q": "You are leading a group that has stalled three days before the deadline. What do you do?",
  "secours.concours.5.cat": "Commitment",
  "secours.concours.5.q": "Tell me about a voluntary, sporting or personal commitment that defines you.",
  "secours.concours.6.cat": "Plans",
  "secours.concours.6.q": "Where do you see yourself five years after leaving the school?",
  "secours.concours.7.cat": "Pressure",
  "secours.concours.7.q": "What in your file might give the panel pause?",
  "secours.entretien.0.cat": "Background",
  "secours.entretien.0.q": "Introduce yourself in two minutes, keeping only what sheds light on this role.",
  "secours.entretien.1.cat": "Motivation",
  "secours.entretien.1.q": "What exactly attracts you to this vacancy, beyond the sector?",
  "secours.entretien.2.cat": "Skills",
  "secours.entretien.2.q": "The advert insists on \u201c{0|rigour}\u201d. Tell me about a situation where you demonstrated it.",
  "secours.entretien.3.cat": "Scenario",
  "secours.entretien.3.q": "Your first week is about {1|an unfamiliar case}. Where do you start?",
  "secours.entretien.4.cat": "Skills",
  "secours.entretien.4.q": "Tell me about a piece of work on {2|a quantified project}: what was your concrete contribution?",
  "secours.entretien.5.cat": "Perspective",
  "secours.entretien.5.q": "Tell me about a professional or academic failure and what you took from it.",
  "secours.entretien.6.cat": "Teamwork",
  "secours.entretien.6.q": "A disagreement with a colleague over a method: how do you handle it?",
  "secours.entretien.7.cat": "Outlook",
  "secours.entretien.7.q": "Where do you want to be in three years, and how does this role contribute?",
  "secours.entretien.8.cat": "Pressure",
  "secours.entretien.8.q": "Your profile lacks experience in this area. Why you rather than an experienced candidate?",
  "secours.grand-oral.0.cat": "Topic",
  "secours.grand-oral.0.q": "Present your question and explain why you chose it.",
  "secours.grand-oral.1.cat": "Argument",
  "secours.grand-oral.1.q": "What is your main thesis, and which arguments support it?",
  "secours.grand-oral.2.cat": "Knowledge",
  "secours.grand-oral.2.q": "Define precisely \u201c{0|the central concept}\u201d of your topic.",
  "secours.grand-oral.3.cat": "Counter-argument",
  "secours.grand-oral.3.q": "Someone argues the exact opposite of your conclusion. What do you say to them?",
  "secours.grand-oral.4.cat": "Example",
  "secours.grand-oral.4.q": "Give a concrete example \u2014 quantified or historical \u2014 that supports your case.",
  "secours.grand-oral.5.cat": "Link to your plans",
  "secours.grand-oral.5.q": "How does this work inform your study and career plans?",
  "secours.grand-oral.6.cat": "Opening out",
  "secours.grand-oral.6.q": "What limitation do you see in your own answer?",
  "secours.grand-oral.7.cat": "Method",
  "secours.grand-oral.7.q": "Which sources did you use, and how did you check their reliability?",
  "secours.langue-de.0.cat": "Introduction",
  "secours.langue-de.1.cat": "Description",
  "secours.langue-de.2.cat": "Opinion",
  "secours.langue-de.3.cat": "Argument",
  "secours.langue-de.4.cat": "Scenario",
  "secours.langue-de.5.cat": "Outlook",
  "secours.langue-es.0.cat": "Introduction",
  "secours.langue-es.1.cat": "Description",
  "secours.langue-es.2.cat": "Opinion",
  "secours.langue-es.3.cat": "Argument",
  "secours.langue-es.4.cat": "Scenario",
  "secours.langue-es.5.cat": "Outlook",
  "secours.langue.0.cat": "Personal question",
  "secours.langue.1.cat": "Description",
  "secours.langue.2.cat": "Opinion",
  "secours.langue.3.cat": "Argument",
  "secours.langue.4.cat": "Scenario",
  "secours.langue.5.cat": "Comparison",
  "secours.langue.6.cat": "Outlook",
  "secours.matiere.0.cat": "Definition",
  "secours.matiere.0.q": "Define \u201c{0|the central concept of the chapter}\u201d.",
  "secours.matiere.1.cat": "Knowledge",
  "secours.matiere.1.q": "What are the essential points to remember about {sujet|this topic}?",
  "secours.matiere.2.cat": "Chronology",
  "secours.matiere.2.q": "Place this topic in context: when, where, why?",
  "secours.matiere.3.cat": "Analysis",
  "secours.matiere.3.q": "Explain the link between {1|the causes} and {2|the consequences}.",
  "secours.matiere.4.cat": "Example",
  "secours.matiere.4.q": "Give a precise example that illustrates what you have just explained.",
  "secours.matiere.5.cat": "Going deeper",
  "secours.matiere.5.q": "What is the main difficulty or controversy on this point?",
  "secours.matiere.6.cat": "Summary",
  "secours.matiere.6.q": "Sum up the essentials in one minute, as if explaining it to a classmate.",
  "secours.pitch.0.cat": "Problem",
  "secours.pitch.0.q": "In one sentence: what problem do you solve, and for whom?",
  "secours.pitch.1.cat": "Solution",
  "secours.pitch.1.q": "What makes your solution hard to copy?",
  "secours.pitch.2.cat": "Market",
  "secours.pitch.2.q": "How big is your market, and how did you size it?",
  "secours.pitch.3.cat": "Model",
  "secours.pitch.3.q": "How do you make money, and from what volume?",
  "secours.pitch.4.cat": "Competition",
  "secours.pitch.4.q": "Why don't your customers simply stay with {0|the current solution}?",
  "secours.pitch.5.cat": "Objection",
  "secours.pitch.5.q": "Has your main assumption been validated? By what?",
  "secours.pitch.6.cat": "Team",
  "secours.pitch.6.q": "Why is your team the right one to execute this?",
  "secours.pitch.7.cat": "Traction",
  "secours.pitch.7.q": "What figures can you show today?",
  "sim.0_mot": "0 words",
  "sim.1_min": "1 min",
  "sim.2_min": "2 min",
  "sim.5_min": "5 min",
  "sim.a_l_ecoute": "Listening\u2026",
  "sim.aide_completer": "Fill in both fields to start.",
  "sim.aide_compte": "One last step: a free account, to tie your two free sessions to.",
  "sim.aide_duree": "Estimated length: about {n} minutes.",
  "sim.aide_quota": "Your free sessions are used up: go Premium to carry on.",
  "sim.arreter_dictee": "Stop",
  "sim.bienveillant": "Supportive",
  "sim.ca_vous_a_servi": "Did this help?",
  "sim.ce_bilan_est_enregistre": "This report is saved",
  "sim.choisis_ton_epreuve_depose_tes_documents_regle_le_fo": "Pick your exam, drop in your documents, set the format. The first question lands thirty seconds later.",
  "sim.chrono_bascule": "Exam conditions: moving on automatically in {n} s.",
  "sim.chrono_depasse": "You are over the suggested time. Wrap up.",
  "sim.chrono_en_pause": "Paused.",
  "sim.chrono_sans_pause": "Exam conditions: no pausing.",
  "sim.chrono_tourne": "The clock is running, but it won't cut you off.",
  "sim.clarte": "Clarity",
  "sim.completez_les_deux_champs_pour_demarrer": "Fill in both fields to start.",
  "sim.debit_de_parole": "Speaking pace",
  "sim.dictee_indisponible": "Dictation is not available in this browser.",
  "sim.dicter": "Dictate",
  "sim.documents_lus_navigateur": "Documents read in your browser, never stored",
  "sim.eloquence_et_voix": "Delivery and voice",
  "sim.enregistrement_arrete": "Recording stopped. Re-read and correct if needed.",
  "sim.exigeant": "Demanding",
  "sim.importer_fichier": "Import a file, or drop it here",
  "sim.intitule_missions_profil_recherche": "Title, duties, profile sought",
  "sim.jecoute": "Listening \u2014 press to stop",
  "sim.l_offre_d_emploi": "The job ad",
  "sim.laisser_un_avis": "Leave a review",
  "sim.le_chrono_tourne": "The clock is running.",
  "sim.le_format_de_l_epreuve": "The exam format",
  "sim.lecture_auto": "The examiner speaks",
  "sim.lecture_auto_aide": "Every question is read out loud, just like on the day.",
  "sim.matiere": "Subject",
  "sim.mettre_en_pause": "Pause",
  "sim.micro_echec": "The microphone could not start.",
  "sim.minimum": "Minimum {n} characters.",
  "sim.minimum_150_caracteres": "Minimum 150 characters.",
  "sim.minimum_200_caracteres": "Minimum 200 characters.",
  "sim.mode_demo": "Demo mode: the API did not respond, so questions and feedback were generated locally. This session does not count against your free quota.",
  "sim.mode_reel": "Exam conditions",
  "sim.mode_reel_actif": "Exam conditions: strict clock, no pausing.",
  "sim.mode_reel_aide": "Strict timer, no pause, automatic move to the next question.",
  "sim.modifier_mes_documents": "Change my documents",
  "sim.mot": "{n} word",
  "sim.mots": "{n} words",
  "sim.mots_reponse": "Words / answer",
  "sim.nombre_de_questions": "Number of questions",
  "sim.parcours_missions_resultats": "Background, roles, results",
  "sim.parlez": "Speak normally, your answer writes itself.",
  "sim.parlez_normalement_votre_reponse_s_ecrit_toute_seule": "Speak normally: your answer writes itself.",
  "sim.passer_cette_question": "Skip this question",
  "sim.pause": "Pause",
  "sim.pause_interdite": "Exam conditions do not allow pausing.",
  "sim.pdf_word_image_ou_texte_colle_tes_fichiers_sont_lus_": "PDF, Word, image or pasted text. Your files are read in your browser, never stored.",
  "sim.pendant_que_vous_attendez": "While you wait",
  "sim.placeholder_cv": "Paste or import your CV\u2026",
  "sim.placeholder_offre": "Paste the full job advert\u2026",
  "sim.placeholder_reponse": "You can also type straight in here.",
  "sim.preparation_de_votre_oral": "Preparing your exam",
  "sim.quel_oral_prepares_tu": "Which oral exam are you preparing?",
  "sim.quelques_secondes_l_examinateur_se_prepare": "A few seconds \u2014 the examiner is getting ready.",
  "sim.question": "Question",
  "sim.questions": "Questions",
  "sim.quitter": "Leave",
  "sim.rapport_de_simulation": "Session report",
  "sim.reecouter": "Replay the question",
  "sim.refaire_une_simulation": "Run another session",
  "sim.repondre_a_l_oral": "Answer out loud",
  "sim.repondre_oral": "Answer out loud",
  "sim.reponse_par_reponse": "Answer by answer",
  "sim.reprendre": "Resume",
  "sim.retrouvez_le_quand_vous_voulez_dans_mes_simulations_": "Find it whenever you like under \"My past sessions\", with the questions asked, your answers and the examiner's full correction.",
  "sim.richesse_du_vocabulaire": "Vocabulary range",
  "sim.simulation": "Session",
  "sim.standard": "Standard",
  "sim.sur": "of",
  "sim.sur_100": "out of 100",
  "sim.telecharger_le_bilan_en_pdf": "Download the report as PDF",
  "sim.temps_de_parole": "Speaking time",
  "sim.temps_par_reponse": "Time per answer",
  "sim.terminer": "Finish and see the report",
  "sim.tes_documents": "Your documents",
  "sim.ton_de_l_examinateur": "Examiner tone",
  "sim.valider": "Confirm and continue",
  "sim.valider_et_continuer": "Submit and continue",
  "sim.voix_absente": "Voice answering is not available in this browser. Use Chrome, Edge or Safari, or type your answer.",
  "sim.votre_cv": "Your CV",
  "sim.votre_reponse": "Your answer",
  "sim.votre_retour_aide_les_prochains_candidats_a_se_lance": "Your feedback helps the next candidates take the plunge. It is checked before publication.",
  "sim.zero_mot": "0 words",
  "temoin.a_votre_tour": "Your turn.",
  "temoin.chaque_avis_publie_ici_a_ete_depose_par_une_personne": "Every review published here was left by someone who sat a session, and checked before going live. No testimonial is written by us.",
  "temoin.deux_simulations_offertes_sans_carte": "Two full sessions free when you create your account, no card.",
  "temoin.envoyer_mon_avis": "Send my review",
  "temoin.epreuve_preparee": "Exam prepared",
  "temoin.merci_votre_avis_part_en_verification_il_apparaitra_": "Thank you. Your review is being checked and will appear on this page once approved.",
  "temoin.note_sur_5": "Rating out of 5",
  "temoin.placeholder_avis": "What helped you, what changed on the day\u2026",
  "temoin.placeholder_nom": "First name L., your situation",
  "temoin.prenom_et_statut": "First name and situation",
  "temoin.racontez_ce_qui_vous_a_servi_et_ce_qui_vous_a_manque": "Tell us what helped and what was missing. Your review is checked before publication: we don't remove negative reviews, only ones that are unreadable, abusive or off topic.",
  "temoin.votre_note": "Your rating",
  "temoin.votre_retour": "Your feedback",
  "temoin.vous_avez_passe_votre_oral": "Sat your oral exam?",
  "titre.auth_volet": "One account, and<br>the panel can wait.",
  "titre.ce_que_disent": "What our users<br class=\"hidden sm:block\"> have to say",
  "titre.chaque_oral": "Every exam has <span class=\"marqueur\">its own rules</span>.",
  "titre.debit_clarte": "Your pace,<br>your clarity, your nerves",
  "titre.examinateur_parle": "The examiner<br>really speaks to you",
  "titre.hero_accueil": "Pass your oral<br><span class=\"marqueur\">first time</span>.",
  "titre.hero_simulateur": "Your oral exam in <span class=\"marqueur\">three steps</span>.",
  "titre.hero_temoignages": "Their words, <span class=\"marqueur\">not our promises</span>.",
  "titre.jour_j": "The real day shouldn't be <span class=\"marqueur\">your first time</span>.",
  "titre.ou_tu_perds": "See exactly<br>where you lose points",
  "titre.plateforme": "Your <span class=\"marqueur\">all-in-one</span> platform<br class=\"hidden sm:block\"> for oral exam prep.",
  "type.brevet.categorie.0": "Presentation",
  "type.brevet.categorie.1": "What you discovered",
  "type.brevet.categorie.2": "Analysis",
  "type.brevet.categorie.3": "Looking ahead",
  "type.brevet.champA.aide": "Internship, careers project, cross-subject project, arts project",
  "type.brevet.champA.label": "Your presentation topic",
  "type.brevet.champA.placeholder": "e.g. \u201cMy Year 10 internship at an accountancy firm\u201d",
  "type.brevet.champB.aide": "How it went, the jobs you saw, what you took from it",
  "type.brevet.champB.label": "What you want to tell them",
  "type.brevet.champB.placeholder": "Your notes, your slides, your report\u2026",
  "type.brevet.court": "Brevet / Year 10",
  "type.brevet.critere.0": "Clarity of the presentation",
  "type.brevet.critere.1": "Depth of content",
  "type.brevet.critere.2": "Answers to questions",
  "type.brevet.critere.3": "Spoken delivery",
  "type.brevet.nom": "Brevet oral (internship or project defence)",
  "type.concours.categorie.0": "Motivation",
  "type.concours.categorie.1": "Personality",
  "type.concours.categorie.2": "General knowledge",
  "type.concours.categorie.3": "Current affairs",
  "type.concours.categorie.4": "Scenario",
  "type.concours.champA.aide": "Education, experience, commitments",
  "type.concours.champA.label": "Your CV or your background",
  "type.concours.champA.placeholder": "Paste or import your CV\u2026",
  "type.concours.champB.aide": "Programme, values, what the panel expects",
  "type.concours.champB.label": "The school, exam or position you are aiming for",
  "type.concours.champB.placeholder": "Description of the school, the course, the exam\u2026",
  "type.concours.court": "Exam / School",
  "type.concours.critere.0": "Coherence of your plans",
  "type.concours.critere.1": "Knowledge of the school",
  "type.concours.critere.2": "General knowledge and current affairs",
  "type.concours.critere.3": "Poise and confidence",
  "type.concours.nom": "Motivation interview, competitive exam or selective school",
  "type.entretien.categorie.0": "Background",
  "type.entretien.categorie.1": "Motivation",
  "type.entretien.categorie.2": "Skills",
  "type.entretien.categorie.3": "Scenario",
  "type.entretien.categorie.4": "Perspective",
  "type.entretien.categorie.5": "Looking ahead",
  "type.entretien.champA.aide": "Background, responsibilities, results",
  "type.entretien.champA.label": "Your CV",
  "type.entretien.champA.placeholder": "Paste or import your CV\u2026",
  "type.entretien.champB.aide": "Title, responsibilities, profile sought",
  "type.entretien.champB.label": "The job advert",
  "type.entretien.champB.placeholder": "Paste the full advert\u2026",
  "type.entretien.court": "Interview / Internship",
  "type.entretien.critere.0": "Structure of the answer",
  "type.entretien.critere.1": "Fit with the advert",
  "type.entretien.critere.2": "Evidence and figures",
  "type.entretien.critere.3": "Concision",
  "type.entretien.nom": "Job or internship interview",
  "type.grand-oral.categorie.0": "Subject",
  "type.grand-oral.categorie.1": "Argument",
  "type.grand-oral.categorie.2": "Counter-argument",
  "type.grand-oral.categorie.3": "Link to your plans",
  "type.grand-oral.categorie.4": "Wider view",
  "type.grand-oral.champA.aide": "The question chosen and its problem statement",
  "type.grand-oral.champA.label": "Your Grand Oral question",
  "type.grand-oral.champA.placeholder": "e.g. \u201cTo what extent does public debt constrain\u2026\u201d",
  "type.grand-oral.champB.aide": "Detailed outline, arguments, examples, link to your plans",
  "type.grand-oral.champB.label": "Your notes or your outline",
  "type.grand-oral.champB.placeholder": "Paste or import your outline, your notes\u2026",
  "type.grand-oral.court": "Grand Oral",
  "type.grand-oral.critere.0": "Command of the subject",
  "type.grand-oral.critere.1": "Quality of the argument",
  "type.grand-oral.critere.2": "Perspective and career plans",
  "type.grand-oral.critere.3": "Delivery and conviction",
  "type.grand-oral.nom": "Grand Oral (French baccalaureate)",
  "type.langue.categorie.0": "Personal question",
  "type.langue.categorie.1": "Description",
  "type.langue.categorie.2": "Opinion",
  "type.langue.categorie.3": "Argument",
  "type.langue.categorie.4": "Situation",
  "type.langue.champA.aide": "Current level, target score, deadline",
  "type.langue.champA.label": "Your level and your goal",
  "type.langue.champA.placeholder": "e.g. \u201cSolid B1, aiming for 850 on the TOEIC in March\u201d",
  "type.langue.champB.aide": "Exam topics, vocabulary to revise",
  "type.langue.champB.label": "Themes to work on",
  "type.langue.champB.placeholder": "Work, studies, environment, technology\u2026",
  "type.langue.court": "Language oral",
  "type.langue.critere.0": "Fluency",
  "type.langue.critere.1": "Grammar and structures",
  "type.langue.critere.2": "Range of vocabulary",
  "type.langue.critere.3": "Pronunciation and intonation",
  "type.langue.nom": "Language certification (TOEIC, TOEFL, IELTS\u2026)",
  "type.langue.souschoix.0": "TOEIC Speaking",
  "type.langue.souschoix.1": "TOEFL iBT Speaking",
  "type.langue.souschoix.2": "IELTS Speaking",
  "type.langue.souschoix.3": "Cambridge B2 First",
  "type.langue.souschoix.4": "Cambridge C1 Advanced",
  "type.langue.souschoix.5": "DELE (Spanish)",
  "type.langue.souschoix.6": "Goethe-Zertifikat (German)",
  "type.langue.souschoix.7": "Other",
  "type.langue.souschoix.label": "Certification",
  "type.matiere.categorie.0": "Definition",
  "type.matiere.categorie.1": "Knowledge",
  "type.matiere.categorie.2": "Analysis",
  "type.matiere.categorie.3": "Example",
  "type.matiere.categorie.4": "Going further",
  "type.matiere.champA.aide": "What you will be questioned on",
  "type.matiere.champA.label": "The topic or the chapter",
  "type.matiere.champA.placeholder": "e.g. \u201cThe Cold War, 1947-1991\u201d",
  "type.matiere.champB.aide": "The material you need to master",
  "type.matiere.champB.label": "Your lesson or your notes",
  "type.matiere.champB.placeholder": "Paste or import your lesson, your revision notes\u2026",
  "type.matiere.court": "Subject oral",
  "type.matiere.critere.0": "Accuracy of knowledge",
  "type.matiere.critere.1": "Structure of the answer",
  "type.matiere.critere.2": "Subject vocabulary",
  "type.matiere.critere.3": "Examples used",
  "type.matiere.nom": "School subject oral",
  "type.matiere.souschoix.0": "History and geography",
  "type.matiere.souschoix.1": "French",
  "type.matiere.souschoix.10": "Other",
  "type.matiere.souschoix.2": "Mathematics",
  "type.matiere.souschoix.3": "Economics and social science",
  "type.matiere.souschoix.4": "Physics and chemistry",
  "type.matiere.souschoix.5": "Biology and earth science",
  "type.matiere.souschoix.6": "Philosophy",
  "type.matiere.souschoix.7": "Spanish",
  "type.matiere.souschoix.8": "German",
  "type.matiere.souschoix.9": "Law",
  "type.matiere.souschoix.label": "Subject",
  "type.pitch.categorie.0": "Problem",
  "type.pitch.categorie.1": "Solution",
  "type.pitch.categorie.2": "Market",
  "type.pitch.categorie.3": "Business model",
  "type.pitch.categorie.4": "Objection",
  "type.pitch.champA.aide": "Problem solved, solution, market, business model",
  "type.pitch.champA.label": "Your project",
  "type.pitch.champA.placeholder": "Describe your project, your product, your startup\u2026",
  "type.pitch.champB.aide": "Panel, investors, client, teachers",
  "type.pitch.champB.label": "Your audience",
  "type.pitch.champB.placeholder": "Who are you presenting to, and what do they expect?",
  "type.pitch.court": "Pitch / Presentation",
  "type.pitch.critere.0": "Clarity of the problem",
  "type.pitch.critere.1": "Soundness of the model",
  "type.pitch.critere.2": "Impact of the storytelling",
  "type.pitch.critere.3": "Answers to objections",
  "type.pitch.nom": "Project presentation or pitch",
  "voix.arreter": "Stop",
  "voix.ecouter": "Listen"
};
