/* Traductions anglaises.
   Le français reste la langue de référence : toute clé absente
   d'ici retombe sur le texte français présent dans le HTML.
   Les textes légaux (mentions, CGV, RGPD) restent en français :
   ce sont des documents de droit français, une traduction
   approximative y ferait plus de mal que de bien. */

export default {
  "titre.auth_volet": "One account, and<br>the panel can wait.",
  "auth.se_connecter": "Sign in",
  "auth.inscription": "Sign up",
  "auth.creer_mon_compte": "Create my account",
  "auth.continuer_google": "Continue with Google",
  "auth.ou": "or",
  "auth.adresse_email": "Email address",
  "auth.mot_de_passe": "Password",
  "auth.mot_de_passe_oublie": "Forgot your password?",
  "auth.confirmer_mot_de_passe": "Confirm password",
  "auth.lien_sans_mot_de_passe": "Email me a link instead",
  "auth.prenom": "First name",
  "auth.nom": "Last name",
  "auth.en_continuant": "By continuing, you accept the",
  "auth.et_la": "and the",
  "auth.politique_confidentialite": "privacy policy",
  "auth.volet_intro": "Two full sessions on the house when you create your account. No card required.",
  "auth.avantage_deux_simulations": "2 free sessions, from the moment you sign up",
  "auth.avantage_relire": "Re-read your feedback whenever you like",
  "auth.avantage_progression": "Follow your progress curve",
  "auth.avantage_appareils": "Pick up your access on any device",
  "auth.raison_simulation": "Create your free account to start your session: your two free sessions are tied to it.",
  "auth.email_invalide": "Enter a valid email address.",
  "auth.mdp_requis": "Enter your password.",
  "auth.prenom_requis": "Tell us your first name.",
  "auth.confirmation_differente": "The two passwords do not match.",
  "auth.force_court": "Too short: eight characters minimum.",
  "auth.force_moyen": "Fine. A digit and a capital would make it sturdier.",
  "auth.force_bon": "Good password.",
  "auth.connexion_en_cours": "Signing in…",
  "auth.creation_en_cours": "Creating your account…",
  "auth.bienvenue": "You're in.",
  "auth.compte_cree": "Account created. Your two free sessions are waiting.",
  "auth.confirmez_boite_mail": "Account created. Open your inbox and click the link to activate it.",
  "auth.lien_envoye": "Link sent. Open your inbox to sign in.",
  "auth.deconnecte": "You are signed out.",
  "compte.mon_compte": "My account",
  "compte.gerer_mon_compte": "Manage my account",
  "compte.premium_actif": "Premium active",
  "compte.offre_gratuite": "Free plan",
  "compte.actif_jusquau": "Active until {date}",
  "compte.abonnement_actif": "Subscription active. Thank you!",
  "compte.mode_local": "Local mode: your history is stored in this browser only. Add your Supabase keys to sync across devices.",
  "paywall.sur_fin": "Nicely done",
  "paywall.titre_fin": "Take it up a level",
  "paywall.sur_quota": "Your {n} free sessions are used up",
  "paywall.titre_quota": "Keep practising",
  "sim.aide_completer": "Fill in both fields to start.",
  "sim.aide_compte": "One last step: a free account, to tie your two free sessions to.",
  "sim.aide_quota": "Your free sessions are used up: go Premium to carry on.",
  "sim.aide_duree": "Estimated length: about {n} minutes.",
  "avis.vide_titre": "No published reviews yet.",
  "avis.vide_texte": "The feedback shown here will come from real people who sat a session, checked before publication. Just finished an oral exam?",
  "avis.vide_lien": "Yours could be the first.",
  "cta.premiere_simulation": "Start my first session",
  "cta.lancer_simulation": "Start my session",
  "cta.tous_temoignages": "See all testimonials",
  "cta.mes_simulations": "See my past sessions",
  "offre.equivalent": "{m} per month · {e} less than six months at the monthly rate",
  "quota.premium": "Premium · unlimited sessions",
  "quota.restante": "{n} free session left",
  "quota.restantes": "{n} free sessions left",
  "quota.epuisees": "Free sessions used up",
  "offre.pass48.accroche": "The night before",
  "offre.pass48.detail": "Full access for 48 hours. One-off payment, no renewal.",
  "offre.mensuel.accroche": "Most flexible",
  "offre.mensuel.detail": "Unlimited sessions, full reports, AI coach. No commitment, cancel in one click.",
  "offre.extra.accroche": "A whole school year",
  "offre.extra.detail": "Six months of full access, paid once. Made for several deadlines in a row.",
  "offre.periode.une_fois": "one-off",
  "offre.periode.par_mois": "per month",
  "offre.periode.pour_6_mois": "for 6 months",
  "offre.recommande": "Recommended",
  "chargement.questions.titre": "Preparing your exam",
  "chargement.questions.etape0": "Reading your documents",
  "chargement.questions.etape1": "Spotting what the panel will dig into",
  "chargement.questions.etape2": "Writing the examiner's questions",
  "chargement.questions.etape3": "Ordering the run",
  "chargement.questions.conseil0": "Breathe before answering. Two seconds of silence beat a three-second \"um\".",
  "chargement.questions.conseil1": "A good answer has three beats: the situation, what you did, the result.",
  "chargement.questions.conseil2": "Panels remember the first and last sentence. Polish them.",
  "chargement.questions.conseil3": "One concrete figure beats three adjectives.",
  "chargement.questions.conseil4": "If a question surprises you, rephrase it: you gain five seconds to think.",
  "chargement.correction.titre": "Analysing your performance",
  "chargement.correction.etape0": "Rereading your answers",
  "chargement.correction.etape1": "Scoring the substance, answer by answer",
  "chargement.correction.etape2": "Measuring pace and vocabulary range",
  "chargement.correction.etape3": "Writing your areas to improve",
  "chargement.correction.conseil0": "The correction is blunt: that's what makes it useful.",
  "chargement.correction.conseil1": "Start with your lowest-scoring question, not the first one.",
  "chargement.correction.conseil2": "Running another session right after reading the report is the best moment to improve.",
  "chargement.correction.conseil3": "An over-long answer costs more points than a short one.",
  "ecoute.ecouter": "Listen",
  "ecoute.arreter": "Stop",
  "ecoute.bilan": "Listen to the report",
  "accueil.documents_lus_puis_supprimes": "Documents read then deleted, never resold",
  "sim.documents_lus_navigateur": "Documents read in your browser, never stored",
  "accueil.paiement_securise_stripe": "Secure payment by Stripe",
  "titre.hero_accueil": "Pass your oral<br><span class=\"marqueur\">first time</span>.",
  "titre.plateforme": "Your <span class=\"marqueur\">all-in-one</span> platform<br class=\"hidden sm:block\"> for oral exam prep.",
  "titre.examinateur_parle": "The examiner<br>really speaks to you",
  "titre.ou_tu_perds": "See exactly<br>where you lose points",
  "titre.debit_clarte": "Your pace,<br>your clarity, your nerves",
  "titre.chaque_oral": "Every exam has <span class=\"marqueur\">its own rules</span>.",
  "titre.ce_que_disent": "What our users<br class=\"hidden sm:block\"> have to say",
  "titre.jour_j": "The real day shouldn't be <span class=\"marqueur\">your first time</span>.",
  "titre.tes_progres": "Your progress<br>is waiting",
  "titre.hero_simulateur": "Your oral exam in <span class=\"marqueur\">three steps</span>.",
  "titre.hero_temoignages": "Their words, <span class=\"marqueur\">not our promises</span>.",
  "accueil.retours_de_candidats_apres_leur_oral_verifies_avant_": "Feedback from candidates after their exam, checked before publication.",
  "accueil.sans_engagement_depuis_le_portail_client_stripe": "No commitment, from the Stripe customer portal.",
  "accueil.simulations_offertes_sans_carte": "full sessions free with your account, no card",
  "accueil.simulations_illimitees_rapports_detailles_et_coach_i": "Unlimited sessions, detailed reports and unlimited AI coach.",
  "accueil.some_people_say_studying_abroad_is_essential_do_you_": "\"Some people say studying abroad is essential. Do you agree? Give reasons and examples.\"",
  "accueil.resiliable_en_un_clic": "Cancel in one click",
  "accueil.se_deconnecter": "Sign out",
  "accueil.simulation_passee": "Past session",
  "accueil.structure_de_la_reponse": "Answer structure",
  "accueil.tes_documents_restent_a_toi": "Your documents stay yours",
  "accueil.1_19_restantes_78_mots_dictes": "1:19 left · 78 words dictated",
  "accueil.accepter": "Accept",
  "accueil.accueil": "Home",
  "accueil.adresse_e_mail": "Email address",
  "accueil.aller_au_contenu": "Skip to content",
  "accueil.appuyez_sur_le_micro_pour_parler_a_votre_coach": "Press the mic to speak to your coach.",
  "accueil.arrete_de_repeter_dans_le_vide_entraine_toi_en_condi": "Stop rehearsing into the void. Practise under real conditions, see exactly where you lose points, and fix every answer with a detailed correction.",
  "accueil.aucune_promesse_de_note": "No promised grade",
  "accueil.axes_notes_a_chaque_passage_contenu_structure_eloque": "areas scored every run: content, structure, delivery and speaking pace",
  "accueil.brevet_3e": "Brevet · Year 10",
  "accueil.certification": "Certification",
  "accueil.cette_information_sert_uniquement_a_appliquer_la_reg": "This is used only to apply the regulations. It is never shared.",
  "accueil.chaque_reponse_est_notee_sur_20_et_decomposee_ce_qui": "Every answer is scored out of 20 and broken down: what works, what's missing, and a short rewrite of what you could have said instead. No polite praise — if an answer is hollow, it says so.",
  "accueil.coach_ia": "AI Coach",
  "accueil.collez_votre_plan_votre_texte_ou_votre_sujet_et_disc": "Paste your outline, your script or your topic and talk it through before you start: structure, rewording, opening hook, panel questions. In writing or out loud.",
  "accueil.compte": "Account",
  "accueil.concision": "Concision",
  "accueil.concours": "Entrance exam",
  "accueil.connexion": "Log in",
  "accueil.connexion_inscription": "Log in / Sign up",
  "accueil.continue_a_travailler_tes_oraux_la_ou_tu_t_etais_arr": "Pick up your speaking practice right where you left off.",
  "accueil.continuer": "Continue",
  "accueil.continuez_a_vous_entrainer": "Keep practising",
  "accueil.criteres_notes": "Scored criteria",
  "accueil.decrivez_une_journee_type_de_votre_stage_que_faisiez": "\"Describe a typical day of your placement: what did you actually do?\"",
  "accueil.deux_simulations_offertes_sans_carte": "Two full sessions free when you create your account, no card. Ten minutes and you'll know where you stand.",
  "accueil.discussion_libre": "Open conversation",
  "accueil.e_mail_de_votre_parent_ou_responsable_legal": "Email of your parent or legal guardian",
  "accueil.effacer": "Clear",
  "accueil.en_dessous_de_15_ans_son_accord_est_necessaire_pour_": "Under 15, their consent is required for us to process your data.",
  "accueil.entretien": "Interview",
  "accueil.essayer_gratuitement": "Try it free",
  "accueil.gerer_mon_abonnement": "Manage my subscription",
  "accueil.grand_oral": "Grand Oral",
  "accueil.l_analyse_d_eloquence_mesure_ce_que_tu_n_entends_pas": "The delivery analysis measures what you can't hear yourself: words per minute, vocabulary range, sentence length. Most candidates speak too fast without realising it.",
  "accueil.l_outil_ne_remplace_ni_un_professeur_ni_un_jury_il_t": "The tool replaces neither a teacher nor a panel. It puts you through the exam once, in private, so that the real day isn't your first time.",
  "accueil.le_moyen_le_plus_rapide_de_passer_son_oral_une_premi": "The fastest way to sit your oral exam once, in private. Your CVs, topics and recordings are handled for the length of the session, then deleted: never kept, never resold, never used to train a model.",
  "accueil.lecture_audio_activee": "Audio playback: on",
  "accueil.legal": "Legal",
  "accueil.les_questions_sont_generees_a_partir_de_tes_propres_": "Questions are generated from your own documents, then read aloud. You answer into the mic while the clock runs. It's the only way to know whether your answer holds up out loud and not just on paper.",
  "accueil.lus_le_temps_de_la_simulation_jamais_conserves_ni_re": "Read for the length of the session, never kept or resold.",
  "accueil.mentions_legales": "Legal notice",
  "accueil.mes_simulations_passees": "My past sessions",
  "accueil.mon_espace": "My space",
  "accueil.note_sur_la_coherence_du_projet_et_la_culture_genera": "Scored on the coherence of your plan and general knowledge.",
  "accueil.note_sur_la_prise_de_recul_et_le_lien_au_projet_d_or": "Scored on perspective and the link to your study plans.",
  "accueil.note_sur_les_preuves_chiffrees_et_la_concision": "Scored on hard evidence and concision.",
  "accueil.parler_au_coach_ia": "Talk to the AI coach",
  "accueil.pitch": "Pitch",
  "accueil.plus_tard": "Later",
  "accueil.pose_dans_la_langue_de_l_epreuve_note_selon_le_cecrl": "Asked in the language of the exam, scored against the CEFR.",
  "accueil.pourquoi_preporal": "Why PrepOral?",
  "accueil.preporal_premium": "PrepOral Premium",
  "accueil.preporal_s_adresse_aussi_a_des_collegiens_et_lyceens": "PrepOral is also used by school pupils. French law sets different rules by age: we ask for an age bracket, never your date of birth.",
  "accueil.preuves_et_chiffres": "Evidence and figures",
  "accueil.produit": "Product",
  "accueil.progression_de_vos_notes_de_la_plus_ancienne_a_la_pl": "Your scores over time, oldest to most recent.",
  "accueil.qu_est_ce_qui_dans_votre_dossier_pourrait_faire_hesi": "\"What in your application might give the panel pause?\"",
  "accueil.quel_age_avez_vous": "How old are you?",
  "accueil.quelle_est_la_taille_de_votre_marche_et_comment_l_av": "\"How big is your market, and how did you size it?\"",
  "accueil.quelqu_un_vous_soutient_exactement_l_inverse_de_votr": "\"Someone argues the exact opposite of your conclusion. What do you say to them?\"",
  "accueil.question_3_5_mise_en_situation": "Question 3 / 5 · Scenario",
  "accueil.questions_courtes_concretes_orientees_objection": "Short, concrete questions aimed at objections.",
  "accueil.recevoir_un_lien_de_connexion": "Send me a sign-in link",
  "accueil.refuser": "Decline",
  "accueil.relecture": "Review",
  "accueil.repeter_devant_quelqu_un_coute_cher_gene_et_n_est_pa": "Rehearsing in front of someone costs money, feels awkward, and can't be done ten times over. PrepOral does the opposite: the examiner asks its questions out loud, never tires, and tells you plainly what isn't working.",
  "accueil.simulateur": "Simulator",
  "accueil.temoignages": "Testimonials",
  "accueil.tout_effacer": "Clear all",
  "accueil.types_d_oraux_couverts_entretien_grand_oral_brevet_c": "types of oral exam covered: job interview, Grand Oral, brevet, competitive entrance, pitch, subject viva",
  "accueil.un_entrainement_pas_une_garantie_de_reussite_c_est_e": "Training, not a guarantee of success. It's written into the terms of sale.",
  "accueil.un_jury_de_brevet_et_un_jury_de_grande_ecole_n_atten": "A brevet panel and a grande école panel expect different things. The examiner shifts its stance, vocabulary and marking grid to match the exam.",
  "accueil.vocabulaire_adapte_a_l_age_bienveillant_mais_exigean": "Age-appropriate vocabulary, kind but demanding.",
  "accueil.voir_les_offres": "See the plans",
  "accueil.vos_2_simulations_gratuites_sont_utilisees": "You've used your 2 free sessions",
  "accueil.votre_premiere_semaine_porte_sur_un_dossier_que_vous": "\"Your first week is on a file you don't know. Where do you start?\"",
  "accueil.votre_profil_manque_d_experience_sur_ce_perimetre_po": "\"Your profile lacks experience in this area. Why you rather than a seasoned candidate?\"",
  "accueil.votre_statut_premium_et_votre_historique_vous_suiven": "Your Premium status and your history follow you across all your devices.",
  "accueil.vous_n_etes_pas_connecte": "You're not signed in.",
  "sim.0_mot": "0 words",
  "sim.1_min": "1 min",
  "sim.2_min": "2 min",
  "sim.5_min": "5 min",
  "sim.bienveillant": "Supportive",
  "sim.ca_vous_a_servi": "Did this help?",
  "sim.ce_bilan_est_enregistre": "This report is saved",
  "sim.choisis_ton_epreuve_depose_tes_documents_regle_le_fo": "Pick your exam, drop in your documents, set the format. The first question lands thirty seconds later.",
  "sim.clarte": "Clarity",
  "sim.completez_les_deux_champs_pour_demarrer": "Fill in both fields to start.",
  "sim.debit_de_parole": "Speaking pace",
  "sim.eloquence_et_voix": "Delivery and voice",
  "sim.exigeant": "Demanding",
  "sim.intitule_missions_profil_recherche": "Title, duties, profile sought",
  "sim.l_offre_d_emploi": "The job ad",
  "sim.laisser_un_avis": "Leave a review",
  "sim.le_chrono_tourne": "The clock is running.",
  "sim.le_format_de_l_epreuve": "The exam format",
  "sim.matiere": "Subject",
  "sim.mettre_en_pause": "Pause",
  "sim.minimum_150_caracteres": "Minimum 150 characters.",
  "sim.minimum_200_caracteres": "Minimum 200 characters.",
  "sim.modifier_mes_documents": "Change my documents",
  "sim.mots_reponse": "Words / answer",
  "sim.nombre_de_questions": "Number of questions",
  "sim.parcours_missions_resultats": "Background, roles, results",
  "sim.parlez_normalement_votre_reponse_s_ecrit_toute_seule": "Speak normally: your answer writes itself.",
  "sim.passer_cette_question": "Skip this question",
  "sim.pdf_word_image_ou_texte_colle_tes_fichiers_sont_lus_": "PDF, Word, image or pasted text. Your files are read in your browser, never stored.",
  "sim.pendant_que_vous_attendez": "While you wait",
  "sim.preparation_de_votre_oral": "Preparing your exam",
  "sim.quel_oral_prepares_tu": "Which oral exam are you preparing?",
  "sim.quelques_secondes_l_examinateur_se_prepare": "A few seconds — the examiner is getting ready.",
  "sim.question": "Question",
  "sim.questions": "Questions",
  "sim.quitter": "Leave",
  "sim.rapport_de_simulation": "Session report",
  "sim.refaire_une_simulation": "Run another session",
  "sim.reponse_par_reponse": "Answer by answer",
  "sim.retrouvez_le_quand_vous_voulez_dans_mes_simulations_": "Find it whenever you like under \"My past sessions\", with the questions asked, your answers and the examiner's full correction.",
  "sim.richesse_du_vocabulaire": "Vocabulary range",
  "sim.simulation": "Session",
  "sim.standard": "Standard",
  "sim.sur_100": "out of 100",
  "sim.telecharger_le_bilan_en_pdf": "Download the report as PDF",
  "sim.temps_de_parole": "Speaking time",
  "sim.temps_par_reponse": "Time per answer",
  "sim.tes_documents": "Your documents",
  "sim.ton_de_l_examinateur": "Examiner tone",
  "sim.valider_et_continuer": "Submit and continue",
  "sim.votre_cv": "Your CV",
  "sim.votre_reponse": "Your answer",
  "sim.votre_retour_aide_les_prochains_candidats_a_se_lance": "Your feedback helps the next candidates take the plunge. It is checked before publication.",
  "temoin.a_votre_tour": "Your turn.",
  "temoin.chaque_avis_publie_ici_a_ete_depose_par_une_personne": "Every review published here was left by someone who sat a session, and checked before going live. No testimonial is written by us.",
  "temoin.deux_simulations_offertes_sans_carte": "Two full sessions free when you create your account, no card.",
  "temoin.envoyer_mon_avis": "Send my review",
  "temoin.epreuve_preparee": "Exam prepared",
  "temoin.merci_votre_avis_part_en_verification_il_apparaitra_": "Thank you. Your review is being checked and will appear on this page once approved.",
  "temoin.prenom_et_statut": "First name and situation",
  "temoin.racontez_ce_qui_vous_a_servi_et_ce_qui_vous_a_manque": "Tell us what helped and what was missing. Your review is checked before publication: we don't remove negative reviews, only ones that are unreadable, abusive or off topic.",
  "temoin.votre_note": "Your rating",
  "temoin.votre_retour": "Your feedback",
  "temoin.vous_avez_passe_votre_oral": "Sat your oral exam?"
};
