/* Traducciones al español.
   El francés sigue siendo la lengua de referencia: cualquier clave
   ausente aquí recae en el texto francés presente en el HTML o en
   el módulo que la invoca.

   Los textos jurídicos se traducen para poder entenderlos, pero el
   contrato sigue sometido al derecho francés: la ventana muestra un
   aviso indicando que solo la versión francesa da fe. */

export default {
  "a11y.changer_langue": "Cambiar de idioma",
  "a11y.changer_theme": "Cambiar de tema",
  "a11y.fermer": "Cerrar",
  "a11y.informations_legales": "Información legal",
  "a11y.langues_disponibles": "Idiomas disponibles",
  "a11y.navigation": "Navegación",
  "a11y.navigation_principale": "Navegación principal",
  "a11y.theme_clair": "Cambiar al tema claro",
  "a11y.theme_sombre": "Cambiar al tema oscuro",
  "accueil.1_19_restantes_78_mots_dictes": "1:19 restantes · 78 palabras dictadas",
  "accueil.accepter": "Aceptar",
  "accueil.accueil": "Inicio",
  "accueil.aller_au_contenu": "Ir al contenido",
  "accueil.appuyez_sur_le_micro_pour_parler_a_votre_coach": "Pulsa el micrófono para hablar con tu coach.",
  "accueil.arrete_de_repeter_dans_le_vide_entraine_toi_en_condi": "Deja de ensayar al vacío. Practica en condiciones reales, ve exactamente dónde pierdes puntos y corrige cada respuesta con una corrección detallada.",
  "accueil.aucune_promesse_de_note": "Ninguna nota prometida",
  "accueil.axes_notes_a_chaque_passage_contenu_structure_eloque": "aspectos evaluados en cada sesión: contenido, estructura, elocuencia y ritmo del habla",
  "accueil.brevet_3e": "Brevet · 4.º ESO",
  "accueil.certification": "Certificación",
  "accueil.cette_information_sert_uniquement_a_appliquer_la_reg": "Esta información solo sirve para aplicar la normativa. Nunca se comparte.",
  "accueil.chaque_reponse_est_notee_sur_20_et_decomposee_ce_qui": "Cada respuesta se puntúa sobre 20 y se desglosa: lo que funciona, lo que falta y una reescritura breve de lo que podrías haber dicho. Sin elogios de cortesía: si una respuesta está vacía, se dice.",
  "accueil.coach_ia": "Coach IA",
  "accueil.collez_votre_plan_votre_texte_ou_votre_sujet_et_disc": "Pega tu guion, tu texto o tu tema y coméntalo antes de empezar: estructura, reformulación, gancho, preguntas del tribunal. Por escrito o en voz alta.",
  "accueil.compte": "Cuenta",
  "accueil.concision": "Concisión",
  "accueil.concours": "Oposición",
  "accueil.connexion": "Iniciar sesión",
  "accueil.continuer": "Continuar",
  "accueil.continuez_a_vous_entrainer": "Sigue practicando",
  "accueil.criteres_notes": "Criterios evaluados",
  "accueil.decrivez_une_journee_type_de_votre_stage_que_faisiez": "«Describa un día normal de sus prácticas: ¿qué hacía en concreto?»",
  "accueil.deux_simulations_offertes_sans_carte": "Dos simulaciones completas gratis al crear tu cuenta, sin tarjeta. En diez minutos sabrás dónde estás.",
  "accueil.discussion_libre": "Conversación libre",
  "accueil.documents_lus_puis_supprimes": "Documentos leídos y luego eliminados, nunca revendidos",
  "accueil.e_mail_de_votre_parent_ou_responsable_legal": "Correo de tu padre, madre o tutor legal",
  "accueil.effacer": "Borrar",
  "accueil.en_dessous_de_15_ans_son_accord_est_necessaire_pour_": "Por debajo de 15 años, su consentimiento es necesario para que podamos tratar tus datos.",
  "accueil.entretien": "Entrevista",
  "accueil.essayer_gratuitement": "Probar gratis",
  "accueil.exemple_parent": "padre@ejemplo.com",
  "accueil.gerer_mon_abonnement": "Gestionar mi suscripción",
  "accueil.grand_oral": "Grand Oral",
  "accueil.l_analyse_d_eloquence_mesure_ce_que_tu_n_entends_pas": "El análisis de elocuencia mide lo que tú no oyes: palabras por minuto, riqueza de vocabulario, longitud de las frases. La mayoría de los candidatos habla demasiado rápido sin darse cuenta.",
  "accueil.l_outil_ne_remplace_ni_un_professeur_ni_un_jury_il_t": "La herramienta no sustituye ni a un profesor ni a un tribunal. Te hace pasar la prueba una primera vez, en privado, para que el día señalado no sea tu primera vez.",
  "accueil.le_moyen_le_plus_rapide_de_passer_son_oral_une_premi": "La forma más rápida de pasar tu oral una primera vez, en privado. Tus CV, temas y grabaciones se tratan durante la simulación y luego se eliminan: no se conservan, no se revenden y no se usan para entrenar ningún modelo.",
  "accueil.lecture_audio_activee": "Lectura en voz alta: activada",
  "accueil.legal": "Legal",
  "accueil.les_questions_sont_generees_a_partir_de_tes_propres_": "Las preguntas se generan a partir de tus propios documentos y se leen en voz alta. Respondes por micrófono mientras corre el cronómetro. Es la única forma de saber si tu respuesta se sostiene en voz alta y no solo sobre el papel.",
  "accueil.lus_le_temps_de_la_simulation_jamais_conserves_ni_re": "Leídos durante la simulación, nunca conservados ni revendidos.",
  "accueil.mentions_legales": "Aviso legal",
  "accueil.mes_simulations_passees": "Mis simulaciones anteriores",
  "accueil.methode_constat": "<span class=\"font-display text-3xl leading-none text-iris2\">«</span> La mayoría de los candidatos preparan su oral releyendo apuntes. El día de la prueba descubren que nunca han dicho sus respuestas en voz alta.",
  "accueil.mon_espace": "Mi espacio",
  "accueil.note_sur_la_coherence_du_projet_et_la_culture_genera": "Evaluado por la coherencia del proyecto y la cultura general.",
  "accueil.note_sur_la_prise_de_recul_et_le_lien_au_projet_d_or": "Evaluado por la perspectiva y la relación con tu proyecto formativo.",
  "accueil.note_sur_les_preuves_chiffrees_et_la_concision": "Evaluado por las pruebas concretas y la concisión.",
  "accueil.paiement_securise_stripe": "Pago seguro con Stripe",
  "accueil.parler_au_coach_ia": "Hablar con el coach IA",
  "accueil.pitch": "Pitch",
  "accueil.plus_tard": "Más tarde",
  "accueil.pose_dans_la_langue_de_l_epreuve_note_selon_le_cecrl": "Planteado en la lengua de la prueba, evaluado según el MCER.",
  "accueil.pourquoi_preporal": "¿Por qué Oralixia?",
  "accueil.preporal_premium": "Oralixia Premium",
  "accueil.preporal_s_adresse_aussi_a_des_collegiens_et_lyceens": "Oralixia también se dirige a estudiantes de secundaria. La ley francesa establece reglas distintas según la edad: pedimos un tramo, nunca tu fecha de nacimiento.",
  "accueil.preuves_et_chiffres": "Pruebas y cifras",
  "accueil.produit": "Producto",
  "accueil.progression_de_vos_notes_de_la_plus_ancienne_a_la_pl": "Evolución de tus notas, de la más antigua a la más reciente.",
  "accueil.qu_est_ce_qui_dans_votre_dossier_pourrait_faire_hesi": "«¿Qué podría hacer dudar al tribunal en su expediente?»",
  "accueil.quel_age_avez_vous": "¿Qué edad tienes?",
  "accueil.quelle_est_la_taille_de_votre_marche_et_comment_l_av": "«¿Qué tamaño tiene su mercado y cómo lo ha estimado?»",
  "accueil.quelqu_un_vous_soutient_exactement_l_inverse_de_votr": "«Alguien defiende justo lo contrario de su conclusión. ¿Qué le responde?»",
  "accueil.question_3_5_mise_en_situation": "Pregunta 3 / 5 · Caso práctico",
  "accueil.questions_courtes_concretes_orientees_objection": "Preguntas breves, concretas, orientadas a la objeción.",
  "accueil.refuser": "Rechazar",
  "accueil.relecture": "Revisión",
  "accueil.repeter_devant_quelqu_un_coute_cher_gene_et_n_est_pa": "Ensayar delante de alguien cuesta dinero, incomoda y no se puede repetir diez veces. Oralixia hace lo contrario: el examinador plantea sus preguntas en voz alta, no se cansa nunca y te dice con franqueza qué no funciona.",
  "accueil.resiliable_en_un_clic": "Cancelable en un clic",
  "accueil.retours_de_candidats_apres_leur_oral_verifies_avant_": "Opiniones de candidatos tras su oral, verificadas antes de publicarse.",
  "accueil.sans_engagement_depuis_le_portail_client_stripe": "Sin compromiso, desde el portal de cliente de Stripe.",
  "accueil.se_deconnecter": "Cerrar sesión",
  "accueil.simulateur": "Simulador",
  "accueil.simulateur_d_oral": "Simulador de examen oral",
  "accueil.simulation_passee": "Simulación anterior",
  "accueil.simulations_illimitees_rapports_detailles_et_coach_i": "Simulaciones ilimitadas, informes detallados y coach IA sin límite.",
  "accueil.simulations_offertes_sans_carte": "simulaciones completas gratis al crear tu cuenta, sin tarjeta",
  "accueil.some_people_say_studying_abroad_is_essential_do_you_": "«Some people say studying abroad is essential. Do you agree? Give reasons and examples.»",
  "accueil.structure_de_la_reponse": "Estructura de la respuesta",
  "accueil.temoignages": "Testimonios",
  "accueil.tes_documents_restent_a_toi": "Tus documentos siguen siendo tuyos",
  "accueil.tout_effacer": "Borrar todo",
  "accueil.types_d_oraux_couverts_entretien_grand_oral_brevet_c": "tipos de oral cubiertos: entrevista, Grand Oral, brevet, oposiciones, pitch, oral de asignatura",
  "accueil.un_entrainement_pas_une_garantie_de_reussite_c_est_e": "Un entrenamiento, no una garantía de éxito. Así consta en las condiciones de venta.",
  "accueil.un_jury_de_brevet_et_un_jury_de_grande_ecole_n_atten": "Un tribunal de brevet y uno de escuela superior no esperan lo mismo. El examinador cambia de actitud, de vocabulario y de criterios según la prueba.",
  "accueil.vocabulaire_adapte_a_l_age_bienveillant_mais_exigean": "Vocabulario adaptado a la edad, cercano pero exigente.",
  "accueil.voir_les_offres": "Ver los planes",
  "accueil.vos_2_simulations_gratuites_sont_utilisees": "Has agotado tus 2 simulaciones gratuitas",
  "accueil.votre_premiere_semaine_porte_sur_un_dossier_que_vous": "«Su primera semana trata de un expediente que no conoce. ¿Por dónde empieza?»",
  "accueil.votre_profil_manque_d_experience_sur_ce_perimetre_po": "«Su perfil carece de experiencia en este ámbito. ¿Por qué usted y no un candidato con experiencia?»",
  "accueil.vous_n_etes_pas_connecte": "No has iniciado sesión.",
  "age.15_17": "Entre 15 y 17 años",
  "age.consentement_envoye": "Gracias. Enviaremos un mensaje a tu representante legal para confirmar su consentimiento.",
  "age.email_parent_requis": "Indica el correo electrónico de tu padre, madre o representante legal.",
  "age.majeur": "18 años o más",
  "age.moins_15": "Menos de 15 años",
  "age.paiement_mineur": "Has declarado tener menos de {n} años: el pago debe realizarlo tu representante legal, o contar con su consentimiento expreso.",
  "appel.appeler_le_coach": "Llamar al coach",
  "appel.connexion": "Conectando…",
  "appel.ecoute": "Te escucho…",
  "appel.erreur": "No he podido responder. ¿Lo intentamos otra vez?",
  "appel.fin_oral": "Gracias, la entrevista ha terminado. Preparo tu corrección.",
  "appel.indisponible": "La llamada necesita reconocimiento de voz, que este navegador no tiene. Safari, Chrome y Edge sí.",
  "appel.ouverture_coach": "Hola, soy tu coach. Dime en qué examen oral estás trabajando.",
  "appel.parole": "Respondiendo…",
  "appel.passer_a_l_oral": "Hacer toda la entrevista en voz alta",
  "appel.raccrocher": "Colgar",
  "appel.reflexion": "Un momento…",
  "appel.sous_titre_coach": "Habla con naturalidad. Haz una pausa para que responda.",
  "appel.sous_titre_oral": "Responde en voz alta. Haz una pausa y el tribunal continúa.",
  "appel.termine": "Llamada terminada.",
  "appel.titre_coach": "Llamada con el coach",
  "appel.titre_oral": "Entrevista oral",
  "auth.adresse_email": "Correo electrónico",
  "auth.afficher_mot_de_passe": "Mostrar la contraseña",
  "auth.avantage_appareils": "Recuperar tu acceso en cualquier dispositivo",
  "auth.avantage_deux_simulations": "2 simulaciones gratuitas, desde que te registras",
  "auth.avantage_progression": "Seguir tu curva de progreso",
  "auth.avantage_relire": "Releer tus correcciones cuando quieras",
  "auth.bienvenue": "Ya estás dentro.",
  "auth.compte_cree": "Cuenta creada. Tus dos simulaciones gratuitas te esperan.",
  "auth.confirmation_differente": "Las dos contraseñas no coinciden.",
  "auth.confirmer_mot_de_passe": "Confirmar contraseña",
  "auth.confirmez_boite_mail": "Cuenta creada. Abre tu correo y pulsa el enlace para activarla. Mira también en la carpeta de spam.",
  "auth.connexion_en_cours": "Iniciando sesión…",
  "auth.continuer_google": "Continuar con Google",
  "auth.creation_en_cours": "Creando la cuenta…",
  "auth.creer_mon_compte": "Crear mi cuenta",
  "auth.deconnecte": "Has cerrado sesión.",
  "auth.deja_inscrit": "Esta dirección ya tiene una cuenta. Inicia sesión o usa «¿Olvidaste tu contraseña?».",
  "auth.email_au_dessus": "Escribe arriba tu correo electrónico.",
  "auth.email_invalide": "Escribe un correo electrónico válido.",
  "auth.en_continuant": "Al continuar, aceptas las",
  "auth.err.deja_inscrit": "Ya existe una cuenta con esta dirección. Inicia sesión en su lugar.",
  "auth.err.generique": "Se ha producido un error.",
  "auth.err.identifiants": "Correo o contraseña incorrectos.",
  "auth.err.mdp_court": "La contraseña debe tener al menos 8 caracteres.",
  "auth.err.non_confirme": "Confirma primero tu dirección: el enlace está en tu buzón.",
  "auth.et_la": "y la",
  "auth.exemple_email": "tu@ejemplo.com",
  "auth.exemple_nom": "Dupont",
  "auth.exemple_prenom": "Camille",
  "auth.facultatif": "(opcional)",
  "auth.force_bon": "Buena contraseña.",
  "auth.force_court": "Demasiado corta: ocho caracteres como mínimo.",
  "auth.force_moyen": "Correcta. Un número y una mayúscula la harían más sólida.",
  "auth.google_inactif": "El acceso con Google aún no está activado en este sitio. Usa tu correo y tu contraseña, o el enlace sin contraseña.",
  "auth.huit_caracteres": "8 caracteres como mínimo",
  "auth.indispo": "No disponible: Supabase no está configurado.",
  "auth.inscription": "Registrarse",
  "auth.inscription_indispo": "Registro no disponible: Supabase no está configurado.",
  "auth.lien_envoye": "Enlace enviado. Abre tu correo para iniciar sesión.",
  "auth.lien_sans_mot_de_passe": "Enviarme un enlace, sin contraseña",
  "auth.masquer_mot_de_passe": "Ocultar la contraseña",
  "auth.mdp_envoye": "Mensaje enviado: sigue el enlace para elegir una contraseña nueva.",
  "auth.mdp_requis": "Escribe tu contraseña.",
  "auth.mot_de_passe": "Contraseña",
  "auth.mot_de_passe_oublie": "¿Olvidaste tu contraseña?",
  "auth.nom": "Apellidos",
  "auth.ou": "o",
  "auth.politique_confidentialite": "política de privacidad",
  "auth.prenom": "Nombre",
  "auth.prenom_requis": "Indica tu nombre.",
  "auth.pseudonyme": "Apodo",
  "auth.pseudonyme_aide": "Se muestra arriba en lugar de tu correo. Sin apodo, aparecerá «Nombre A.».",
  "auth.pseudonyme_exemple": "Cam",
  "auth.raison_simulation": "Crea tu cuenta gratuita para lanzar la simulación: tus dos simulaciones de regalo van asociadas a ella.",
  "auth.se_connecter": "Iniciar sesión",
  "auth.supabase_absent": "Inicio de sesión no disponible: Supabase no está configurado.",
  "auth.volet_intro": "Dos simulaciones completas de regalo al crear la cuenta. Sin tarjeta.",
  "avis.aucun_detail": "Esta página solo muestra opiniones reales de personas que han hecho una simulación, verificadas antes de publicarse. Preferimos una página vacía a testimonios inventados, que además son ilegales.",
  "avis.aucun_pour_epreuve": "Todavía no hay opiniones para esta prueba.",
  "avis.aucun_titre": "Aún no hay testimonios publicados.",
  "avis.collectes_depuis": ", recogidas desde {date}",
  "avis.deposer_premier": "Deja la primera opinión",
  "avis.depuis": "desde {date}",
  "avis.en_attente": "Pendiente de verificación",
  "avis.epreuve_facultative": "Prueba preparada (opcional)",
  "avis.etoile": "{n} estrella",
  "avis.etoiles": "{n} estrellas",
  "avis.merci_local": "¡Gracias! Tu opinión se ha guardado en este dispositivo; se publicará tras la verificación.",
  "avis.merci_serveur": "¡Gracias! Tu opinión se publicará tras la verificación.",
  "avis.nom_requis": "Indica al menos tu nombre.",
  "avis.note_sur_5": "{n} sobre 5",
  "avis.statut_defaut": "Usuario de Oralixia",
  "avis.sur_n_verifie": "sobre {n} opinión verificada",
  "avis.sur_n_verifies": "sobre {n} opiniones verificadas",
  "avis.toutes_epreuves": "Todas las pruebas",
  "avis.trop_court": "Tu opinión es un poco corta, ¿unas palabras más?",
  "avis.verifie": "{n} opinión verificada",
  "avis.verifies": "{n} opiniones verificadas",
  "avis.vide_lien": "La tuya puede ser la primera.",
  "avis.vide_texte": "Las opiniones que se muestran aquí serán de personas reales que hicieron una simulación, verificadas antes de publicarse. ¿Acabas de hacer un oral?",
  "avis.vide_titre": "Aún no hay opiniones publicadas.",
  "bilan.chiffres.non": "Añade un dato preciso: una duración, un volumen, una fecha, una cifra.",
  "bilan.chiffres.oui": "Apoyas lo que dices en cifras o en fechas.",
  "bilan.debit.bon": "Ritmo de {n} palabras por minuto: es el de un oral controlado, mantenlo.",
  "bilan.debit.lent": "Hablas a {n} palabras por minuto: algo lento, lo que da sensación de duda. Encadena tus ideas sin buscar la palabra perfecta.",
  "bilan.debit.non_mesure": "Responde con el micrófono en vez de escribir: así Oralixia puede medir tu ritmo y tus silencios.",
  "bilan.debit.rapide": "Hablas a {n} palabras por minuto: es rápido. Respira después de cada idea, el tribunal necesita seguirte.",
  "bilan.je.non": "Di «hice», no «hicimos»: el tribunal te evalúa a ti.",
  "bilan.je.oui": "Asumes tu papel en primera persona.",
  "bilan.long.bien": "Respuesta lo bastante desarrollada para convencer.",
  "bilan.long.correct": "Longitud correcta; un ejemplo más la haría imbatible.",
  "bilan.long.court": "Demasiado corta: apunta a entre 45 y 120 segundos, unas 100 a 250 palabras.",
  "bilan.phrases_longues": "Tus frases tienen {n} palabras de media. Pártelas en dos: una idea, una frase.",
  "bilan.plan": "Anuncia tu esquema en voz alta («primero… luego… por último»): el tribunal puntúa lo que consigue seguir.",
  "bilan.plan.non": "Anuncia dos o tres puntos al empezar: el tribunal te sigue mejor.",
  "bilan.plan.oui": "El esquema de la respuesta se oye con claridad.",
  "bilan.preuve.non": "Termina con lo que produjo, no solo con lo que hiciste.",
  "bilan.preuve.oui": "El razonamiento llega hasta el resultado o el ejemplo.",
  "bilan.reecriture": "Empieza así: «{debut}…», sigue con un ejemplo fechado y con cifras, y cierra en una frase sobre el resultado.",
  "bilan.sans_reponse": "Pregunta sin responder: retómala en voz alta, aunque sea de forma imperfecta.",
  "bilan.tics.aucun": "Ninguna muletilla destacable: tu discurso es limpio.",
  "bilan.tics.reperes": "Muletillas detectadas: {liste}. Sustitúyelas por un silencio de un segundo, que se percibe como seguridad.",
  "bilan.tics.supprimer": "Muletillas que hay que eliminar: {liste}.",
  "bilan.vocabulaire": "Vocabulario repetitivo: prepara cinco términos precisos del ámbito y colócalos a propósito.",
  "chargement.correction.conseil.0": "La corrección es franca: eso es lo que la hace útil.",
  "chargement.correction.conseil.1": "Retoma primero la pregunta peor puntuada, no la primera.",
  "chargement.correction.conseil.2": "Lanzar otra simulación justo después de leer el balance es el mejor momento para progresar.",
  "chargement.correction.conseil.3": "Una respuesta demasiado larga cuesta más puntos que una demasiado corta.",
  "chargement.correction.etape.0": "Releyendo tus respuestas",
  "chargement.correction.etape.1": "Evaluando el contenido, respuesta por respuesta",
  "chargement.correction.etape.2": "Midiendo tu ritmo y tu riqueza de vocabulario",
  "chargement.correction.etape.3": "Redactando tus puntos de mejora",
  "chargement.correction.titre": "Analizando tu intervención",
  "chargement.questions.conseil.0": "Respira antes de responder. Dos segundos de silencio valen más que tres de «eh».",
  "chargement.questions.conseil.1": "Una buena respuesta tiene tres tiempos: la situación, lo que hiciste, el resultado.",
  "chargement.questions.conseil.2": "El tribunal recuerda tu primera y tu última frase. Cuídalas.",
  "chargement.questions.conseil.3": "Una cifra concreta vale más que tres adjetivos.",
  "chargement.questions.conseil.4": "Si una pregunta te sorprende, reformúlala: ganas cinco segundos para pensar.",
  "chargement.questions.etape.0": "Leyendo tus documentos",
  "chargement.questions.etape.1": "Detectando los puntos que el tribunal va a explorar",
  "chargement.questions.etape.2": "Redactando las preguntas del examinador",
  "chargement.questions.etape.3": "Ordenando el desarrollo",
  "chargement.questions.titre": "Preparando tu oral",
  "coach.accueil": "Hola, soy tu coach de Oralixia. Dime qué oral estás preparando, o pega tu guion, tu texto o tu tema: te ayudo a estructurarlo, reformularlo y anticipar las preguntas del tribunal.",
  "coach.analyse_piece": "¿Puedes analizar este documento y decirme qué debería trabajar?",
  "coach.appuyez_micro": "Pulsa el micrófono para hablar con tu coach.",
  "coach.dernier_echange": "Último intercambio gratuito del día.",
  "coach.dictee_absente": "El dictado por voz no está disponible en este navegador (prueba con Chrome, Edge o Safari).",
  "coach.documents_joints": "Documentos adjuntos",
  "coach.echange_restant": "{n} intercambio gratuito hoy",
  "coach.echanges_restants": "{n} intercambios gratuitos hoy",
  "coach.je_vous_ecoute": "Te escucho…",
  "coach.joindre": "Adjuntar un documento",
  "coach.lecture_activee": "Lectura en voz alta: activada",
  "coach.lecture_coupee": "Lectura en voz alta: desactivada",
  "coach.lecture_piece": "Leyendo {nom}…",
  "coach.limite_atteinte": "Has usado tus intercambios de hoy con el coach.",
  "coach.parler": "Hablar",
  "coach.piece_echec": "No se ha podido leer este archivo.",
  "coach.piece_refusee": "No se ha podido enviar este documento.",
  "coach.piece_trop_lourde": "Archivo demasiado pesado: 3 MB como máximo.",
  "coach.piece_vide": "No hay texto aprovechable en este archivo.",
  "coach.placeholder_saisie": "Haz tu pregunta o pega el texto de tu oral…",
  "coach.preparation": "Preparando…",
  "coach.raison_compte": "Crea tu cuenta gratuita para hablar con el coach: unos cuantos intercambios al día van de regalo.",
  "coach.repli": "No se puede contactar con el coach ahora mismo (la API no está configurada o se ha cortado la red). Mientras tanto, un método que casi siempre funciona: una frase de entrada, tres ideas anunciadas, un ejemplo fechado y con cifras por idea, y una conclusión que responda a la pregunta.",
  "coach.retirer_piece": "Quitar",
  "coach.simulation_confiee": "Esta es mi simulación del {date}. ¿Qué debería trabajar primero?",
  "coach.trop_de_pieces": "Cinco archivos adjuntos como máximo.",
  "compte.abonnement": "Suscripción",
  "compte.abonnement_actif": "Suscripción activa. ¡Gracias!",
  "compte.actif_jusquau": "Activo hasta el {date}",
  "compte.aucun_abonnement": "Sin suscripción activa. Tus simulaciones de regalo siguen disponibles.",
  "compte.changer_adresse": "Cambiar de correo",
  "compte.changer_mot_de_passe": "Cambiar la contraseña",
  "compte.choisir_photo": "Elegir una foto",
  "compte.connexion": "Correo y contraseña",
  "compte.couleur_pastille": "Color de la chapa",
  "compte.delai": "El servidor no ha respondido. Inténtalo de nuevo.",
  "compte.echec": "No se ha podido guardar.",
  "compte.email_aide": "Cambiar de correo requiere confirmación: sale un enlace al antiguo y al nuevo.",
  "compte.email_confirmation": "Sale un enlace de confirmación al correo antiguo y al nuevo. El cambio surte efecto cuando ambos se confirmen.",
  "compte.email_identique": "Escribe una dirección nueva.",
  "compte.enregistre": "Guardado.",
  "compte.enregistrement": "Guardando…",
  "compte.enregistrer": "Guardar",
  "compte.envoi_photo": "Enviando la foto…",
  "compte.gerer_abonnement": "Cancelar o cambiar de plan",
  "compte.gerer_mon_compte": "Gestionar mi cuenta",
  "compte.hors_ligne": "No se puede guardar: no has iniciado sesión.",
  "compte.identite_aide": "Una foto sustituye a la silueta. Sin foto, elige el tono de tu chapa.",
  "compte.identite_visuelle": "Foto y color",
  "compte.intro": "Tu identidad, tu suscripción y tus métodos de pago. Nada de esto lo ven los demás candidatos.",
  "compte.intro_anonyme": "Tus datos, tu suscripción y tus simulaciones gratuitas te esperan detrás de tu cuenta.",
  "compte.mdp_envoye": "Mensaje enviado: sigue el enlace para elegir una contraseña nueva.",
  "compte.mes_informations": "Mis datos",
  "compte.mes_simulations": "Mis simulaciones",
  "compte.mode_local": "Modo local: tu historial se guarda solo en este navegador. Añade tus claves de Supabase para sincronizar tus dispositivos.",
  "compte.mode_local_titre": "Las cuentas no están disponibles en modo local",
  "compte.mon_abonnement": "Mi suscripción",
  "compte.mon_compte": "Mi cuenta",
  "compte.moyens_de_paiement": "Métodos de pago",
  "compte.offre_gratuite": "Plan gratuito",
  "compte.ouvrir_portail": "Gestionar mis métodos de pago",
  "compte.paiement_aide": "Tus datos bancarios nunca pasan por Oralixia ni se guardan aquí: los gestiona Stripe en sus propias páginas.",
  "compte.photo_echec": "No se ha podido enviar la foto.",
  "compte.photo_enregistree": "Foto guardada.",
  "compte.photo_retiree": "Foto quitada.",
  "compte.photo_trop_lourde": "Foto demasiado pesada: 2 MB como máximo.",
  "compte.photo_url": "No se ha encontrado la URL de la foto.",
  "compte.premium_actif": "Premium activo",
  "compte.pseudo_aide": "Se muestra arriba. Sin apodo aparecerá",
  "compte.reconduction": "Se renueva automáticamente. Cancelable en cualquier momento.",
  "compte.resiliation_aide": "Una cancelación surte efecto al final del periodo ya pagado: conservas el acceso hasta entonces.",
  "compte.retirer_photo": "Quitar la foto",
  "compte.simulations_restantes": "simulaciones de regalo restantes de {total}",
  "compte.suppression_corps": "Hola:\n\nSolicito la eliminación de mi cuenta de Oralixia.\n\nDirección de la cuenta: {email}\n\nGracias.",
  "compte.suppression_objet": "Eliminación de mi cuenta de Oralixia",
  "compte.suppression_sans_contact": "Este sitio aún no tiene dirección de contacto. Escribe al editor para pedir la eliminación.",
  "compte.supprimer_aide": "Borra definitivamente tu perfil, tus simulaciones pasadas y tu contador de uso. Una suscripción activa debe cancelarse antes, desde el portal de pago.",
  "compte.supprimer_bouton": "Solicitar la eliminación",
  "compte.supprimer_confirmation": "¿Eliminar definitivamente tu cuenta, tus simulaciones pasadas y tu contador de uso? No tiene vuelta atrás.",
  "compte.supprimer_titre": "Eliminar mi cuenta",
  "compte.titre_anonyme": "Inicia sesión para gestionar tu cuenta",
  "cookies.texte": "Solo usamos cookies necesarias para que el sitio funcione (sesión, preferencias). Ninguna cookie publicitaria, ningún rastreador de terceros.",
  "cta.lancer_simulation": "Empezar mi simulación",
  "cta.mes_simulations": "Ver mis simulaciones anteriores",
  "cta.premiere_simulation": "Empezar mi primera simulación",
  "cta.tous_temoignages": "Ver todos los testimonios",
  "demo.conseil": "<span class=\"font-medium text-iris2\">Consejo ·</span> Haz una pausa real después de cada idea. Tu ritmo baja solo y el tribunal retiene más.",
  "demo.debit": "palabras / min<br>Demasiado rápido",
  "demo.phrases": "palabras / frase<br>Acórtalas",
  "demo.richesse": "riqueza<br>Vocabulario variado",
  "ecoute.arreter": "Detener",
  "ecoute.bilan": "Escuchar el informe",
  "ecoute.ecouter": "Escuchar",
  "hist.aucune": "Todav\u00eda no hay ninguna simulaci\u00f3n. Lanza una y aparecer\u00e1 aqu\u00ed con su nota y su correcci\u00f3n.",
  "hist.a": "a las",
  "hist.courbe_a11y": "Curva de evolución de las notas",
  "hist.courbe_attente": "Haz una segunda simulación y aquí aparecerá tu curva de evolución.",
  "hist.eloquence": "elocuencia",
  "hist.non_conserve": "Detalle no conservado",
  "hist.progression": "Evolución en {n} simulaciones",
  "hist.question": "pregunta",
  "hist.questions": "preguntas",
  "hist.relire": "Releer las preguntas y la corrección →",
  "hist.vide": "Historial borrado.",
  "hist.vider_confirmer": "¿Borrar definitivamente todas tus simulaciones guardadas?",
  "import.doc_ancien": "El formato .doc antiguo no se puede leer: guarda el archivo en .docx o en PDF.",
  "import.echec": "No se ha podido importar.",
  "import.format": "Formato no admitido.",
  "import.importe": "{n} caracteres importados",
  "import.lecture": "Leyendo {f}…",
  "import.lib_injoignable": "Biblioteca de lectura inaccesible.",
  "import.ocr": "PDF escaneado detectado, aplicando reconocimiento óptico…",
  "import.ok": "Documento importado. Revísalo y corrígelo si hace falta.",
  "import.page": "Leyendo la página {p}/{n}…",
  "import.vide": "No se ha encontrado texto utilizable en este archivo.",
  "legal.alerte.completer": "Completa el bloque <code>window.ORALIXIA_ENV</code> en <code>index.html</code>.",
  "legal.alerte.manquantes": "Faltan las siguientes menciones legales obligatorias:",
  "legal.alerte.sanctions": "Vender sin estas menciones expone a sanciones (art. L111-1 y ss. del Código de Consumo francés).",
  "legal.alerte.titre": "Configuración incompleta: no poner a la venta en este estado.",
  "legal.cgv": "Condiciones de venta",
  "legal.cgv.1": "1. Objeto",
  "legal.cgv.1_corps": "Las presentes condiciones regulan la venta de las suscripciones y accesos de pago a Oralixia, servicio de entrenamiento para pruebas orales editado por {n}.",
  "legal.cgv.2": "2. Ofertas y precios",
  "legal.cgv.2_extra": "{nom}: {prix} IVA incluido por seis meses de acceso completo, precedidos de {jours} días de prueba gratuita. La suscripción se <strong>renueva automáticamente cada seis meses</strong> hasta su cancelación; no se cobra nada durante la prueba.",
  "legal.cgv.2_gratuit": "Oferta gratuita: {n} simulaciones completas al crear la cuenta, sin tarjeta bancaria.",
  "legal.cgv.2_mensuel": "{nom}: {prix} IVA incluido al mes, sin compromiso, renovado automáticamente cada mes hasta su cancelación.",
  "legal.cgv.2_pass48": "{nom}: {prix} IVA incluido, acceso completo durante 48 horas desde el pago. Pago único, sin renovación.",
  "legal.cgv.2_prix": "Los precios se indican con todos los impuestos incluidos, en euros. {n} puede modificarlos en cualquier momento; se aplica la tarifa mostrada en el momento del pedido.",
  "legal.cgv.3": "3. Pedido y pago",
  "legal.cgv.3_corps": "El pago se efectúa en línea mediante Stripe (tarjeta bancaria y medios ofrecidos por Stripe). El pedido se valida tras la confirmación del pago. La factura está disponible en el área de cliente.",
  "legal.cgv.4": "4. Cancelación y renovación",
  "legal.cgv.4_essai": "Cancelar durante los {jours} días de prueba de la oferta {nom} no conlleva ningún cobro.",
  "legal.cgv.4_l215": "De conformidad con el artículo L215-1 del Código de Consumo francés, {n} informa al abonado de su facultad de no renovar su suscripción semestral, como muy pronto tres meses y como muy tarde un mes antes del vencimiento. A falta de esta información, el abonado puede poner fin gratuitamente al contrato en cualquier momento a partir de la fecha de renovación y obtener el reembolso de las cantidades cobradas después de ella.",
  "legal.cgv.4_pass48": "El Pase de 48 horas es un pago único: no se renueva y no hay que cancelarlo. Al vencer, el acceso vuelve a la oferta gratuita.",
  "legal.cgv.4_resilier": "Las suscripciones {m} y {e} pueden cancelarse en cualquier momento desde «Gestionar mi cuenta», que abre el portal de cliente de Stripe. La cancelación surte efecto al final del periodo ya pagado: el acceso se conserva hasta entonces y no se reembolsa ningún prorrateo. El portal también permite cambiar de fórmula.",
  "legal.cgv.5": "5. Derecho de desistimiento",
  "legal.cgv.5_delai": "De conformidad con los artículos L221-18 y siguientes del Código de Consumo francés, el consumidor dispone de 14 días para desistir.",
  "legal.cgv.5_renonciation": "Al suscribirte, solicitas expresamente la ejecución inmediata del servicio y reconoces perder tu derecho de desistimiento una vez que el servicio se haya ejecutado por completo (art. L221-28 13°). En la suscripción mensual, el desistimiento sigue siendo posible mientras no se haya lanzado ninguna simulación de pago.",
  "legal.cgv.6": "6. Disponibilidad",
  "legal.cgv.6_corps": "El servicio se presta «tal cual». {n} aplica los medios razonables para asegurar su disponibilidad, pero no garantiza una continuidad absoluta (mantenimiento, incidente de un proveedor externo, indisponibilidad del proveedor del modelo de IA).",
  "legal.cgv.7": "7. Responsabilidad",
  "legal.cgv.7_corps": "Oralixia es una herramienta de entrenamiento. No se asume ninguna obligación de resultado en cuanto al éxito en un examen, una oposición o un proceso de selección.",
  "legal.cgv.8": "8. Suscripción por un menor",
  "legal.cgv.8_annulation": "{n} puede pedir una confirmación en cualquier momento y anular, sin gastos, una suscripción contratada por un menor sin ese consentimiento.",
  "legal.cgv.8_gratuit": "El uso gratuito del servicio sigue abierto. Para los menores de 15 años, crear una cuenta requiere el consentimiento del titular de la patria potestad (art. 45 de la Ley francesa de Protección de Datos).",
  "legal.cgv.8_principe": "El servicio se dirige en particular a alumnos de secundaria y bachillerato. De conformidad con los artículos 1145 y siguientes del Código Civil francés, un menor no emancipado no puede contratar solo una suscripción de pago: debe contratarla el titular de la patria potestad o hacerse con su consentimiento expreso.",
  "legal.cgv.9": "9. Derecho aplicable",
  "legal.cgv.9_corps": "Derecho francés. A falta de acuerdo amistoso, son competentes los tribunales franceses.",
  "legal.cgv.titre": "Condiciones generales de venta",
  "legal.confidentialite": "Privacidad (RGPD)",
  "legal.cookies": "Cookies",
  "legal.cookies.aucun_avant": "Oralixia no utiliza",
  "legal.cookies.aucun_gras": "ninguna cookie publicitaria ni rastreador de marketing",
  "legal.cookies.necessaires": "Cookies estrictamente necesarias: sesión de autenticación (Supabase) y seguridad del pago (Stripe). No requieren consentimiento previo.",
  "legal.cookies.stockage": "Almacenamiento local del navegador: contador de simulaciones gratuitas, historial de tus notas, opiniones enviadas, preferencias de visualización. Esta información permanece en tu dispositivo; puedes borrarla desde «Mi espacio» o vaciando los datos del sitio.",
  "legal.cookies.titre": "Cookies y almacenamiento local",
  "legal.cookies.utilisons": "Lo que utilizamos",
  "legal.mentions": "Aviso legal",
  "legal.mentions.contact": "Contacto",
  "legal.mentions.directeur": "Director de la publicación",
  "legal.mentions.editeur": "Editor del sitio",
  "legal.mentions.hebergement": "Alojamiento",
  "legal.mentions.limites": "Límites del servicio",
  "legal.mentions.limites_corps": "Oralixia es una herramienta de entrenamiento asistida por inteligencia artificial. Las preguntas, notas y consejos se generan automáticamente, pueden contener errores y no constituyen ni una evaluación oficial ni una garantía de éxito en un examen, una oposición o una entrevista.",
  "legal.mentions.mediation": "Mediación de consumo",
  "legal.mentions.mediation_corps": "En caso de litigio no resuelto, el consumidor puede acudir gratuitamente a un mediador de consumo: {m}. Plataforma europea de resolución de litigios en línea: ec.europa.eu/consumers/odr.",
  "legal.mentions.paiement": "Pago",
  "legal.mentions.paiement_corps": "Los pagos los gestiona {p}. Ningún dato de tarjeta bancaria transita ni se almacena en los servidores de Oralixia.",
  "legal.mentions.pi": "Propiedad intelectual",
  "legal.mentions.pi_corps": "Todos los elementos del sitio (marca, logotipo, interfaz, textos, código) están protegidos. Queda prohibida cualquier reproducción sin autorización escrita. Los contenidos que subes siguen siendo tuyos.",
  "legal.mentions.siege": "Domicilio social",
  "legal.mentions.titre": "Aviso legal",
  "legal.mentions.tva": "IVA",
  "legal.rgpd.documents": "Tus documentos",
  "legal.rgpd.documents_corps": "Los archivos que subes se leen directamente en tu navegador: nunca se cargan en nuestros servidores.",
  "legal.rgpd.documents_gras": "Tus CV, temas, apuntes y respuestas no se conservan.",
  "legal.rgpd.documents_ia": "El texto extraído se transmite al proveedor del modelo de IA el tiempo necesario para generar las preguntas y la corrección, y después no se almacena del lado de Oralixia. Estos contenidos no se venden, ni se ceden, ni se usan para entrenar un modelo.",
  "legal.rgpd.donnees": "Datos tratados",
  "legal.rgpd.donnees_abo": "Suscripción: identificador de cliente de Stripe, estado y vencimiento (ejecución del contrato y obligación contable).",
  "legal.rgpd.donnees_audio": "Audio: el reconocimiento de voz usa la API de tu navegador. Según el navegador, el audio puede ser tratado por su editor (Google, Apple, Microsoft). Oralixia no recibe ni almacena ninguna grabación.",
  "legal.rgpd.donnees_compte": "Cuenta: dirección de correo electrónico, identificador, fecha de creación (base jurídica: ejecución del contrato).",
  "legal.rgpd.donnees_historique": "Historial: tipo de oral, fecha, nota global y notas por criterio, para mostrar tu evolución (ejecución del contrato). El contenido de tus respuestas no se guarda en el servidor.",
  "legal.rgpd.droits": "Tus derechos",
  "legal.rgpd.droits_corps": "Acceso, rectificación, supresión, limitación, oposición y portabilidad: escribe a {email}. También puedes presentar una reclamación ante la CNIL (cnil.fr).",
  "legal.rgpd.durees": "Plazos de conservación",
  "legal.rgpd.durees_corps": "Cuenta e historial: hasta la eliminación de la cuenta, y después 30 días. Documentos contables: 10 años (obligación legal). Datos de navegación: 13 meses como máximo.",
  "legal.rgpd.mineurs": "Menores",
  "legal.rgpd.mineurs_corps": "El servicio se dirige en particular a alumnos de secundaria y bachillerato. Para los menores de 15 años, crear una cuenta requiere el consentimiento del titular de la patria potestad.",
  "legal.rgpd.responsable": "Responsable del tratamiento",
  "legal.rgpd.soustraitants": "Encargados del tratamiento",
  "legal.rgpd.soustraitants_corps": "Vercel (alojamiento), Supabase (base de datos y autenticación, región UE), Stripe (pago) y el proveedor del modelo de IA para generar las preguntas y las correcciones. Algunas transferencias fuera de la UE están amparadas por las cláusulas contractuales tipo de la Comisión Europea.",
  "legal.rgpd.titre": "Política de privacidad (RGPD)",
  "legal.version_fr_fait_foi": "Traducción facilitada a título informativo. Solo la versión francesa da fe: el contrato se rige por el derecho francés.",
  "lien.desactive": "El acceso por enlace está desactivado en este proyecto.",
  "lien.expire": "Este enlace ha caducado o ya se ha usado. Un enlace de acceso solo funciona una vez. Pide uno nuevo o inicia sesión con tu contraseña.",
  "lien.incomplet": "El enlace recibido está incompleto. Pide uno nuevo.",
  "lien.invalide": "Este enlace no es válido. Pide uno nuevo.",
  "lien.refuse": "Este enlace ya no es válido. Pide uno nuevo o inicia sesión con tu contraseña.",
  "lien.serveur": "El servicio de autenticación no ha respondido. Inténtalo de nuevo en un momento.",
  "lu.eloquence": "Consejos de elocuencia.",
  "lu.note_globale": "Tu nota global es {n} sobre 100.",
  "lu.note_sur_20": "Nota: {n} sobre 20.",
  "lu.par_critere": "Detalle por criterio.",
  "lu.sur_100": "{nom}: {val} sobre 100.",
  "micro.absent": "No se ha detectado ningún micrófono en este dispositivo.",
  "micro.interrompue": "El dictado se ha interrumpido.",
  "micro.refuse": "Micrófono denegado. Autoriza el acceso al micrófono en tu navegador.",
  "micro.refuse_systeme": "Micrófono denegado por el sistema.",
  "micro.reseau": "El reconocimiento de voz no ha podido conectarse a la red.",
  "micro.rien_entendu": "No se ha detectado ninguna voz.",
  "offre.equivalent": "{m} al mes · {e} menos que seis meses a la tarifa mensual",
  "offre.essai": "{n} días gratis",
  "offre.extra.accroche": "Todo un curso escolar",
  "offre.extra.detail": "Seis meses de acceso completo y coach de IA sin límite. Una semana gratis y luego renovación cada seis meses, cancelable cuando quieras.",
  "offre.mensuel.accroche": "El más flexible",
  "offre.mensuel.detail": "Simulaciones ilimitadas, informes completos, coach de IA sin límite. Sin compromiso, cancelable con un clic.",
  "offre.pass48.accroche": "La víspera de un oral",
  "offre.pass48.detail": "Acceso completo durante 48 horas. Pago único, sin renovación.",
  "offre.periode.par_mois": "al mes",
  "offre.periode.pour_6_mois": "por 6 meses",
  "offre.periode.une_fois": "pago único",
  "offre.recommande": "Recomendado",
  "page.titre.accueil": "Oralixia — Aprueba tu oral a la primera",
  "page.titre.compte": "Mi cuenta — Oralixia",
  "page.titre.simulateur": "Tu oral en tres pasos — Oralixia",
  "page.titre.temoignages": "Testimonios — Oralixia",
  "paywall.annule": "Pago cancelado. Tus simulaciones gratuitas siguen disponibles.",
  "paywall.confirmation_age": "Declaro tener 18 años o más, o contar con el consentimiento de mi representante legal para realizar este pago, y acepto las",
  "paywall.confirme": "Pago confirmado. Tu acceso Premium está activo, buen entrenamiento.",
  "paywall.confirmer_age": "Confirma antes que tienes {n} años o el consentimiento de tu representante legal.",
  "paywall.demarrage_echec": "El pago no ha podido iniciarse. Inténtalo de nuevo en un momento.",
  "paywall.non_confirme": "No hemos podido confirmar este pago. Si se te ha cobrado, escríbenos.",
  "paywall.portail_echec": "No se ha podido abrir el portal de suscripción.",
  "paywall.portail_indispo": "Portal no disponible.",
  "paywall.reassurance": "Pago seguro con Stripe · Cancelable en un clic · Ningún dato bancario en nuestros servidores",
  "paywall.recu": "Pago recibido. Tu acceso se activará en unos segundos.",
  "paywall.session_indispo": "Sesión de pago no disponible.",
  "paywall.sur_fin": "Buena simulación",
  "paywall.sur_quota": "Has usado tus {n} simulaciones gratuitas",
  "paywall.titre_fin": "Sube un nivel",
  "paywall.titre_quota": "Sigue entrenando",
  "paywall.verif_impossible": "Ahora mismo no se puede verificar el pago. Recarga la página en un momento.",
  "pied.droits": "Oralixia. Todos los derechos reservados. Oralixia es una herramienta de entrenamiento: las preguntas y las correcciones se generan automáticamente y no constituyen ni una evaluación oficial ni una garantía de éxito.",
  "quota.epuisees": "Simulaciones gratuitas agotadas",
  "quota.premium": "Premium · simulaciones ilimitadas",
  "quota.restante": "{n} simulación gratuita restante",
  "quota.restantes": "{n} simulaciones gratuitas restantes",
  "rapport.a_renforcer": "Por reforzar",
  "rapport.ce_qui_fonctionne": "Lo que funciona",
  "rapport.micro_pour_mesure": "Responde con el micrófono para poder medirlo",
  "rapport.mots_min": "{n} palabras/min",
  "rapport.mots_par_phrase": "{n} palabras por frase de media",
  "rapport.non_mesure": "sin medir",
  "rapport.question_passee": "Pregunta omitida.",
  "rapport.reponse_reecrite": "Respuesta reescrita",
  "rapport.rythme_ideal": "Ritmo ideal",
  "rapport.s_de_parole": "{n} s de habla",
  "rapport.titre_pdf": "Oralixia - informe del {date}",
  "rapport.trop_rapide": "Demasiado rápido",
  "rapport.un_peu_lent": "Algo lento",
  "rapport.verdict.base": "Buena base, hay que afinar",
  "rapport.verdict.pret": "Estás preparado",
  "rapport.verdict.pret_detail": "Tus respuestas están estructuradas y apoyadas en hechos. Retoma solo las preguntas más flojas de abajo y haz otra pasada en condiciones reales.",
  "rapport.verdict.retravailler": "Hay que trabajarlo antes del día de la prueba",
  "rapport.verdict.retravailler_detail": "Trabaja primero los puntos señalados pregunta a pregunta y luego lanza otra simulación: la repetición es lo que instala los reflejos.",
  "rapport.vocabulaire_enrichir": "Vocabulario por enriquecer",
  "rapport.vocabulaire_varie": "Vocabulario variado",
  "rapport.votre_reponse": "Lo que has respondido",
  "refus.coach": "Has agotado tus {n} intercambios de hoy con el coach. Vuelve mañana o pásate a Premium para tener acceso ilimitado.",
  "refus.connexion": "Crea una cuenta gratuita para lanzar una simulación: tus {n} simulaciones gratuitas van asociadas a ella.",
  "refus.defaut": "Cuota agotada.",
  "refus.quota": "Has usado tus {n} simulaciones gratuitas. Pásate a Premium para continuar.",
  "relecture.envoyer_au_coach": "Analizar con el coach",
  "relecture.telecharger": "Descargar en PDF",
  "secours.brevet.0.cat": "Presentación",
  "secours.brevet.0.q": "Presenta en unas frases {sujet|tus prácticas o tu proyecto}.",
  "secours.brevet.1.cat": "Descubrimiento",
  "secours.brevet.1.q": "Describe un día normal: ¿qué hacías concretamente?",
  "secours.brevet.2.cat": "Análisis",
  "secours.brevet.2.q": "¿Qué es lo que más te ha sorprendido, para bien o para mal?",
  "secours.brevet.3.cat": "Profesiones",
  "secours.brevet.3.q": "¿Qué profesión has observado y en qué consiste realmente?",
  "secours.brevet.4.cat": "Competencias",
  "secours.brevet.4.q": "¿Qué cualidades hacen falta para ejercer esa profesión?",
  "secours.brevet.5.cat": "Orientación",
  "secours.brevet.5.q": "¿Esta experiencia ha cambiado algo en tu proyecto?",
  "secours.brevet.6.cat": "Perspectiva",
  "secours.brevet.6.q": "Si pudieras repetir estas prácticas, ¿qué harías de otra manera?",
  "secours.concours.0.cat": "Motivación",
  "secours.concours.0.q": "¿Por qué esta escuela y no otra del mismo nivel?",
  "secours.concours.1.cat": "Personalidad",
  "secours.concours.1.q": "¿Cuál es la decisión más difícil que has tomado?",
  "secours.concours.2.cat": "Trayectoria",
  "secours.concours.2.q": "Tu expediente menciona {0|tu formación}: ¿qué sacas de ella?",
  "secours.concours.3.cat": "Cultura general",
  "secours.concours.3.q": "¿Qué tema de actualidad te ha marcado estos últimos meses y por qué?",
  "secours.concours.4.cat": "Caso práctico",
  "secours.concours.4.q": "Diriges un grupo que está bloqueado a tres días de la entrega. ¿Qué haces?",
  "secours.concours.5.cat": "Compromiso",
  "secours.concours.5.q": "Háblame de un compromiso asociativo, deportivo o personal que te defina.",
  "secours.concours.6.cat": "Proyecto",
  "secours.concours.6.q": "¿Dónde te ves cinco años después de salir de la escuela?",
  "secours.concours.7.cat": "Presión",
  "secours.concours.7.q": "¿Qué podría hacer dudar al tribunal en tu expediente?",
  "secours.entretien.0.cat": "Trayectoria",
  "secours.entretien.0.q": "Preséntate en dos minutos, quedándote solo con lo que ilumina este puesto.",
  "secours.entretien.1.cat": "Motivación",
  "secours.entretien.1.q": "¿Qué te atrae exactamente de esta oferta, más allá del sector?",
  "secours.entretien.2.cat": "Competencias",
  "secours.entretien.2.q": "El anuncio insiste en «{0|el rigor}». Cuéntame una situación en la que lo demostraste.",
  "secours.entretien.3.cat": "Caso práctico",
  "secours.entretien.3.q": "Tu primera semana trata sobre {1|un expediente desconocido}. ¿Por dónde empiezas?",
  "secours.entretien.4.cat": "Competencias",
  "secours.entretien.4.q": "Háblame de un trabajo sobre {2|un proyecto con cifras}: ¿cuál fue tu aportación concreta?",
  "secours.entretien.5.cat": "Perspectiva",
  "secours.entretien.5.q": "Cuéntame un fracaso profesional o académico y qué sacaste de él.",
  "secours.entretien.6.cat": "Trabajo en equipo",
  "secours.entretien.6.q": "Un desacuerdo con un compañero sobre un método: ¿cómo lo gestionas?",
  "secours.entretien.7.cat": "Proyección",
  "secours.entretien.7.q": "¿Dónde quieres estar dentro de tres años y en qué contribuye este puesto?",
  "secours.entretien.8.cat": "Presión",
  "secours.entretien.8.q": "A tu perfil le falta experiencia en este ámbito. ¿Por qué tú y no un candidato con más recorrido?",
  "secours.grand-oral.0.cat": "Tema",
  "secours.grand-oral.0.q": "Presenta tu pregunta y explica por qué la elegiste.",
  "secours.grand-oral.1.cat": "Argumentación",
  "secours.grand-oral.1.q": "¿Cuál es tu tesis principal y en qué argumentos se apoya?",
  "secours.grand-oral.2.cat": "Conocimientos",
  "secours.grand-oral.2.q": "Define con precisión «{0|el concepto central}» de tu tema.",
  "secours.grand-oral.3.cat": "Contraargumento",
  "secours.grand-oral.3.q": "Alguien defiende exactamente lo contrario de tu conclusión. ¿Qué le respondes?",
  "secours.grand-oral.4.cat": "Ejemplo",
  "secours.grand-oral.4.q": "Da un ejemplo concreto, con cifras o histórico, que apoye tu demostración.",
  "secours.grand-oral.5.cat": "Vínculo con tu proyecto",
  "secours.grand-oral.5.q": "¿En qué ilumina este trabajo tu proyecto de orientación?",
  "secours.grand-oral.6.cat": "Apertura",
  "secours.grand-oral.6.q": "¿Qué límite le ves a tu propia respuesta?",
  "secours.grand-oral.7.cat": "Método",
  "secours.grand-oral.7.q": "¿Qué fuentes has usado y cómo has verificado su fiabilidad?",
  "secours.langue-de.0.cat": "Presentación",
  "secours.langue-de.1.cat": "Descripción",
  "secours.langue-de.2.cat": "Opinión",
  "secours.langue-de.3.cat": "Argumentación",
  "secours.langue-de.4.cat": "Situación",
  "secours.langue-de.5.cat": "Proyección",
  "secours.langue-es.0.cat": "Presentación",
  "secours.langue-es.1.cat": "Descripción",
  "secours.langue-es.2.cat": "Opinión",
  "secours.langue-es.3.cat": "Argumentación",
  "secours.langue-es.4.cat": "Situación",
  "secours.langue-es.5.cat": "Proyección",
  "secours.langue.0.cat": "Pregunta personal",
  "secours.langue.1.cat": "Descripción",
  "secours.langue.2.cat": "Opinión",
  "secours.langue.3.cat": "Argumentación",
  "secours.langue.4.cat": "Situación",
  "secours.langue.5.cat": "Comparación",
  "secours.langue.6.cat": "Proyección",
  "secours.matiere.0.cat": "Definición",
  "secours.matiere.0.q": "Define «{0|el concepto central del tema}».",
  "secours.matiere.1.cat": "Conocimientos",
  "secours.matiere.1.q": "¿Cuáles son los puntos esenciales que hay que retener sobre {sujet|este tema}?",
  "secours.matiere.2.cat": "Cronología",
  "secours.matiere.2.q": "Sitúa este tema en su contexto: cuándo, dónde, por qué.",
  "secours.matiere.3.cat": "Análisis",
  "secours.matiere.3.q": "Explica la relación entre {1|las causas} y {2|las consecuencias}.",
  "secours.matiere.4.cat": "Ejemplo",
  "secours.matiere.4.q": "Da un ejemplo preciso que ilustre lo que acabas de explicar.",
  "secours.matiere.5.cat": "Profundización",
  "secours.matiere.5.q": "¿Cuál es la principal dificultad o controversia sobre este punto?",
  "secours.matiere.6.cat": "Síntesis",
  "secours.matiere.6.q": "Resume lo esencial en un minuto, como si se lo explicaras a un compañero.",
  "secours.pitch.0.cat": "Problema",
  "secours.pitch.0.q": "En una frase: ¿qué problema resuelves y para quién?",
  "secours.pitch.1.cat": "Solución",
  "secours.pitch.1.q": "¿Qué hace que tu solución sea difícil de copiar?",
  "secours.pitch.2.cat": "Mercado",
  "secours.pitch.2.q": "¿Cuál es el tamaño de tu mercado y cómo lo has estimado?",
  "secours.pitch.3.cat": "Modelo",
  "secours.pitch.3.q": "¿Cómo ganas dinero y a partir de qué volumen?",
  "secours.pitch.4.cat": "Competencia",
  "secours.pitch.4.q": "¿Por qué tus clientes no se quedan simplemente con {0|la solución actual}?",
  "secours.pitch.5.cat": "Objeción",
  "secours.pitch.5.q": "¿Está validada tu hipótesis principal? ¿Con qué?",
  "secours.pitch.6.cat": "Equipo",
  "secours.pitch.6.q": "¿Por qué es tu equipo el adecuado para ejecutar este proyecto?",
  "secours.pitch.7.cat": "Tracción",
  "secours.pitch.7.q": "¿Qué cifras puedes enseñar hoy?",
  "sim.0_mot": "0 palabras",
  "sim.1_min": "1 min",
  "sim.2_min": "2 min",
  "sim.5_min": "5 min",
  "sim.a_l_ecoute": "Escuchando…",
  "sim.aide_completer": "Rellena los dos campos para empezar.",
  "sim.aide_compte": "Último paso: una cuenta gratuita, para asociar tus dos simulaciones de regalo.",
  "sim.aide_duree": "Duración estimada: unos {n} minutos.",
  "sim.aide_quota": "Has usado tus simulaciones gratuitas: pasa a Premium para continuar.",
  "sim.arreter_dictee": "Parar",
  "sim.bienveillant": "Cercano",
  "sim.ca_vous_a_servi": "¿Te ha servido?",
  "sim.ce_bilan_est_enregistre": "Este informe está guardado",
  "sim.choisis_ton_epreuve_depose_tes_documents_regle_le_fo": "Elige tu prueba, sube tus documentos, ajusta el formato. La primera pregunta llega treinta segundos después.",
  "sim.chrono_bascule": "Condiciones reales: paso automático en {n} s.",
  "sim.chrono_depasse": "Estás superando el tiempo recomendado. Ve concluyendo.",
  "sim.chrono_en_pause": "En pausa.",
  "sim.chrono_sans_pause": "Condiciones reales: sin pausa.",
  "sim.chrono_tourne": "El cronómetro corre, pero no te corta.",
  "sim.clarte": "Claridad",
  "sim.completez_les_deux_champs_pour_demarrer": "Completa los dos campos para empezar.",
  "sim.debit_de_parole": "Ritmo del habla",
  "sim.dictee_indisponible": "El dictado no está disponible en este navegador.",
  "sim.dicter": "Dictar",
  "sim.documents_lus_navigateur": "Documentos leídos en tu navegador, nunca almacenados",
  "sim.eloquence_et_voix": "Elocuencia y voz",
  "sim.enregistrement_arrete": "Grabación detenida. Relee y corrige si hace falta.",
  "sim.exigeant": "Exigente",
  "sim.importer_fichier": "Importar un archivo o arrástralo aquí",
  "sim.intitule_missions_profil_recherche": "Puesto, funciones, perfil buscado",
  "sim.jecoute": "Te escucho: pulsa para parar",
  "sim.l_offre_d_emploi": "La oferta de empleo",
  "sim.laisser_un_avis": "Dejar una opinión",
  "sim.le_chrono_tourne": "El cronómetro corre.",
  "sim.le_format_de_l_epreuve": "El formato de la prueba",
  "sim.lecture_auto": "El examinador habla",
  "sim.lecture_auto_aide": "Cada pregunta se lee en voz alta, como el día del examen.",
  "sim.matiere": "Asignatura",
  "sim.mettre_en_pause": "Pausar",
  "sim.micro_echec": "El micrófono no ha podido iniciarse.",
  "sim.minimum": "Mínimo {n} caracteres.",
  "sim.minimum_150_caracteres": "Mínimo 150 caracteres.",
  "sim.minimum_200_caracteres": "Mínimo 200 caracteres.",
  "sim.mode_demo": "Modo demo: la API no ha respondido, las preguntas y la corrección se han generado localmente. Esta simulación no descuenta de tu cuota gratuita.",
  "sim.mode_reel": "Modo condiciones reales",
  "sim.mode_reel_actif": "Condiciones reales: cronómetro estricto, sin pausa.",
  "sim.mode_reel_aide": "Cronómetro estricto, sin pausa, paso automático a la siguiente pregunta.",
  "sim.modifier_mes_documents": "Cambiar mis documentos",
  "sim.mot": "{n} palabra",
  "sim.mots": "{n} palabras",
  "sim.mots_reponse": "Palabras / respuesta",
  "sim.nombre_de_questions": "Número de preguntas",
  "sim.parcours_missions_resultats": "Trayectoria, funciones, resultados",
  "sim.parlez": "Habla con normalidad, tu respuesta se escribe sola.",
  "sim.parlez_normalement_votre_reponse_s_ecrit_toute_seule": "Habla con naturalidad: tu respuesta se escribe sola.",
  "sim.passer_cette_question": "Saltar esta pregunta",
  "sim.pause": "Pausar",
  "sim.pause_interdite": "El modo condiciones reales no permite pausar.",
  "sim.pdf_word_image_ou_texte_colle_tes_fichiers_sont_lus_": "PDF, Word, imagen o texto pegado. Tus archivos se leen en tu navegador, nunca se almacenan.",
  "sim.pendant_que_vous_attendez": "Mientras esperas",
  "sim.placeholder_cv": "Pega o importa tu CV…",
  "sim.placeholder_offre": "Pega la oferta completa…",
  "sim.placeholder_reponse": "También puedes escribir directamente aquí.",
  "sim.preparation_de_votre_oral": "Preparando tu oral",
  "sim.quel_oral_prepares_tu": "¿Qué oral estás preparando?",
  "sim.quelques_secondes_l_examinateur_se_prepare": "Unos segundos, el examinador se está preparando.",
  "sim.question": "Pregunta",
  "sim.questions": "Preguntas",
  "sim.quitter": "Salir",
  "sim.rapport_de_simulation": "Informe de la simulación",
  "sim.reecouter": "Volver a escuchar la pregunta",
  "sim.refaire_une_simulation": "Hacer otra simulación",
  "sim.repondre_a_l_oral": "Responder en voz alta",
  "sim.repondre_oral": "Responder en voz alta",
  "sim.reponse_par_reponse": "Respuesta por respuesta",
  "sim.reprendre": "Reanudar",
  "sim.retrouvez_le_quand_vous_voulez_dans_mes_simulations_": "Encuéntralo cuando quieras en «Mis simulaciones anteriores», con las preguntas planteadas, tus respuestas y la corrección completa del examinador.",
  "sim.richesse_du_vocabulaire": "Riqueza de vocabulario",
  "sim.simulation": "Simulación",
  "sim.standard": "Estándar",
  "sim.sur": "de",
  "sim.sur_100": "sobre 100",
  "sim.telecharger_le_bilan_en_pdf": "Descargar el informe en PDF",
  "sim.temps_de_parole": "Tiempo de habla",
  "sim.temps_par_reponse": "Tiempo por respuesta",
  "sim.terminer": "Terminar y ver el informe",
  "sim.tes_documents": "Tus documentos",
  "sim.ton_de_l_examinateur": "Tono del examinador",
  "sim.valider": "Validar y continuar",
  "sim.valider_et_continuer": "Validar y continuar",
  "sim.voix_absente": "La respuesta por voz no está disponible en este navegador. Usa Chrome, Edge o Safari, o escribe tu respuesta.",
  "sim.votre_cv": "Tu CV",
  "sim.votre_reponse": "Tu respuesta",
  "sim.votre_retour_aide_les_prochains_candidats_a_se_lance": "Tu opinión ayuda a los próximos candidatos a dar el paso. Se verifica antes de publicarse.",
  "sim.zero_mot": "0 palabras",
  "temoin.a_votre_tour": "Te toca.",
  "temoin.chaque_avis_publie_ici_a_ete_depose_par_une_personne": "Cada opinión publicada aquí la ha dejado alguien que hizo una simulación, y se verifica antes de publicarse. Ningún testimonio lo escribimos nosotros.",
  "temoin.deux_simulations_offertes_sans_carte": "Dos simulaciones completas gratis al crear tu cuenta, sin tarjeta.",
  "temoin.envoyer_mon_avis": "Enviar mi opinión",
  "temoin.epreuve_preparee": "Prueba preparada",
  "temoin.merci_votre_avis_part_en_verification_il_apparaitra_": "Gracias. Tu opinión está en verificación y aparecerá en esta página una vez aprobada.",
  "temoin.note_sur_5": "Puntuación sobre 5",
  "temoin.placeholder_avis": "Lo que te ayudó, lo que cambió el día del examen…",
  "temoin.placeholder_nom": "Nombre A., tu situación",
  "temoin.prenom_et_statut": "Nombre y situación",
  "temoin.racontez_ce_qui_vous_a_servi_et_ce_qui_vous_a_manque": "Cuéntanos qué te sirvió y qué te faltó. Tu opinión se verifica antes de publicarse: no retiramos las opiniones negativas, solo las ilegibles, ofensivas o fuera de tema.",
  "temoin.votre_note": "Tu valoración",
  "temoin.votre_retour": "Tu opinión",
  "temoin.vous_avez_passe_votre_oral": "¿Ya has hecho tu oral?",
  "titre.auth_volet": "Una cuenta, y<br>el tribunal puede esperar.",
  "titre.ce_que_disent": "Lo que dicen<br class=\"hidden sm:block\"> nuestros usuarios",
  "titre.chaque_oral": "Cada oral tiene <span class=\"marqueur\">sus códigos</span>.",
  "titre.debit_clarte": "Tu ritmo,<br>tu claridad, tus nervios",
  "titre.examinateur_parle": "El examinador<br>te habla de verdad",
  "titre.hero_accueil": "Aprueba tu oral<br><span class=\"marqueur\">a la primera</span>.",
  "titre.hero_simulateur": "Tu oral en <span class=\"marqueur\">tres pasos</span>.",
  "titre.hero_temoignages": "Sus palabras, <span class=\"marqueur\">no nuestras promesas</span>.",
  "titre.jour_j": "El día señalado no debe ser <span class=\"marqueur\">tu primera vez</span>.",
  "titre.ou_tu_perds": "Ve exactamente<br>dónde pierdes puntos",
  "titre.plateforme": "Tu plataforma <span class=\"marqueur\">todo en uno</span><br class=\"hidden sm:block\"> para preparar tu oral.",
  "type.brevet.categorie.0": "Presentación",
  "type.brevet.categorie.1": "Lo que descubriste",
  "type.brevet.categorie.2": "Análisis",
  "type.brevet.categorie.3": "Proyección",
  "type.brevet.champA.aide": "Prácticas, orientación, proyecto interdisciplinar, proyecto artístico",
  "type.brevet.champA.label": "Tu tema de exposición",
  "type.brevet.champA.placeholder": "Ej. «Mis prácticas en una asesoría contable»",
  "type.brevet.champB.aide": "Cómo fue, los oficios que viste, lo que sacaste en claro",
  "type.brevet.champB.label": "Lo que quieres contar",
  "type.brevet.champB.placeholder": "Tus apuntes, tu presentación, tu informe…",
  "type.brevet.court": "Brevet / 3.º ESO",
  "type.brevet.critere.0": "Claridad de la exposición",
  "type.brevet.critere.1": "Riqueza del contenido",
  "type.brevet.critere.2": "Respuestas a las preguntas",
  "type.brevet.critere.3": "Expresión oral",
  "type.brevet.nom": "Oral del brevet (defensa de prácticas o de proyecto)",
  "type.concours.categorie.0": "Motivación",
  "type.concours.categorie.1": "Personalidad",
  "type.concours.categorie.2": "Cultura general",
  "type.concours.categorie.3": "Actualidad",
  "type.concours.categorie.4": "Caso práctico",
  "type.concours.champA.aide": "Formación, experiencias, compromisos",
  "type.concours.champA.label": "Tu CV o tu trayectoria",
  "type.concours.champA.placeholder": "Pega o importa tu CV…",
  "type.concours.champB.aide": "Programa, valores, expectativas del tribunal",
  "type.concours.champB.label": "La escuela, la oposición o el puesto al que aspiras",
  "type.concours.champB.placeholder": "Descripción de la escuela, del itinerario, de la oposición…",
  "type.concours.court": "Oposición / Escuela",
  "type.concours.critere.0": "Coherencia del proyecto",
  "type.concours.critere.1": "Conocimiento de la escuela",
  "type.concours.critere.2": "Cultura general y actualidad",
  "type.concours.critere.3": "Actitud y seguridad",
  "type.concours.nom": "Entrevista de motivación, oposición o escuela selectiva",
  "type.entretien.categorie.0": "Trayectoria",
  "type.entretien.categorie.1": "Motivación",
  "type.entretien.categorie.2": "Competencias",
  "type.entretien.categorie.3": "Caso práctico",
  "type.entretien.categorie.4": "Perspectiva",
  "type.entretien.categorie.5": "Proyección",
  "type.entretien.champA.aide": "Trayectoria, funciones, resultados",
  "type.entretien.champA.label": "Tu CV",
  "type.entretien.champA.placeholder": "Pega o importa tu CV…",
  "type.entretien.champB.aide": "Puesto, funciones, perfil buscado",
  "type.entretien.champB.label": "La oferta de empleo",
  "type.entretien.champB.placeholder": "Pega el anuncio completo…",
  "type.entretien.court": "Entrevista / Prácticas",
  "type.entretien.critere.0": "Estructura de la respuesta",
  "type.entretien.critere.1": "Encaje con la oferta",
  "type.entretien.critere.2": "Pruebas y cifras",
  "type.entretien.critere.3": "Concisión",
  "type.entretien.nom": "Entrevista de trabajo o de prácticas",
  "type.grand-oral.categorie.0": "Tema",
  "type.grand-oral.categorie.1": "Argumentación",
  "type.grand-oral.categorie.2": "Contraargumento",
  "type.grand-oral.categorie.3": "Vínculo con el proyecto",
  "type.grand-oral.categorie.4": "Apertura",
  "type.grand-oral.champA.aide": "La pregunta elegida y su planteamiento",
  "type.grand-oral.champA.label": "Tu pregunta del Grand Oral",
  "type.grand-oral.champA.placeholder": "Ej. «¿Hasta qué punto condiciona la deuda pública…?»",
  "type.grand-oral.champB.aide": "Esquema detallado, argumentos, ejemplos, vínculo con tu proyecto",
  "type.grand-oral.champB.label": "Tus apuntes o tu esquema",
  "type.grand-oral.champB.placeholder": "Pega o importa tu esquema, tus fichas…",
  "type.grand-oral.court": "Grand Oral",
  "type.grand-oral.critere.0": "Dominio del tema",
  "type.grand-oral.critere.1": "Calidad de la argumentación",
  "type.grand-oral.critere.2": "Perspectiva y proyecto",
  "type.grand-oral.critere.3": "Expresión y convicción",
  "type.grand-oral.nom": "Grand Oral del bachillerato francés",
  "type.langue.categorie.0": "Pregunta personal",
  "type.langue.categorie.1": "Descripción",
  "type.langue.categorie.2": "Opinión",
  "type.langue.categorie.3": "Argumentación",
  "type.langue.categorie.4": "Situación",
  "type.langue.champA.aide": "Nivel actual, puntuación objetivo, plazo",
  "type.langue.champA.label": "Tu nivel y tu objetivo",
  "type.langue.champA.placeholder": "Ej. «B1 sólido, busco 850 en el TOEIC en marzo»",
  "type.langue.champB.aide": "Temas del examen, vocabulario que repasar",
  "type.langue.champB.label": "Temas que trabajar",
  "type.langue.champB.placeholder": "Trabajo, estudios, medio ambiente, tecnología…",
  "type.langue.court": "Oral de idioma",
  "type.langue.critere.0": "Fluidez",
  "type.langue.critere.1": "Gramática y estructuras",
  "type.langue.critere.2": "Riqueza léxica",
  "type.langue.critere.3": "Pronunciación y entonación",
  "type.langue.nom": "Certificación de idioma (TOEIC, TOEFL, IELTS…)",
  "type.langue.souschoix.0": "TOEIC Speaking",
  "type.langue.souschoix.1": "TOEFL iBT Speaking",
  "type.langue.souschoix.2": "IELTS Speaking",
  "type.langue.souschoix.3": "Cambridge B2 First",
  "type.langue.souschoix.4": "Cambridge C1 Advanced",
  "type.langue.souschoix.5": "DELE (español)",
  "type.langue.souschoix.6": "Goethe-Zertifikat (alemán)",
  "type.langue.souschoix.7": "Otra",
  "type.langue.souschoix.label": "Certificación",
  "type.matiere.categorie.0": "Definición",
  "type.matiere.categorie.1": "Conocimientos",
  "type.matiere.categorie.2": "Análisis",
  "type.matiere.categorie.3": "Ejemplo",
  "type.matiere.categorie.4": "Profundización",
  "type.matiere.champA.aide": "Aquello sobre lo que te van a preguntar",
  "type.matiere.champA.label": "El tema o el capítulo",
  "type.matiere.champA.placeholder": "Ej. «La Guerra Fría, 1947-1991»",
  "type.matiere.champB.aide": "El contenido que debes dominar",
  "type.matiere.champB.label": "Tus apuntes o tus fichas",
  "type.matiere.champB.placeholder": "Pega o importa tus apuntes, tus fichas de repaso…",
  "type.matiere.court": "Oral de asignatura",
  "type.matiere.critere.0": "Exactitud de los conocimientos",
  "type.matiere.critere.1": "Estructura de la respuesta",
  "type.matiere.critere.2": "Vocabulario de la asignatura",
  "type.matiere.critere.3": "Ejemplos utilizados",
  "type.matiere.nom": "Oral de asignatura",
  "type.matiere.souschoix.0": "Historia y geografía",
  "type.matiere.souschoix.1": "Francés",
  "type.matiere.souschoix.10": "Otra",
  "type.matiere.souschoix.2": "Matemáticas",
  "type.matiere.souschoix.3": "Economía y ciencias sociales",
  "type.matiere.souschoix.4": "Física y química",
  "type.matiere.souschoix.5": "Biología y geología",
  "type.matiere.souschoix.6": "Filosofía",
  "type.matiere.souschoix.7": "Español",
  "type.matiere.souschoix.8": "Alemán",
  "type.matiere.souschoix.9": "Derecho",
  "type.matiere.souschoix.label": "Asignatura",
  "type.pitch.categorie.0": "Problema",
  "type.pitch.categorie.1": "Solución",
  "type.pitch.categorie.2": "Mercado",
  "type.pitch.categorie.3": "Modelo de negocio",
  "type.pitch.categorie.4": "Objeción",
  "type.pitch.champA.aide": "Problema resuelto, solución, mercado, modelo",
  "type.pitch.champA.label": "Tu proyecto",
  "type.pitch.champA.placeholder": "Describe tu proyecto, tu producto, tu startup…",
  "type.pitch.champB.aide": "Tribunal, inversores, cliente, profesores",
  "type.pitch.champB.label": "Tu público",
  "type.pitch.champB.placeholder": "¿Ante quién presentas y qué esperan?",
  "type.pitch.court": "Pitch / Presentación",
  "type.pitch.critere.0": "Claridad del problema",
  "type.pitch.critere.1": "Solidez del modelo",
  "type.pitch.critere.2": "Impacto del relato",
  "type.pitch.critere.3": "Respuestas a las objeciones",
  "type.pitch.nom": "Presentación o pitch de proyecto",
  "voix.arreter": "Detener",
  "voix.ecouter": "Escuchar"
};
