/* Traductions espagnoles.
   Le français reste la langue de référence : toute clé absente
   d'ici retombe sur le texte français présent dans le HTML.
   Les textes légaux (mentions, CGV, RGPD) restent en français :
   ce sont des documents de droit français, une traduction
   approximative y ferait plus de mal que de bien. */

export default {
  "titre.auth_volet": "Una cuenta, y<br>el tribunal puede esperar.",
  "auth.se_connecter": "Iniciar sesión",
  "auth.inscription": "Registrarse",
  "auth.creer_mon_compte": "Crear mi cuenta",
  "auth.continuer_google": "Continuar con Google",
  "auth.ou": "o",
  "auth.adresse_email": "Correo electrónico",
  "auth.mot_de_passe": "Contraseña",
  "auth.mot_de_passe_oublie": "¿Olvidaste tu contraseña?",
  "auth.confirmer_mot_de_passe": "Confirmar contraseña",
  "auth.lien_sans_mot_de_passe": "Enviarme un enlace, sin contraseña",
  "auth.prenom": "Nombre",
  "auth.nom": "Apellidos",
  "auth.en_continuant": "Al continuar, aceptas las",
  "auth.et_la": "y la",
  "auth.politique_confidentialite": "política de privacidad",
  "auth.volet_intro": "Dos simulaciones completas de regalo al crear la cuenta. Sin tarjeta.",
  "auth.avantage_deux_simulations": "2 simulaciones gratuitas, desde que te registras",
  "auth.avantage_relire": "Releer tus correcciones cuando quieras",
  "auth.avantage_progression": "Seguir tu curva de progreso",
  "auth.avantage_appareils": "Recuperar tu acceso en cualquier dispositivo",
  "auth.raison_simulation": "Crea tu cuenta gratuita para lanzar la simulación: tus dos simulaciones de regalo van asociadas a ella.",
  "auth.email_invalide": "Escribe una dirección de correo válida.",
  "auth.mdp_requis": "Escribe tu contraseña.",
  "auth.prenom_requis": "Indica tu nombre.",
  "auth.confirmation_differente": "Las dos contraseñas no coinciden.",
  "auth.force_court": "Demasiado corta: ocho caracteres como mínimo.",
  "auth.force_moyen": "Correcta. Un número y una mayúscula la harían más sólida.",
  "auth.force_bon": "Buena contraseña.",
  "auth.connexion_en_cours": "Iniciando sesión…",
  "auth.creation_en_cours": "Creando la cuenta…",
  "auth.bienvenue": "Ya estás dentro.",
  "auth.compte_cree": "Cuenta creada. Tus dos simulaciones gratuitas te esperan.",
  "auth.confirmez_boite_mail": "Cuenta creada. Abre tu correo y pulsa el enlace para activarla.",
  "auth.lien_envoye": "Enlace enviado. Abre tu correo para iniciar sesión.",
  "auth.deconnecte": "Has cerrado sesión.",
  "compte.mon_compte": "Mi cuenta",
  "compte.gerer_mon_compte": "Gestionar mi cuenta",
  "compte.premium_actif": "Premium activo",
  "compte.offre_gratuite": "Plan gratuito",
  "compte.actif_jusquau": "Activo hasta el {date}",
  "compte.abonnement_actif": "Suscripción activa. ¡Gracias!",
  "compte.mode_local": "Modo local: tu historial se guarda solo en este navegador. Añade tus claves de Supabase para sincronizar tus dispositivos.",
  "paywall.sur_fin": "Buena simulación",
  "paywall.titre_fin": "Sube un nivel",
  "paywall.sur_quota": "Has usado tus {n} simulaciones gratuitas",
  "paywall.titre_quota": "Sigue entrenando",
  "sim.aide_completer": "Rellena los dos campos para empezar.",
  "sim.aide_compte": "Último paso: una cuenta gratuita, para asociar tus dos simulaciones de regalo.",
  "sim.aide_quota": "Has usado tus simulaciones gratuitas: pasa a Premium para continuar.",
  "sim.aide_duree": "Duración estimada: unos {n} minutos.",
  "avis.vide_titre": "Aún no hay opiniones publicadas.",
  "avis.vide_texte": "Las opiniones que se muestran aquí serán de personas reales que hicieron una simulación, verificadas antes de publicarse. ¿Acabas de hacer un oral?",
  "avis.vide_lien": "La tuya puede ser la primera.",
  "cta.premiere_simulation": "Empezar mi primera simulación",
  "cta.lancer_simulation": "Empezar mi simulación",
  "cta.tous_temoignages": "Ver todos los testimonios",
  "cta.mes_simulations": "Ver mis simulaciones anteriores",
  "offre.equivalent": "{m} al mes · {e} menos que seis meses a la tarifa mensual",
  "quota.premium": "Premium · simulaciones ilimitadas",
  "quota.restante": "{n} simulación gratuita restante",
  "quota.restantes": "{n} simulaciones gratuitas restantes",
  "quota.epuisees": "Simulaciones gratuitas agotadas",
  "offre.pass48.accroche": "La víspera de un oral",
  "offre.pass48.detail": "Acceso completo durante 48 horas. Pago único, sin renovación.",
  "offre.mensuel.accroche": "El más flexible",
  "offre.mensuel.detail": "Simulaciones ilimitadas, informes completos, coach IA. Sin compromiso, cancelable en un clic.",
  "offre.extra.accroche": "Todo un curso escolar",
  "offre.extra.detail": "Seis meses de acceso completo, pagados una sola vez. Pensado para varias convocatorias.",
  "offre.periode.une_fois": "pago único",
  "offre.periode.par_mois": "al mes",
  "offre.periode.pour_6_mois": "por 6 meses",
  "offre.recommande": "Recomendado",
  "chargement.questions.titre": "Preparando tu oral",
  "chargement.questions.etape0": "Leyendo tus documentos",
  "chargement.questions.etape1": "Detectando lo que el tribunal va a indagar",
  "chargement.questions.etape2": "Redactando las preguntas del examinador",
  "chargement.questions.etape3": "Ordenando el desarrollo",
  "chargement.questions.conseil0": "Respira antes de responder. Dos segundos de silencio valen más que un «eh» de tres.",
  "chargement.questions.conseil1": "Una buena respuesta tiene tres tiempos: la situación, lo que hiciste, el resultado.",
  "chargement.questions.conseil2": "El tribunal recuerda la primera y la última frase. Cuídalas.",
  "chargement.questions.conseil3": "Una cifra concreta vale más que tres adjetivos.",
  "chargement.questions.conseil4": "Si una pregunta te sorprende, reformúlala: ganas cinco segundos para pensar.",
  "chargement.correction.titre": "Analizando tu intervención",
  "chargement.correction.etape0": "Releyendo tus respuestas",
  "chargement.correction.etape1": "Evaluando el fondo, respuesta por respuesta",
  "chargement.correction.etape2": "Midiendo el ritmo y la riqueza de vocabulario",
  "chargement.correction.etape3": "Redactando tus áreas de mejora",
  "chargement.correction.conseil0": "La corrección es franca: eso es lo que la hace útil.",
  "chargement.correction.conseil1": "Empieza por la pregunta peor puntuada, no por la primera.",
  "chargement.correction.conseil2": "Repetir una simulación justo después de leer el informe es el mejor momento para progresar.",
  "chargement.correction.conseil3": "Una respuesta demasiado larga cuesta más puntos que una corta.",
  "ecoute.ecouter": "Escuchar",
  "ecoute.arreter": "Detener",
  "ecoute.bilan": "Escuchar el informe",
  "accueil.documents_lus_puis_supprimes": "Documentos leídos y luego eliminados, nunca revendidos",
  "sim.documents_lus_navigateur": "Documentos leídos en tu navegador, nunca almacenados",
  "accueil.paiement_securise_stripe": "Pago seguro con Stripe",
  "titre.hero_accueil": "Aprueba tu oral<br><span class=\"marqueur\">a la primera</span>.",
  "titre.plateforme": "Tu plataforma <span class=\"marqueur\">todo en uno</span><br class=\"hidden sm:block\"> para preparar tu oral.",
  "titre.examinateur_parle": "El examinador<br>te habla de verdad",
  "titre.ou_tu_perds": "Ve exactamente<br>dónde pierdes puntos",
  "titre.debit_clarte": "Tu ritmo,<br>tu claridad, tus nervios",
  "titre.chaque_oral": "Cada oral tiene <span class=\"marqueur\">sus códigos</span>.",
  "titre.ce_que_disent": "Lo que dicen<br class=\"hidden sm:block\"> nuestros usuarios",
  "titre.jour_j": "El día señalado no debe ser <span class=\"marqueur\">tu primera vez</span>.",
  "titre.tes_progres": "Tu progreso<br>te espera",
  "titre.hero_simulateur": "Tu oral en <span class=\"marqueur\">tres pasos</span>.",
  "titre.hero_temoignages": "Sus palabras, <span class=\"marqueur\">no nuestras promesas</span>.",
  "accueil.retours_de_candidats_apres_leur_oral_verifies_avant_": "Opiniones de candidatos tras su oral, verificadas antes de publicarse.",
  "accueil.sans_engagement_depuis_le_portail_client_stripe": "Sin compromiso, desde el portal de cliente de Stripe.",
  "accueil.simulations_offertes_sans_carte": "simulaciones completas gratis al crear tu cuenta, sin tarjeta",
  "accueil.simulations_illimitees_rapports_detailles_et_coach_i": "Simulaciones ilimitadas, informes detallados y coach IA sin límite.",
  "accueil.some_people_say_studying_abroad_is_essential_do_you_": "«Some people say studying abroad is essential. Do you agree? Give reasons and examples.»",
  "accueil.resiliable_en_un_clic": "Cancelable en un clic",
  "accueil.se_deconnecter": "Cerrar sesión",
  "accueil.simulation_passee": "Simulación anterior",
  "accueil.structure_de_la_reponse": "Estructura de la respuesta",
  "accueil.tes_documents_restent_a_toi": "Tus documentos siguen siendo tuyos",
  "accueil.1_19_restantes_78_mots_dictes": "1:19 restantes · 78 palabras dictadas",
  "accueil.accepter": "Aceptar",
  "accueil.accueil": "Inicio",
  "accueil.adresse_e_mail": "Correo electrónico",
  "accueil.aller_au_contenu": "Ir al contenido",
  "accueil.appuyez_sur_le_micro_pour_parler_a_votre_coach": "Pulsa el micrófono para hablar con tu coach.",
  "accueil.arrete_de_repeter_dans_le_vide_entraine_toi_en_condi": "Deja de ensayar al vacío. Practica en condiciones reales, ve exactamente dónde pierdes puntos y corrige cada respuesta con una corrección detallada.",
  "accueil.aucune_promesse_de_note": "Ninguna nota prometida",
  "accueil.axes_notes_a_chaque_passage_contenu_structure_eloque": "aspectos evaluados en cada sesión: contenido, estructura, elocuencia y ritmo del habla",
  "accueil.brevet_3e": "Brevet · 4.º ESO",
  "accueil.certification": "Certificación",
  "accueil.cette_information_sert_uniquement_a_appliquer_la_reg": "Esta información solo sirve para aplicar la normativa. Nunca se comparte.",
  "accueil.chaque_reponse_est_notee_sur_20_et_decomposee_ce_qui": "Cada respuesta se puntúa sobre 20 y se desglosa: lo que funciona, lo que falta y una reescritura breve de lo que podrías haber dicho. Sin elogios de cortesía: si una respuesta está vacía, se dice.",
  "accueil.coach_ia": "Coach IA",
  "accueil.collez_votre_plan_votre_texte_ou_votre_sujet_et_disc": "Pega tu guion, tu texto o tu tema y coméntalo antes de empezar: estructura, reformulación, gancho, preguntas del tribunal. Por escrito o en voz alta.",
  "accueil.compte": "Cuenta",
  "accueil.concision": "Concisión",
  "accueil.concours": "Oposición",
  "accueil.connexion": "Iniciar sesión",
  "accueil.connexion_inscription": "Iniciar sesión / Registrarse",
  "accueil.continue_a_travailler_tes_oraux_la_ou_tu_t_etais_arr": "Retoma la preparación de tus orales donde la dejaste.",
  "accueil.continuer": "Continuar",
  "accueil.continuez_a_vous_entrainer": "Sigue practicando",
  "accueil.criteres_notes": "Criterios evaluados",
  "accueil.decrivez_une_journee_type_de_votre_stage_que_faisiez": "«Describa un día normal de sus prácticas: ¿qué hacía en concreto?»",
  "accueil.deux_simulations_offertes_sans_carte": "Dos simulaciones completas gratis al crear tu cuenta, sin tarjeta. En diez minutos sabrás dónde estás.",
  "accueil.discussion_libre": "Conversación libre",
  "accueil.e_mail_de_votre_parent_ou_responsable_legal": "Correo de tu padre, madre o tutor legal",
  "accueil.effacer": "Borrar",
  "accueil.en_dessous_de_15_ans_son_accord_est_necessaire_pour_": "Por debajo de 15 años, su consentimiento es necesario para que podamos tratar tus datos.",
  "accueil.entretien": "Entrevista",
  "accueil.essayer_gratuitement": "Probar gratis",
  "accueil.gerer_mon_abonnement": "Gestionar mi suscripción",
  "accueil.grand_oral": "Grand Oral",
  "accueil.l_analyse_d_eloquence_mesure_ce_que_tu_n_entends_pas": "El análisis de elocuencia mide lo que tú no oyes: palabras por minuto, riqueza de vocabulario, longitud de las frases. La mayoría de los candidatos habla demasiado rápido sin darse cuenta.",
  "accueil.l_outil_ne_remplace_ni_un_professeur_ni_un_jury_il_t": "La herramienta no sustituye ni a un profesor ni a un tribunal. Te hace pasar la prueba una primera vez, en privado, para que el día señalado no sea tu primera vez.",
  "accueil.le_moyen_le_plus_rapide_de_passer_son_oral_une_premi": "La forma más rápida de pasar tu oral una primera vez, en privado. Tus CV, temas y grabaciones se tratan durante la simulación y luego se eliminan: no se conservan, no se revenden y no se usan para entrenar ningún modelo.",
  "accueil.lecture_audio_activee": "Lectura en voz alta: activada",
  "accueil.legal": "Legal",
  "accueil.les_questions_sont_generees_a_partir_de_tes_propres_": "Las preguntas se generan a partir de tus propios documentos y se leen en voz alta. Respondes por micrófono mientras corre el cronómetro. Es la única forma de saber si tu respuesta se sostiene en voz alta y no solo sobre el papel.",
  "accueil.lus_le_temps_de_la_simulation_jamais_conserves_ni_re": "Leídos durante la simulación, nunca conservados ni revendidos.",
  "accueil.mentions_legales": "Aviso legal",
  "accueil.mes_simulations_passees": "Mis simulaciones anteriores",
  "accueil.mon_espace": "Mi espacio",
  "accueil.note_sur_la_coherence_du_projet_et_la_culture_genera": "Evaluado por la coherencia del proyecto y la cultura general.",
  "accueil.note_sur_la_prise_de_recul_et_le_lien_au_projet_d_or": "Evaluado por la perspectiva y la relación con tu proyecto formativo.",
  "accueil.note_sur_les_preuves_chiffrees_et_la_concision": "Evaluado por las pruebas concretas y la concisión.",
  "accueil.parler_au_coach_ia": "Hablar con el coach IA",
  "accueil.pitch": "Pitch",
  "accueil.plus_tard": "Más tarde",
  "accueil.pose_dans_la_langue_de_l_epreuve_note_selon_le_cecrl": "Planteado en la lengua de la prueba, evaluado según el MCER.",
  "accueil.pourquoi_preporal": "¿Por qué PrepOral?",
  "accueil.preporal_premium": "PrepOral Premium",
  "accueil.preporal_s_adresse_aussi_a_des_collegiens_et_lyceens": "PrepOral también se dirige a estudiantes de secundaria. La ley francesa establece reglas distintas según la edad: pedimos un tramo, nunca tu fecha de nacimiento.",
  "accueil.preuves_et_chiffres": "Pruebas y cifras",
  "accueil.produit": "Producto",
  "accueil.progression_de_vos_notes_de_la_plus_ancienne_a_la_pl": "Evolución de tus notas, de la más antigua a la más reciente.",
  "accueil.qu_est_ce_qui_dans_votre_dossier_pourrait_faire_hesi": "«¿Qué podría hacer dudar al tribunal en su expediente?»",
  "accueil.quel_age_avez_vous": "¿Qué edad tienes?",
  "accueil.quelle_est_la_taille_de_votre_marche_et_comment_l_av": "«¿Qué tamaño tiene su mercado y cómo lo ha estimado?»",
  "accueil.quelqu_un_vous_soutient_exactement_l_inverse_de_votr": "«Alguien defiende justo lo contrario de su conclusión. ¿Qué le responde?»",
  "accueil.question_3_5_mise_en_situation": "Pregunta 3 / 5 · Caso práctico",
  "accueil.questions_courtes_concretes_orientees_objection": "Preguntas breves, concretas, orientadas a la objeción.",
  "accueil.recevoir_un_lien_de_connexion": "Enviarme un enlace de acceso",
  "accueil.refuser": "Rechazar",
  "accueil.relecture": "Revisión",
  "accueil.repeter_devant_quelqu_un_coute_cher_gene_et_n_est_pa": "Ensayar delante de alguien cuesta dinero, incomoda y no se puede repetir diez veces. PrepOral hace lo contrario: el examinador plantea sus preguntas en voz alta, no se cansa nunca y te dice con franqueza qué no funciona.",
  "accueil.simulateur": "Simulador",
  "accueil.temoignages": "Testimonios",
  "accueil.tout_effacer": "Borrar todo",
  "accueil.types_d_oraux_couverts_entretien_grand_oral_brevet_c": "tipos de oral cubiertos: entrevista, Grand Oral, brevet, oposiciones, pitch, oral de asignatura",
  "accueil.un_entrainement_pas_une_garantie_de_reussite_c_est_e": "Un entrenamiento, no una garantía de éxito. Así consta en las condiciones de venta.",
  "accueil.un_jury_de_brevet_et_un_jury_de_grande_ecole_n_atten": "Un tribunal de brevet y uno de escuela superior no esperan lo mismo. El examinador cambia de actitud, de vocabulario y de criterios según la prueba.",
  "accueil.vocabulaire_adapte_a_l_age_bienveillant_mais_exigean": "Vocabulario adaptado a la edad, cercano pero exigente.",
  "accueil.voir_les_offres": "Ver los planes",
  "accueil.vos_2_simulations_gratuites_sont_utilisees": "Has agotado tus 2 simulaciones gratuitas",
  "accueil.votre_premiere_semaine_porte_sur_un_dossier_que_vous": "«Su primera semana trata de un expediente que no conoce. ¿Por dónde empieza?»",
  "accueil.votre_profil_manque_d_experience_sur_ce_perimetre_po": "«Su perfil carece de experiencia en este ámbito. ¿Por qué usted y no un candidato con experiencia?»",
  "accueil.votre_statut_premium_et_votre_historique_vous_suiven": "Tu estado Premium y tu historial te acompañan en todos tus dispositivos.",
  "accueil.vous_n_etes_pas_connecte": "No has iniciado sesión.",
  "sim.0_mot": "0 palabras",
  "sim.1_min": "1 min",
  "sim.2_min": "2 min",
  "sim.5_min": "5 min",
  "sim.bienveillant": "Cercano",
  "sim.ca_vous_a_servi": "¿Te ha servido?",
  "sim.ce_bilan_est_enregistre": "Este informe está guardado",
  "sim.choisis_ton_epreuve_depose_tes_documents_regle_le_fo": "Elige tu prueba, sube tus documentos, ajusta el formato. La primera pregunta llega treinta segundos después.",
  "sim.clarte": "Claridad",
  "sim.completez_les_deux_champs_pour_demarrer": "Completa los dos campos para empezar.",
  "sim.debit_de_parole": "Ritmo del habla",
  "sim.eloquence_et_voix": "Elocuencia y voz",
  "sim.exigeant": "Exigente",
  "sim.intitule_missions_profil_recherche": "Puesto, funciones, perfil buscado",
  "sim.l_offre_d_emploi": "La oferta de empleo",
  "sim.laisser_un_avis": "Dejar una opinión",
  "sim.le_chrono_tourne": "El cronómetro corre.",
  "sim.le_format_de_l_epreuve": "El formato de la prueba",
  "sim.matiere": "Asignatura",
  "sim.mettre_en_pause": "Pausar",
  "sim.minimum_150_caracteres": "Mínimo 150 caracteres.",
  "sim.minimum_200_caracteres": "Mínimo 200 caracteres.",
  "sim.modifier_mes_documents": "Cambiar mis documentos",
  "sim.mots_reponse": "Palabras / respuesta",
  "sim.nombre_de_questions": "Número de preguntas",
  "sim.parcours_missions_resultats": "Trayectoria, funciones, resultados",
  "sim.parlez_normalement_votre_reponse_s_ecrit_toute_seule": "Habla con naturalidad: tu respuesta se escribe sola.",
  "sim.passer_cette_question": "Saltar esta pregunta",
  "sim.pdf_word_image_ou_texte_colle_tes_fichiers_sont_lus_": "PDF, Word, imagen o texto pegado. Tus archivos se leen en tu navegador, nunca se almacenan.",
  "sim.pendant_que_vous_attendez": "Mientras esperas",
  "sim.preparation_de_votre_oral": "Preparando tu oral",
  "sim.quel_oral_prepares_tu": "¿Qué oral estás preparando?",
  "sim.quelques_secondes_l_examinateur_se_prepare": "Unos segundos, el examinador se está preparando.",
  "sim.question": "Pregunta",
  "sim.questions": "Preguntas",
  "sim.quitter": "Salir",
  "sim.rapport_de_simulation": "Informe de la simulación",
  "sim.refaire_une_simulation": "Hacer otra simulación",
  "sim.reponse_par_reponse": "Respuesta por respuesta",
  "sim.retrouvez_le_quand_vous_voulez_dans_mes_simulations_": "Encuéntralo cuando quieras en «Mis simulaciones anteriores», con las preguntas planteadas, tus respuestas y la corrección completa del examinador.",
  "sim.richesse_du_vocabulaire": "Riqueza de vocabulario",
  "sim.simulation": "Simulación",
  "sim.standard": "Estándar",
  "sim.sur_100": "sobre 100",
  "sim.telecharger_le_bilan_en_pdf": "Descargar el informe en PDF",
  "sim.temps_de_parole": "Tiempo de habla",
  "sim.temps_par_reponse": "Tiempo por respuesta",
  "sim.tes_documents": "Tus documentos",
  "sim.ton_de_l_examinateur": "Tono del examinador",
  "sim.valider_et_continuer": "Validar y continuar",
  "sim.votre_cv": "Tu CV",
  "sim.votre_reponse": "Tu respuesta",
  "sim.votre_retour_aide_les_prochains_candidats_a_se_lance": "Tu opinión ayuda a los próximos candidatos a dar el paso. Se verifica antes de publicarse.",
  "temoin.a_votre_tour": "Te toca.",
  "temoin.chaque_avis_publie_ici_a_ete_depose_par_une_personne": "Cada opinión publicada aquí la ha dejado alguien que hizo una simulación, y se verifica antes de publicarse. Ningún testimonio lo escribimos nosotros.",
  "temoin.deux_simulations_offertes_sans_carte": "Dos simulaciones completas gratis al crear tu cuenta, sin tarjeta.",
  "temoin.envoyer_mon_avis": "Enviar mi opinión",
  "temoin.epreuve_preparee": "Prueba preparada",
  "temoin.merci_votre_avis_part_en_verification_il_apparaitra_": "Gracias. Tu opinión está en verificación y aparecerá en esta página una vez aprobada.",
  "temoin.prenom_et_statut": "Nombre y situación",
  "temoin.racontez_ce_qui_vous_a_servi_et_ce_qui_vous_a_manque": "Cuéntanos qué te sirvió y qué te faltó. Tu opinión se verifica antes de publicarse: no retiramos las opiniones negativas, solo las ilegibles, ofensivas o fuera de tema.",
  "temoin.votre_note": "Tu valoración",
  "temoin.votre_retour": "Tu opinión",
  "temoin.vous_avez_passe_votre_oral": "¿Ya has hecho tu oral?"
};
