/* Traducciones al español.
   El francés sigue siendo la lengua de referencia: cualquier clave
   ausente aquí recae en el texto francés presente en el HTML o en
   el módulo que la invoca.

   Los textos jurídicos se traducen para poder entenderlos, pero el
   contrato sigue sometido al derecho francés: la ventana muestra un
   aviso indicando que solo la versión francesa da fe. */

export default {
  "a11y.changer_langue": "Cambiar de idioma",
  "a11y.changer_theme": "Cambiar de tema",
  "a11y.fermer": "Cerrar",
  "a11y.informations_legales": "Informaci\u00f3n legal",
  "a11y.langues_disponibles": "Idiomas disponibles",
  "a11y.navigation": "Navegaci\u00f3n",
  "a11y.navigation_principale": "Navegaci\u00f3n principal",
  "a11y.theme_clair": "Cambiar al tema claro",
  "a11y.theme_sombre": "Cambiar al tema oscuro",
  "accueil.1_19_restantes_78_mots_dictes": "1:19 restantes \u00b7 78 palabras dictadas",
  "accueil.accepter": "Aceptar",
  "accueil.accueil": "Inicio",
  "accueil.aller_au_contenu": "Ir al contenido",
  "accueil.appuyez_sur_le_micro_pour_parler_a_votre_coach": "Pulsa el micr\u00f3fono para hablar con tu coach.",
  "accueil.arrete_de_repeter_dans_le_vide_entraine_toi_en_condi": "Deja de ensayar al vac\u00edo. Practica en condiciones reales, ve exactamente d\u00f3nde pierdes puntos y corrige cada respuesta con una correcci\u00f3n detallada.",
  "accueil.aucune_promesse_de_note": "Ninguna nota prometida",
  "accueil.axes_notes_a_chaque_passage_contenu_structure_eloque": "aspectos evaluados en cada sesi\u00f3n: contenido, estructura, elocuencia y ritmo del habla",
  "accueil.brevet_3e": "Brevet \u00b7 4.\u00ba ESO",
  "accueil.certification": "Certificaci\u00f3n",
  "accueil.cette_information_sert_uniquement_a_appliquer_la_reg": "Esta informaci\u00f3n solo sirve para aplicar la normativa. Nunca se comparte.",
  "accueil.chaque_reponse_est_notee_sur_20_et_decomposee_ce_qui": "Cada respuesta se punt\u00faa sobre 20 y se desglosa: lo que funciona, lo que falta y una reescritura breve de lo que podr\u00edas haber dicho. Sin elogios de cortes\u00eda: si una respuesta est\u00e1 vac\u00eda, se dice.",
  "accueil.coach_ia": "Coach IA",
  "accueil.collez_votre_plan_votre_texte_ou_votre_sujet_et_disc": "Pega tu guion, tu texto o tu tema y com\u00e9ntalo antes de empezar: estructura, reformulaci\u00f3n, gancho, preguntas del tribunal. Por escrito o en voz alta.",
  "accueil.compte": "Cuenta",
  "accueil.concision": "Concisi\u00f3n",
  "accueil.concours": "Oposici\u00f3n",
  "accueil.connexion": "Iniciar sesi\u00f3n",
  "accueil.continuer": "Continuar",
  "accueil.continuez_a_vous_entrainer": "Sigue practicando",
  "accueil.criteres_notes": "Criterios evaluados",
  "accueil.decrivez_une_journee_type_de_votre_stage_que_faisiez": "\u00abDescriba un d\u00eda normal de sus pr\u00e1cticas: \u00bfqu\u00e9 hac\u00eda en concreto?\u00bb",
  "accueil.deux_simulations_offertes_sans_carte": "Dos simulaciones completas gratis al crear tu cuenta, sin tarjeta. En diez minutos sabr\u00e1s d\u00f3nde est\u00e1s.",
  "accueil.discussion_libre": "Conversaci\u00f3n libre",
  "accueil.documents_lus_puis_supprimes": "Documentos le\u00eddos y luego eliminados, nunca revendidos",
  "accueil.e_mail_de_votre_parent_ou_responsable_legal": "Correo de tu padre, madre o tutor legal",
  "accueil.effacer": "Borrar",
  "accueil.en_dessous_de_15_ans_son_accord_est_necessaire_pour_": "Por debajo de 15 a\u00f1os, su consentimiento es necesario para que podamos tratar tus datos.",
  "accueil.entretien": "Entrevista",
  "accueil.essayer_gratuitement": "Probar gratis",
  "accueil.exemple_parent": "padre@ejemplo.com",
  "accueil.gerer_mon_abonnement": "Gestionar mi suscripci\u00f3n",
  "accueil.grand_oral": "Grand Oral",
  "accueil.l_analyse_d_eloquence_mesure_ce_que_tu_n_entends_pas": "El an\u00e1lisis de elocuencia mide lo que t\u00fa no oyes: palabras por minuto, riqueza de vocabulario, longitud de las frases. La mayor\u00eda de los candidatos habla demasiado r\u00e1pido sin darse cuenta.",
  "accueil.l_outil_ne_remplace_ni_un_professeur_ni_un_jury_il_t": "La herramienta no sustituye ni a un profesor ni a un tribunal. Te hace pasar la prueba una primera vez, en privado, para que el d\u00eda se\u00f1alado no sea tu primera vez.",
  "accueil.le_moyen_le_plus_rapide_de_passer_son_oral_une_premi": "La forma m\u00e1s r\u00e1pida de pasar tu oral una primera vez, en privado. Tus CV, temas y grabaciones se tratan durante la simulaci\u00f3n y luego se eliminan: no se conservan, no se revenden y no se usan para entrenar ning\u00fan modelo.",
  "accueil.lecture_audio_activee": "Lectura en voz alta: activada",
  "accueil.legal": "Legal",
  "accueil.les_questions_sont_generees_a_partir_de_tes_propres_": "Las preguntas se generan a partir de tus propios documentos y se leen en voz alta. Respondes por micr\u00f3fono mientras corre el cron\u00f3metro. Es la \u00fanica forma de saber si tu respuesta se sostiene en voz alta y no solo sobre el papel.",
  "accueil.lus_le_temps_de_la_simulation_jamais_conserves_ni_re": "Le\u00eddos durante la simulaci\u00f3n, nunca conservados ni revendidos.",
  "accueil.mentions_legales": "Aviso legal",
  "accueil.mes_simulations_passees": "Mis simulaciones anteriores",
  "accueil.methode_constat": "<span class=\"font-display text-3xl leading-none text-iris2\">\u00ab</span> La mayor\u00eda de los candidatos preparan su oral releyendo apuntes. El d\u00eda de la prueba descubren que nunca han dicho sus respuestas en voz alta.",
  "accueil.mon_espace": "Mi espacio",
  "accueil.note_sur_la_coherence_du_projet_et_la_culture_genera": "Evaluado por la coherencia del proyecto y la cultura general.",
  "accueil.note_sur_la_prise_de_recul_et_le_lien_au_projet_d_or": "Evaluado por la perspectiva y la relaci\u00f3n con tu proyecto formativo.",
  "accueil.note_sur_les_preuves_chiffrees_et_la_concision": "Evaluado por las pruebas concretas y la concisi\u00f3n.",
  "accueil.paiement_securise_stripe": "Pago seguro con Stripe",
  "accueil.parler_au_coach_ia": "Hablar con el coach IA",
  "accueil.pitch": "Pitch",
  "accueil.plus_tard": "M\u00e1s tarde",
  "accueil.pose_dans_la_langue_de_l_epreuve_note_selon_le_cecrl": "Planteado en la lengua de la prueba, evaluado seg\u00fan el MCER.",
  "accueil.pourquoi_preporal": "\u00bfPor qu\u00e9 Oralixia?",
  "accueil.preporal_premium": "Oralixia Premium",
  "accueil.preporal_s_adresse_aussi_a_des_collegiens_et_lyceens": "Oralixia tambi\u00e9n se dirige a estudiantes de secundaria. La ley francesa establece reglas distintas seg\u00fan la edad: pedimos un tramo, nunca tu fecha de nacimiento.",
  "accueil.preuves_et_chiffres": "Pruebas y cifras",
  "accueil.produit": "Producto",
  "accueil.progression_de_vos_notes_de_la_plus_ancienne_a_la_pl": "Evoluci\u00f3n de tus notas, de la m\u00e1s antigua a la m\u00e1s reciente.",
  "accueil.qu_est_ce_qui_dans_votre_dossier_pourrait_faire_hesi": "\u00ab\u00bfQu\u00e9 podr\u00eda hacer dudar al tribunal en su expediente?\u00bb",
  "accueil.quel_age_avez_vous": "\u00bfQu\u00e9 edad tienes?",
  "accueil.quelle_est_la_taille_de_votre_marche_et_comment_l_av": "\u00ab\u00bfQu\u00e9 tama\u00f1o tiene su mercado y c\u00f3mo lo ha estimado?\u00bb",
  "accueil.quelqu_un_vous_soutient_exactement_l_inverse_de_votr": "\u00abAlguien defiende justo lo contrario de su conclusi\u00f3n. \u00bfQu\u00e9 le responde?\u00bb",
  "accueil.question_3_5_mise_en_situation": "Pregunta 3 / 5 \u00b7 Caso pr\u00e1ctico",
  "accueil.questions_courtes_concretes_orientees_objection": "Preguntas breves, concretas, orientadas a la objeci\u00f3n.",
  "accueil.refuser": "Rechazar",
  "accueil.relecture": "Revisi\u00f3n",
  "accueil.repeter_devant_quelqu_un_coute_cher_gene_et_n_est_pa": "Ensayar delante de alguien cuesta dinero, incomoda y no se puede repetir diez veces. Oralixia hace lo contrario: el examinador plantea sus preguntas en voz alta, no se cansa nunca y te dice con franqueza qu\u00e9 no funciona.",
  "accueil.resiliable_en_un_clic": "Cancelable en un clic",
  "accueil.retours_de_candidats_apres_leur_oral_verifies_avant_": "Opiniones de candidatos tras su oral, verificadas antes de publicarse.",
  "accueil.sans_engagement_depuis_le_portail_client_stripe": "Sin compromiso, desde el portal de cliente de Stripe.",
  "accueil.se_deconnecter": "Cerrar sesi\u00f3n",
  "accueil.simulateur": "Simulador",
  "accueil.simulateur_d_oral": "Simulador de examen oral",
  "accueil.simulation_passee": "Simulaci\u00f3n anterior",
  "accueil.simulations_illimitees_rapports_detailles_et_coach_i": "Simulaciones ilimitadas, informes detallados y coach IA sin l\u00edmite.",
  "accueil.simulations_offertes_sans_carte": "simulaciones completas gratis al crear tu cuenta, sin tarjeta",
  "accueil.some_people_say_studying_abroad_is_essential_do_you_": "\u00abSome people say studying abroad is essential. Do you agree? Give reasons and examples.\u00bb",
  "accueil.structure_de_la_reponse": "Estructura de la respuesta",
  "accueil.temoignages": "Testimonios",
  "accueil.tes_documents_restent_a_toi": "Tus documentos siguen siendo tuyos",
  "accueil.tout_effacer": "Borrar todo",
  "accueil.types_d_oraux_couverts_entretien_grand_oral_brevet_c": "tipos de oral cubiertos: entrevista, Grand Oral, brevet, oposiciones, pitch, oral de asignatura",
  "accueil.un_entrainement_pas_une_garantie_de_reussite_c_est_e": "Un entrenamiento, no una garant\u00eda de \u00e9xito. As\u00ed consta en las condiciones de venta.",
  "accueil.un_jury_de_brevet_et_un_jury_de_grande_ecole_n_atten": "Un tribunal de brevet y uno de escuela superior no esperan lo mismo. El examinador cambia de actitud, de vocabulario y de criterios seg\u00fan la prueba.",
  "accueil.vocabulaire_adapte_a_l_age_bienveillant_mais_exigean": "Vocabulario adaptado a la edad, cercano pero exigente.",
  "accueil.voir_les_offres": "Ver los planes",
  "accueil.vos_2_simulations_gratuites_sont_utilisees": "Has agotado tus 2 simulaciones gratuitas",
  "accueil.votre_premiere_semaine_porte_sur_un_dossier_que_vous": "\u00abSu primera semana trata de un expediente que no conoce. \u00bfPor d\u00f3nde empieza?\u00bb",
  "accueil.votre_profil_manque_d_experience_sur_ce_perimetre_po": "\u00abSu perfil carece de experiencia en este \u00e1mbito. \u00bfPor qu\u00e9 usted y no un candidato con experiencia?\u00bb",
  "accueil.vous_n_etes_pas_connecte": "No has iniciado sesi\u00f3n.",
  "age.15_17": "Entre 15 y 17 a\u00f1os",
  "age.consentement_envoye": "Gracias. Enviaremos un mensaje a tu representante legal para confirmar su consentimiento.",
  "age.email_parent_requis": "Indica el correo electr\u00f3nico de tu padre, madre o representante legal.",
  "age.majeur": "18 a\u00f1os o m\u00e1s",
  "age.moins_15": "Menos de 15 a\u00f1os",
  "age.paiement_mineur": "Has declarado tener menos de {n} a\u00f1os: el pago debe realizarlo tu representante legal, o contar con su consentimiento expreso.",
  "appel.appeler_le_coach": "Llamar al coach",
  "appel.connexion": "Conectando\u2026",
  "appel.ecoute": "Te escucho\u2026",
  "appel.erreur": "No he podido responder. \u00bfLo intentamos otra vez?",
  "appel.fin_oral": "Gracias, la entrevista ha terminado. Preparo tu correcci\u00f3n.",
  "appel.indisponible": "La llamada necesita reconocimiento de voz, que este navegador no tiene. Safari, Chrome y Edge s\u00ed.",
  "appel.ouverture_coach": "Hola, soy tu coach. Dime en qu\u00e9 examen oral est\u00e1s trabajando.",
  "appel.parole": "Respondiendo\u2026",
  "appel.passer_a_l_oral": "Hacer toda la entrevista en voz alta",
  "appel.raccrocher": "Colgar",
  "appel.reflexion": "Un momento\u2026",
  "appel.sous_titre_coach": "Habla con naturalidad. Haz una pausa para que responda.",
  "appel.sous_titre_oral": "Responde en voz alta. Haz una pausa y el tribunal contin\u00faa.",
  "appel.termine": "Llamada terminada.",
  "appel.titre_coach": "Llamada con el coach",
  "appel.titre_oral": "Entrevista oral",
  "auth.adresse_email": "Correo electr\u00f3nico",
  "auth.afficher_mot_de_passe": "Mostrar la contrase\u00f1a",
  "auth.avantage_appareils": "Recuperar tu acceso en cualquier dispositivo",
  "auth.avantage_deux_simulations": "2 simulaciones gratuitas, desde que te registras",
  "auth.avantage_progression": "Seguir tu curva de progreso",
  "auth.avantage_relire": "Releer tus correcciones cuando quieras",
  "auth.bienvenue": "Ya est\u00e1s dentro.",
  "auth.compte_cree": "Cuenta creada. Tus dos simulaciones gratuitas te esperan.",
  "auth.confirmation_differente": "Las dos contrase\u00f1as no coinciden.",
  "auth.confirmer_mot_de_passe": "Confirmar contrase\u00f1a",
  "auth.confirmez_boite_mail": "Cuenta creada. Abre tu correo y pulsa el enlace para activarla. Mira tambi\u00e9n en la carpeta de spam.",
  "auth.connexion_en_cours": "Iniciando sesi\u00f3n\u2026",
  "auth.continuer_google": "Continuar con Google",
  "auth.creation_en_cours": "Creando la cuenta\u2026",
  "auth.creer_mon_compte": "Crear mi cuenta",
  "auth.deconnecte": "Has cerrado sesi\u00f3n.",
  "auth.deja_inscrit": "Esta direcci\u00f3n ya tiene una cuenta. Inicia sesi\u00f3n o usa \u00ab\u00bfOlvidaste tu contrase\u00f1a?\u00bb.",
  "auth.email_au_dessus": "Escribe arriba tu correo electr\u00f3nico.",
  "auth.email_invalide": "Escribe un correo electr\u00f3nico v\u00e1lido.",
  "auth.en_continuant": "Al continuar, aceptas las",
  "auth.err.deja_inscrit": "Ya existe una cuenta con esta direcci\u00f3n. Inicia sesi\u00f3n en su lugar.",
  "auth.err.generique": "Se ha producido un error.",
  "auth.err.identifiants": "Correo o contrase\u00f1a incorrectos.",
  "auth.err.mdp_court": "La contrase\u00f1a debe tener al menos 8 caracteres.",
  "auth.err.non_confirme": "Confirma primero tu direcci\u00f3n: el enlace est\u00e1 en tu buz\u00f3n.",
  "auth.et_la": "y la",
  "auth.exemple_email": "tu@ejemplo.com",
  "auth.exemple_nom": "Dupont",
  "auth.exemple_prenom": "Camille",
  "auth.facultatif": "(opcional)",
  "auth.force_bon": "Buena contrase\u00f1a.",
  "auth.force_court": "Demasiado corta: ocho caracteres como m\u00ednimo.",
  "auth.force_moyen": "Correcta. Un n\u00famero y una may\u00fascula la har\u00edan m\u00e1s s\u00f3lida.",
  "auth.google_inactif": "El acceso con Google a\u00fan no est\u00e1 activado en este sitio. Usa tu correo y tu contrase\u00f1a, o el enlace sin contrase\u00f1a.",
  "auth.huit_caracteres": "8 caracteres como m\u00ednimo",
  "auth.indispo": "No disponible: Supabase no est\u00e1 configurado.",
  "auth.inscription": "Registrarse",
  "auth.inscription_indispo": "Registro no disponible: Supabase no est\u00e1 configurado.",
  "auth.lien_envoye": "Enlace enviado. Abre tu correo para iniciar sesi\u00f3n.",
  "auth.lien_sans_mot_de_passe": "Enviarme un enlace, sin contrase\u00f1a",
  "auth.masquer_mot_de_passe": "Ocultar la contrase\u00f1a",
  "auth.mdp_envoye": "Mensaje enviado: sigue el enlace para elegir una contrase\u00f1a nueva.",
  "auth.mdp_requis": "Escribe tu contrase\u00f1a.",
  "auth.mot_de_passe": "Contrase\u00f1a",
  "auth.mot_de_passe_oublie": "\u00bfOlvidaste tu contrase\u00f1a?",
  "auth.nom": "Apellidos",
  "auth.ou": "o",
  "auth.politique_confidentialite": "pol\u00edtica de privacidad",
  "auth.prenom": "Nombre",
  "auth.prenom_requis": "Indica tu nombre.",
  "auth.pseudonyme": "Apodo",
  "auth.pseudonyme_aide": "Se muestra arriba en lugar de tu correo. Sin apodo, aparecer\u00e1 \u00abNombre A.\u00bb.",
  "auth.pseudonyme_exemple": "Cam",
  "auth.raison_simulation": "Crea tu cuenta gratuita para lanzar la simulaci\u00f3n: tus dos simulaciones de regalo van asociadas a ella.",
  "auth.se_connecter": "Iniciar sesi\u00f3n",
  "auth.supabase_absent": "Inicio de sesi\u00f3n no disponible: Supabase no est\u00e1 configurado.",
  "auth.volet_intro": "Dos simulaciones completas de regalo al crear la cuenta. Sin tarjeta.",
  "avis.aucun_detail": "Esta p\u00e1gina solo muestra opiniones reales de personas que han hecho una simulaci\u00f3n, verificadas antes de publicarse. Preferimos una p\u00e1gina vac\u00eda a testimonios inventados, que adem\u00e1s son ilegales.",
  "avis.aucun_pour_epreuve": "Todav\u00eda no hay opiniones para esta prueba.",
  "avis.aucun_titre": "A\u00fan no hay testimonios publicados.",
  "avis.collectes_depuis": ", recogidas desde {date}",
  "avis.deposer_premier": "Deja la primera opini\u00f3n",
  "avis.depuis": "desde {date}",
  "avis.en_attente": "Pendiente de verificaci\u00f3n",
  "avis.epreuve_facultative": "Prueba preparada (opcional)",
  "avis.etoile": "{n} estrella",
  "avis.etoiles": "{n} estrellas",
  "avis.merci_local": "\u00a1Gracias! Tu opini\u00f3n se ha guardado en este dispositivo; se publicar\u00e1 tras la verificaci\u00f3n.",
  "avis.merci_serveur": "\u00a1Gracias! Tu opini\u00f3n se publicar\u00e1 tras la verificaci\u00f3n.",
  "avis.nom_requis": "Indica al menos tu nombre.",
  "avis.note_sur_5": "{n} sobre 5",
  "avis.statut_defaut": "Usuario de Oralixia",
  "avis.sur_n_verifie": "sobre {n} opini\u00f3n verificada",
  "avis.sur_n_verifies": "sobre {n} opiniones verificadas",
  "avis.toutes_epreuves": "Todas las pruebas",
  "avis.trop_court": "Tu opini\u00f3n es un poco corta, \u00bfunas palabras m\u00e1s?",
  "avis.verifie": "{n} opini\u00f3n verificada",
  "avis.verifies": "{n} opiniones verificadas",
  "avis.vide_lien": "La tuya puede ser la primera.",
  "avis.vide_texte": "Las opiniones que se muestran aqu\u00ed ser\u00e1n de personas reales que hicieron una simulaci\u00f3n, verificadas antes de publicarse. \u00bfAcabas de hacer un oral?",
  "avis.vide_titre": "A\u00fan no hay opiniones publicadas.",
  "bilan.chiffres.non": "A\u00f1ade un dato preciso: una duraci\u00f3n, un volumen, una fecha, una cifra.",
  "bilan.chiffres.oui": "Apoyas lo que dices en cifras o en fechas.",
  "bilan.debit.bon": "Ritmo de {n} palabras por minuto: es el de un oral controlado, mantenlo.",
  "bilan.debit.lent": "Hablas a {n} palabras por minuto: algo lento, lo que da sensaci\u00f3n de duda. Encadena tus ideas sin buscar la palabra perfecta.",
  "bilan.debit.non_mesure": "Responde con el micr\u00f3fono en vez de escribir: as\u00ed Oralixia puede medir tu ritmo y tus silencios.",
  "bilan.debit.rapide": "Hablas a {n} palabras por minuto: es r\u00e1pido. Respira despu\u00e9s de cada idea, el tribunal necesita seguirte.",
  "bilan.je.non": "Di \u00abhice\u00bb, no \u00abhicimos\u00bb: el tribunal te eval\u00faa a ti.",
  "bilan.je.oui": "Asumes tu papel en primera persona.",
  "bilan.long.bien": "Respuesta lo bastante desarrollada para convencer.",
  "bilan.long.correct": "Longitud correcta; un ejemplo m\u00e1s la har\u00eda imbatible.",
  "bilan.long.court": "Demasiado corta: apunta a entre 45 y 120 segundos, unas 100 a 250 palabras.",
  "bilan.phrases_longues": "Tus frases tienen {n} palabras de media. P\u00e1rtelas en dos: una idea, una frase.",
  "bilan.plan": "Anuncia tu esquema en voz alta (\u00abprimero\u2026 luego\u2026 por \u00faltimo\u00bb): el tribunal punt\u00faa lo que consigue seguir.",
  "bilan.plan.non": "Anuncia dos o tres puntos al empezar: el tribunal te sigue mejor.",
  "bilan.plan.oui": "El esquema de la respuesta se oye con claridad.",
  "bilan.preuve.non": "Termina con lo que produjo, no solo con lo que hiciste.",
  "bilan.preuve.oui": "El razonamiento llega hasta el resultado o el ejemplo.",
  "bilan.reecriture": "Empieza as\u00ed: \u00ab{debut}\u2026\u00bb, sigue con un ejemplo fechado y con cifras, y cierra en una frase sobre el resultado.",
  "bilan.sans_reponse": "Pregunta sin responder: ret\u00f3mala en voz alta, aunque sea de forma imperfecta.",
  "bilan.tics.aucun": "Ninguna muletilla destacable: tu discurso es limpio.",
  "bilan.tics.reperes": "Muletillas detectadas: {liste}. Sustit\u00fayelas por un silencio de un segundo, que se percibe como seguridad.",
  "bilan.tics.supprimer": "Muletillas que hay que eliminar: {liste}.",
  "bilan.vocabulaire": "Vocabulario repetitivo: prepara cinco t\u00e9rminos precisos del \u00e1mbito y col\u00f3calos a prop\u00f3sito.",
  "chargement.correction.conseil.0": "La correcci\u00f3n es franca: eso es lo que la hace \u00fatil.",
  "chargement.correction.conseil.1": "Retoma primero la pregunta peor puntuada, no la primera.",
  "chargement.correction.conseil.2": "Lanzar otra simulaci\u00f3n justo despu\u00e9s de leer el balance es el mejor momento para progresar.",
  "chargement.correction.conseil.3": "Una respuesta demasiado larga cuesta m\u00e1s puntos que una demasiado corta.",
  "chargement.correction.etape.0": "Releyendo tus respuestas",
  "chargement.correction.etape.1": "Evaluando el contenido, respuesta por respuesta",
  "chargement.correction.etape.2": "Midiendo tu ritmo y tu riqueza de vocabulario",
  "chargement.correction.etape.3": "Redactando tus puntos de mejora",
  "chargement.correction.titre": "Analizando tu intervenci\u00f3n",
  "chargement.questions.conseil.0": "Respira antes de responder. Dos segundos de silencio valen m\u00e1s que tres de \u00abeh\u00bb.",
  "chargement.questions.conseil.1": "Una buena respuesta tiene tres tiempos: la situaci\u00f3n, lo que hiciste, el resultado.",
  "chargement.questions.conseil.2": "El tribunal recuerda tu primera y tu \u00faltima frase. Cu\u00eddalas.",
  "chargement.questions.conseil.3": "Una cifra concreta vale m\u00e1s que tres adjetivos.",
  "chargement.questions.conseil.4": "Si una pregunta te sorprende, reform\u00falala: ganas cinco segundos para pensar.",
  "chargement.questions.etape.0": "Leyendo tus documentos",
  "chargement.questions.etape.1": "Detectando los puntos que el tribunal va a explorar",
  "chargement.questions.etape.2": "Redactando las preguntas del examinador",
  "chargement.questions.etape.3": "Ordenando el desarrollo",
  "chargement.questions.titre": "Preparando tu oral",
  "coach.accueil": "Hola, soy tu coach de Oralixia. Dime qu\u00e9 oral est\u00e1s preparando, o pega tu guion, tu texto o tu tema: te ayudo a estructurarlo, reformularlo y anticipar las preguntas del tribunal.",
  "coach.analyse_piece": "\u00bfPuedes analizar este documento y decirme qu\u00e9 deber\u00eda trabajar?",
  "coach.appuyez_micro": "Pulsa el micr\u00f3fono para hablar con tu coach.",
  "coach.dernier_echange": "\u00daltimo intercambio gratuito del d\u00eda.",
  "coach.dictee_absente": "El dictado por voz no est\u00e1 disponible en este navegador (prueba con Chrome, Edge o Safari).",
  "coach.documents_joints": "Documentos adjuntos",
  "coach.echange_restant": "{n} intercambio gratuito hoy",
  "coach.echanges_restants": "{n} intercambios gratuitos hoy",
  "coach.je_vous_ecoute": "Te escucho\u2026",
  "coach.joindre": "Adjuntar un documento",
  "coach.lecture_activee": "Lectura en voz alta: activada",
  "coach.lecture_coupee": "Lectura en voz alta: desactivada",
  "coach.lecture_piece": "Leyendo {nom}\u2026",
  "coach.limite_atteinte": "Has usado tus intercambios de hoy con el coach.",
  "coach.parler": "Hablar",
  "coach.piece_echec": "No se ha podido leer este archivo.",
  "coach.piece_refusee": "No se ha podido enviar este documento.",
  "coach.piece_trop_lourde": "Archivo demasiado pesado: 3 MB como m\u00e1ximo.",
  "coach.piece_vide": "No hay texto aprovechable en este archivo.",
  "coach.placeholder_saisie": "Haz tu pregunta o pega el texto de tu oral\u2026",
  "coach.preparation": "Preparando\u2026",
  "coach.raison_compte": "Crea tu cuenta gratuita para hablar con el coach: unos cuantos intercambios al d\u00eda van de regalo.",
  "coach.repli": "No se puede contactar con el coach ahora mismo (la API no est\u00e1 configurada o se ha cortado la red). Mientras tanto, un m\u00e9todo que casi siempre funciona: una frase de entrada, tres ideas anunciadas, un ejemplo fechado y con cifras por idea, y una conclusi\u00f3n que responda a la pregunta.",
  "coach.resume.axes": "Puntos se\u00f1alados: {axes}",
  "coach.resume.eloquence": "Elocuencia: {n}/20.",
  "coach.resume.entete": "Simulaci\u00f3n del {date} \u2014 {type}{precision}.",
  "coach.resume.ma_reponse": "Mi respuesta: {texte}",
  "coach.resume.note": "Nota global: {n}/100.",
  "coach.resume.note_20": "Nota: {n}/20.",
  "coach.resume.sans_reponse": "(sin respuesta)",
  "coach.resume.verdict": "Veredicto: {v}",
  "coach.retirer_piece": "Quitar",
  "coach.simulation_confiee": "Esta es mi simulaci\u00f3n del {date}. \u00bfQu\u00e9 deber\u00eda trabajar primero?",
  "coach.trop_de_pieces": "Cinco archivos adjuntos como m\u00e1ximo.",
  "compte.abonnement": "Suscripci\u00f3n",
  "compte.abonnement_actif": "Suscripci\u00f3n activa. \u00a1Gracias!",
  "compte.actif_jusquau": "Activo hasta el {date}",
  "compte.aucun_abonnement": "Sin suscripci\u00f3n activa. Tus simulaciones de regalo siguen disponibles.",
  "compte.changer_adresse": "Cambiar de correo",
  "compte.changer_mot_de_passe": "Cambiar la contrase\u00f1a",
  "compte.choisir_photo": "Elegir una foto",
  "compte.connexion": "Correo y contrase\u00f1a",
  "compte.couleur_pastille": "Color de la chapa",
  "compte.delai": "El servidor no ha respondido. Int\u00e9ntalo de nuevo.",
  "compte.echec": "No se ha podido guardar.",
  "compte.email_aide": "Cambiar de correo requiere confirmaci\u00f3n: sale un enlace al antiguo y al nuevo.",
  "compte.email_confirmation": "Sale un enlace de confirmaci\u00f3n al correo antiguo y al nuevo. El cambio surte efecto cuando ambos se confirmen.",
  "compte.email_identique": "Escribe una direcci\u00f3n nueva.",
  "compte.enregistre": "Guardado.",
  "compte.enregistre_court": "Guardado",
  "compte.enregistrement": "Guardando\u2026",
  "compte.enregistrer": "Guardar",
  "compte.envoi_photo": "Enviando la foto\u2026",
  "compte.gerer_abonnement": "Cancelar o cambiar de plan",
  "compte.gerer_mon_compte": "Gestionar mi cuenta",
  "compte.hors_ligne": "No se puede guardar: no has iniciado sesi\u00f3n.",
  "compte.identite_aide": "Una foto sustituye a la silueta. Sin foto, elige el tono de tu chapa.",
  "compte.identite_visuelle": "Foto y color",
  "compte.intro": "Tu identidad, tu suscripci\u00f3n y tus m\u00e9todos de pago. Nada de esto lo ven los dem\u00e1s candidatos.",
  "compte.intro_anonyme": "Tus datos, tu suscripci\u00f3n y tus simulaciones gratuitas te esperan detr\u00e1s de tu cuenta.",
  "compte.mdp_envoye": "Mensaje enviado: sigue el enlace para elegir una contrase\u00f1a nueva.",
  "compte.mes_informations": "Mis datos",
  "compte.mes_simulations": "Mis simulaciones",
  "compte.mode_local": "Modo local: tu historial se guarda solo en este navegador. A\u00f1ade tus claves de Supabase para sincronizar tus dispositivos.",
  "compte.mode_local_titre": "Las cuentas no est\u00e1n disponibles en modo local",
  "compte.mon_abonnement": "Mi suscripci\u00f3n",
  "compte.mon_compte": "Mi cuenta",
  "compte.moyens_de_paiement": "M\u00e9todos de pago",
  "compte.offre_gratuite": "Plan gratuito",
  "compte.ouvrir_portail": "Gestionar mis m\u00e9todos de pago",
  "compte.paiement_aide": "Tus datos bancarios nunca pasan por Oralixia ni se guardan aqu\u00ed: los gestiona Stripe en sus propias p\u00e1ginas.",
  "compte.photo_echec": "No se ha podido enviar la foto.",
  "compte.photo_enregistree": "Foto guardada.",
  "compte.photo_illisible": "No se ha podido leer esta imagen.",
  "compte.photo_trop_detaillee": "Esta foto tiene demasiado detalle para guardarse aqu\u00ed. Prueba con otra.",
  "compte.photo_retiree": "Foto quitada.",
  "compte.photo_trop_lourde": "Foto demasiado pesada: 25 MB como m\u00e1ximo.",
  "compte.photo_url": "No se ha encontrado la URL de la foto.",
  "compte.premium_actif": "Premium activo",
  "compte.pseudo_aide": "Se muestra arriba. Sin apodo aparecer\u00e1",
  "compte.reconduction": "Se renueva autom\u00e1ticamente. Cancelable en cualquier momento.",
  "compte.resiliation_aide": "Una cancelaci\u00f3n surte efecto al final del periodo ya pagado: conservas el acceso hasta entonces.",
  "compte.retirer_photo": "Quitar la foto",
  "compte.simulations_restantes": "simulaciones de regalo restantes de {total}",
  "compte.suppression_corps": "Hola:\n\nSolicito la eliminaci\u00f3n de mi cuenta de Oralixia.\n\nDirecci\u00f3n de la cuenta: {email}\n\nGracias.",
  "compte.suppression_objet": "Eliminaci\u00f3n de mi cuenta de Oralixia",
  "compte.suppression_sans_contact": "Este sitio a\u00fan no tiene direcci\u00f3n de contacto. Escribe al editor para pedir la eliminaci\u00f3n.",
  "compte.supprimer_aide": "Borra definitivamente tu perfil, tus simulaciones pasadas y tu contador de uso. Una suscripci\u00f3n activa debe cancelarse antes, desde el portal de pago.",
  "compte.supprimer_bouton": "Solicitar la eliminaci\u00f3n",
  "compte.supprimer_confirmation": "\u00bfEliminar definitivamente tu cuenta, tus simulaciones pasadas y tu contador de uso? No tiene vuelta atr\u00e1s.",
  "compte.supprimer_titre": "Eliminar mi cuenta",
  "compte.titre_anonyme": "Inicia sesi\u00f3n para gestionar tu cuenta",
  "cookies.texte": "Solo usamos cookies necesarias para que el sitio funcione (sesi\u00f3n, preferencias). Ninguna cookie publicitaria, ning\u00fan rastreador de terceros.",
  "cta.lancer_simulation": "Empezar mi simulaci\u00f3n",
  "cta.mes_simulations": "Ver mis simulaciones anteriores",
  "cta.premiere_simulation": "Empezar mi primera simulaci\u00f3n",
  "cta.tous_temoignages": "Ver todos los testimonios",
  "demo.conseil": "<span class=\"font-medium text-iris2\">Consejo \u00b7</span> Haz una pausa real despu\u00e9s de cada idea. Tu ritmo baja solo y el tribunal retiene m\u00e1s.",
  "demo.debit": "palabras / min<br>Demasiado r\u00e1pido",
  "demo.phrases": "palabras / frase<br>Ac\u00f3rtalas",
  "demo.richesse": "riqueza<br>Vocabulario variado",
  "ecoute.arreter": "Detener",
  "ecoute.bilan": "Escuchar el informe",
  "ecoute.ecouter": "Escuchar",
  "hist.a": "a las",
  "hist.aucune": "Todav\u00eda no hay ninguna simulaci\u00f3n. Lanza una y aparecer\u00e1 aqu\u00ed con su nota y su correcci\u00f3n.",
  "hist.courbe_a11y": "Curva de evoluci\u00f3n de las notas",
  "hist.courbe_attente": "Haz una segunda simulaci\u00f3n y aqu\u00ed aparecer\u00e1 tu curva de evoluci\u00f3n.",
  "hist.eloquence": "elocuencia",
  "hist.non_conserve": "Detalle no conservado",
  "hist.progression": "Evoluci\u00f3n en {n} simulaciones",
  "hist.question": "pregunta",
  "hist.questions": "preguntas",
  "hist.relire": "Releer las preguntas y la correcci\u00f3n \u2192",
  "hist.vide": "Historial borrado.",
  "hist.vider_confirmer": "\u00bfBorrar definitivamente todas tus simulaciones guardadas?",
  "import.doc_ancien": "El formato .doc antiguo no se puede leer: guarda el archivo en .docx o en PDF.",
  "import.echec": "No se ha podido importar.",
  "import.format": "Formato no admitido.",
  "import.importe": "{n} caracteres importados",
  "import.lecture": "Leyendo {f}\u2026",
  "import.lib_injoignable": "Biblioteca de lectura inaccesible.",
  "import.ocr": "PDF escaneado detectado, aplicando reconocimiento \u00f3ptico\u2026",
  "import.ok": "Documento importado. Rev\u00edsalo y corr\u00edgelo si hace falta.",
  "import.page": "Leyendo la p\u00e1gina {p}/{n}\u2026",
  "import.vide": "No se ha encontrado texto utilizable en este archivo.",
  "legal.alerte.completer": "Completa el bloque <code>window.ORALIXIA_ENV</code> en <code>index.html</code>.",
  "legal.alerte.manquantes": "Faltan las siguientes menciones legales obligatorias:",
  "legal.alerte.sanctions": "Vender sin estas menciones expone a sanciones (art. L111-1 y ss. del C\u00f3digo de Consumo franc\u00e9s).",
  "legal.alerte.titre": "Configuraci\u00f3n incompleta: no poner a la venta en este estado.",
  "legal.cgv": "Condiciones de venta",
  "legal.cgv.1": "1. Objeto",
  "legal.cgv.1_corps": "Las presentes condiciones regulan la venta de las suscripciones y accesos de pago a Oralixia, servicio de entrenamiento para pruebas orales editado por {n}.",
  "legal.cgv.2": "2. Ofertas y precios",
  "legal.cgv.2_extra": "{nom}: {prix} IVA incluido por seis meses de acceso completo, precedidos de {jours} d\u00edas de prueba gratuita. La suscripci\u00f3n se <strong>renueva autom\u00e1ticamente cada seis meses</strong> hasta su cancelaci\u00f3n; no se cobra nada durante la prueba.",
  "legal.cgv.2_gratuit": "Oferta gratuita: {n} simulaciones completas al crear la cuenta, sin tarjeta bancaria.",
  "legal.cgv.2_mensuel": "{nom}: {prix} IVA incluido al mes, sin compromiso, renovado autom\u00e1ticamente cada mes hasta su cancelaci\u00f3n.",
  "legal.cgv.2_pass48": "{nom}: {prix} IVA incluido, acceso completo durante 48 horas desde el pago. Pago \u00fanico, sin renovaci\u00f3n.",
  "legal.cgv.2_prix": "Los precios se indican con todos los impuestos incluidos, en euros. {n} puede modificarlos en cualquier momento; se aplica la tarifa mostrada en el momento del pedido.",
  "legal.cgv.3": "3. Pedido y pago",
  "legal.cgv.3_corps": "El pago se efect\u00faa en l\u00ednea mediante Stripe (tarjeta bancaria y medios ofrecidos por Stripe). El pedido se valida tras la confirmaci\u00f3n del pago. La factura est\u00e1 disponible en el \u00e1rea de cliente.",
  "legal.cgv.4": "4. Cancelaci\u00f3n y renovaci\u00f3n",
  "legal.cgv.4_essai": "Cancelar durante los {jours} d\u00edas de prueba de la oferta {nom} no conlleva ning\u00fan cobro.",
  "legal.cgv.4_l215": "De conformidad con el art\u00edculo L215-1 del C\u00f3digo de Consumo franc\u00e9s, {n} informa al abonado de su facultad de no renovar su suscripci\u00f3n semestral, como muy pronto tres meses y como muy tarde un mes antes del vencimiento. A falta de esta informaci\u00f3n, el abonado puede poner fin gratuitamente al contrato en cualquier momento a partir de la fecha de renovaci\u00f3n y obtener el reembolso de las cantidades cobradas despu\u00e9s de ella.",
  "legal.cgv.4_pass48": "El Pase de 48 horas es un pago \u00fanico: no se renueva y no hay que cancelarlo. Al vencer, el acceso vuelve a la oferta gratuita.",
  "legal.cgv.4_resilier": "Las suscripciones {m} y {e} pueden cancelarse en cualquier momento desde \u00abGestionar mi cuenta\u00bb, que abre el portal de cliente de Stripe. La cancelaci\u00f3n surte efecto al final del periodo ya pagado: el acceso se conserva hasta entonces y no se reembolsa ning\u00fan prorrateo. El portal tambi\u00e9n permite cambiar de f\u00f3rmula.",
  "legal.cgv.5": "5. Derecho de desistimiento",
  "legal.cgv.5_delai": "De conformidad con los art\u00edculos L221-18 y siguientes del C\u00f3digo de Consumo franc\u00e9s, el consumidor dispone de 14 d\u00edas para desistir.",
  "legal.cgv.5_renonciation": "Al suscribirte, solicitas expresamente la ejecuci\u00f3n inmediata del servicio y reconoces perder tu derecho de desistimiento una vez que el servicio se haya ejecutado por completo (art. L221-28 13\u00b0). En la suscripci\u00f3n mensual, el desistimiento sigue siendo posible mientras no se haya lanzado ninguna simulaci\u00f3n de pago.",
  "legal.cgv.6": "6. Disponibilidad",
  "legal.cgv.6_corps": "El servicio se presta \u00abtal cual\u00bb. {n} aplica los medios razonables para asegurar su disponibilidad, pero no garantiza una continuidad absoluta (mantenimiento, incidente de un proveedor externo, indisponibilidad del proveedor del modelo de IA).",
  "legal.cgv.7": "7. Responsabilidad",
  "legal.cgv.7_corps": "Oralixia es una herramienta de entrenamiento. No se asume ninguna obligaci\u00f3n de resultado en cuanto al \u00e9xito en un examen, una oposici\u00f3n o un proceso de selecci\u00f3n.",
  "legal.cgv.8": "8. Suscripci\u00f3n por un menor",
  "legal.cgv.8_annulation": "{n} puede pedir una confirmaci\u00f3n en cualquier momento y anular, sin gastos, una suscripci\u00f3n contratada por un menor sin ese consentimiento.",
  "legal.cgv.8_gratuit": "El uso gratuito del servicio sigue abierto. Para los menores de 15 a\u00f1os, crear una cuenta requiere el consentimiento del titular de la patria potestad (art. 45 de la Ley francesa de Protecci\u00f3n de Datos).",
  "legal.cgv.8_principe": "El servicio se dirige en particular a alumnos de secundaria y bachillerato. De conformidad con los art\u00edculos 1145 y siguientes del C\u00f3digo Civil franc\u00e9s, un menor no emancipado no puede contratar solo una suscripci\u00f3n de pago: debe contratarla el titular de la patria potestad o hacerse con su consentimiento expreso.",
  "legal.cgv.9": "9. Derecho aplicable",
  "legal.cgv.9_corps": "Derecho franc\u00e9s. A falta de acuerdo amistoso, son competentes los tribunales franceses.",
  "legal.cgv.titre": "Condiciones generales de venta",
  "legal.confidentialite": "Privacidad (RGPD)",
  "legal.cookies": "Cookies",
  "legal.cookies.aucun_avant": "Oralixia no utiliza",
  "legal.cookies.aucun_gras": "ninguna cookie publicitaria ni rastreador de marketing",
  "legal.cookies.necessaires": "Cookies estrictamente necesarias: sesi\u00f3n de autenticaci\u00f3n (Supabase) y seguridad del pago (Stripe). No requieren consentimiento previo.",
  "legal.cookies.stockage": "Almacenamiento local del navegador: contador de simulaciones gratuitas, historial de tus notas, opiniones enviadas, preferencias de visualizaci\u00f3n. Esta informaci\u00f3n permanece en tu dispositivo; puedes borrarla desde \u00abMi espacio\u00bb o vaciando los datos del sitio.",
  "legal.cookies.titre": "Cookies y almacenamiento local",
  "legal.cookies.utilisons": "Lo que utilizamos",
  "legal.mentions": "Aviso legal",
  "legal.mentions.contact": "Contacto",
  "legal.mentions.directeur": "Director de la publicaci\u00f3n",
  "legal.mentions.editeur": "Editor del sitio",
  "legal.mentions.hebergement": "Alojamiento",
  "legal.mentions.limites": "L\u00edmites del servicio",
  "legal.mentions.limites_corps": "Oralixia es una herramienta de entrenamiento asistida por inteligencia artificial. Las preguntas, notas y consejos se generan autom\u00e1ticamente, pueden contener errores y no constituyen ni una evaluaci\u00f3n oficial ni una garant\u00eda de \u00e9xito en un examen, una oposici\u00f3n o una entrevista.",
  "legal.mentions.mediation": "Mediaci\u00f3n de consumo",
  "legal.mentions.mediation_corps": "En caso de litigio no resuelto, el consumidor puede acudir gratuitamente a un mediador de consumo: {m}. Plataforma europea de resoluci\u00f3n de litigios en l\u00ednea: ec.europa.eu/consumers/odr.",
  "legal.mentions.paiement": "Pago",
  "legal.mentions.paiement_corps": "Los pagos los gestiona {p}. Ning\u00fan dato de tarjeta bancaria transita ni se almacena en los servidores de Oralixia.",
  "legal.mentions.pi": "Propiedad intelectual",
  "legal.mentions.pi_corps": "Todos los elementos del sitio (marca, logotipo, interfaz, textos, c\u00f3digo) est\u00e1n protegidos. Queda prohibida cualquier reproducci\u00f3n sin autorizaci\u00f3n escrita. Los contenidos que subes siguen siendo tuyos.",
  "legal.mentions.siege": "Domicilio social",
  "legal.mentions.titre": "Aviso legal",
  "legal.mentions.tva": "IVA",
  "legal.rgpd.documents": "Tus documentos",
  "legal.rgpd.documents_corps": "Los archivos que subes se leen directamente en tu navegador: nunca se cargan en nuestros servidores.",
  "legal.rgpd.documents_gras": "Tus CV, temas, apuntes y respuestas no se conservan.",
  "legal.rgpd.documents_ia": "El texto extra\u00eddo se transmite al proveedor del modelo de IA el tiempo necesario para generar las preguntas y la correcci\u00f3n, y despu\u00e9s no se almacena del lado de Oralixia. Estos contenidos no se venden, ni se ceden, ni se usan para entrenar un modelo.",
  "legal.rgpd.donnees": "Datos tratados",
  "legal.rgpd.donnees_abo": "Suscripci\u00f3n: identificador de cliente de Stripe, estado y vencimiento (ejecuci\u00f3n del contrato y obligaci\u00f3n contable).",
  "legal.rgpd.donnees_audio": "Audio: el reconocimiento de voz usa la API de tu navegador. Seg\u00fan el navegador, el audio puede ser tratado por su editor (Google, Apple, Microsoft). Oralixia no recibe ni almacena ninguna grabaci\u00f3n.",
  "legal.rgpd.donnees_compte": "Cuenta: direcci\u00f3n de correo electr\u00f3nico, identificador, fecha de creaci\u00f3n (base jur\u00eddica: ejecuci\u00f3n del contrato).",
  "legal.rgpd.donnees_historique": "Historial: tipo de oral, fecha, nota global y notas por criterio, para mostrar tu evoluci\u00f3n (ejecuci\u00f3n del contrato). El contenido de tus respuestas no se guarda en el servidor.",
  "legal.rgpd.droits": "Tus derechos",
  "legal.rgpd.droits_corps": "Acceso, rectificaci\u00f3n, supresi\u00f3n, limitaci\u00f3n, oposici\u00f3n y portabilidad: escribe a {email}. Tambi\u00e9n puedes presentar una reclamaci\u00f3n ante la CNIL (cnil.fr).",
  "legal.rgpd.durees": "Plazos de conservaci\u00f3n",
  "legal.rgpd.durees_corps": "Cuenta e historial: hasta la eliminaci\u00f3n de la cuenta, y despu\u00e9s 30 d\u00edas. Documentos contables: 10 a\u00f1os (obligaci\u00f3n legal). Datos de navegaci\u00f3n: 13 meses como m\u00e1ximo.",
  "legal.rgpd.mineurs": "Menores",
  "legal.rgpd.mineurs_corps": "El servicio se dirige en particular a alumnos de secundaria y bachillerato. Para los menores de 15 a\u00f1os, crear una cuenta requiere el consentimiento del titular de la patria potestad.",
  "legal.rgpd.responsable": "Responsable del tratamiento",
  "legal.rgpd.soustraitants": "Encargados del tratamiento",
  "legal.rgpd.soustraitants_corps": "Vercel (alojamiento), Supabase (base de datos y autenticaci\u00f3n, regi\u00f3n UE), Stripe (pago) y el proveedor del modelo de IA para generar las preguntas y las correcciones. Algunas transferencias fuera de la UE est\u00e1n amparadas por las cl\u00e1usulas contractuales tipo de la Comisi\u00f3n Europea.",
  "legal.rgpd.titre": "Pol\u00edtica de privacidad (RGPD)",
  "legal.version_fr_fait_foi": "Traducci\u00f3n facilitada a t\u00edtulo informativo. Solo la versi\u00f3n francesa da fe: el contrato se rige por el derecho franc\u00e9s.",
  "lien.desactive": "El acceso por enlace est\u00e1 desactivado en este proyecto.",
  "lien.expire": "Este enlace ha caducado o ya se ha usado. Un enlace de acceso solo funciona una vez. Pide uno nuevo o inicia sesi\u00f3n con tu contrase\u00f1a.",
  "lien.incomplet": "El enlace recibido est\u00e1 incompleto. Pide uno nuevo.",
  "lien.invalide": "Este enlace no es v\u00e1lido. Pide uno nuevo.",
  "lien.refuse": "Este enlace ya no es v\u00e1lido. Pide uno nuevo o inicia sesi\u00f3n con tu contrase\u00f1a.",
  "lien.serveur": "El servicio de autenticaci\u00f3n no ha respondido. Int\u00e9ntalo de nuevo en un momento.",
  "lu.eloquence": "Consejos de elocuencia.",
  "lu.note_globale": "Tu nota global es {n} sobre 100.",
  "lu.note_sur_20": "Nota: {n} sobre 20.",
  "lu.par_critere": "Detalle por criterio.",
  "lu.sur_100": "{nom}: {val} sobre 100.",
  "micro.absent": "No se ha detectado ning\u00fan micr\u00f3fono en este dispositivo.",
  "micro.interrompue": "El dictado se ha interrumpido.",
  "micro.refuse": "Micr\u00f3fono denegado. Autoriza el acceso al micr\u00f3fono en tu navegador.",
  "micro.refuse_systeme": "Micr\u00f3fono denegado por el sistema.",
  "micro.reseau": "El reconocimiento de voz no ha podido conectarse a la red.",
  "micro.rien_entendu": "No se ha detectado ninguna voz.",
  "offre.equivalent": "{m} al mes \u00b7 {e} menos que seis meses a la tarifa mensual",
  "offre.essai": "{n} d\u00edas gratis",
  "offre.extra.accroche": "Todo un curso escolar",
  "offre.extra.detail": "Seis meses de acceso completo y coach de IA sin l\u00edmite. Una semana gratis y luego renovaci\u00f3n cada seis meses, cancelable cuando quieras.",
  "offre.mensuel.accroche": "El m\u00e1s flexible",
  "offre.mensuel.detail": "Simulaciones ilimitadas, informes completos, coach de IA sin l\u00edmite. Sin compromiso, cancelable con un clic.",
  "offre.pass48.accroche": "La v\u00edspera de un oral",
  "offre.pass48.detail": "Acceso completo durante 48 horas. Pago \u00fanico, sin renovaci\u00f3n.",
  "offre.periode.par_mois": "al mes",
  "offre.periode.pour_6_mois": "por 6 meses",
  "offre.periode.une_fois": "pago \u00fanico",
  "offre.recommande": "Recomendado",
  "page.titre.accueil": "Oralixia \u2014 Aprueba tu oral a la primera",
  "page.titre.compte": "Mi cuenta \u2014 Oralixia",
  "page.titre.simulateur": "Tu oral en tres pasos \u2014 Oralixia",
  "page.titre.temoignages": "Testimonios \u2014 Oralixia",
  "paywall.annule": "Pago cancelado. Tus simulaciones gratuitas siguen disponibles.",
  "paywall.confirmation_age": "Declaro tener 18 a\u00f1os o m\u00e1s, o contar con el consentimiento de mi representante legal para realizar este pago, y acepto las",
  "paywall.confirme": "Pago confirmado. Tu acceso Premium est\u00e1 activo, buen entrenamiento.",
  "paywall.confirmer_age": "Confirma antes que tienes {n} a\u00f1os o el consentimiento de tu representante legal.",
  "paywall.demarrage_echec": "El pago no ha podido iniciarse. Int\u00e9ntalo de nuevo en un momento.",
  "paywall.non_confirme": "No hemos podido confirmar este pago. Si se te ha cobrado, escr\u00edbenos.",
  "paywall.portail_echec": "No se ha podido abrir el portal de suscripci\u00f3n.",
  "paywall.portail_indispo": "Portal no disponible.",
  "paywall.reassurance": "Pago seguro con Stripe \u00b7 Cancelable en un clic \u00b7 Ning\u00fan dato bancario en nuestros servidores",
  "paywall.recu": "Pago recibido. Tu acceso se activar\u00e1 en unos segundos.",
  "paywall.session_indispo": "Sesi\u00f3n de pago no disponible.",
  "paywall.sur_fin": "Buena simulaci\u00f3n",
  "paywall.sur_quota": "Has usado tus {n} simulaciones gratuitas",
  "paywall.titre_fin": "Sube un nivel",
  "paywall.titre_quota": "Sigue entrenando",
  "paywall.verif_impossible": "Ahora mismo no se puede verificar el pago. Recarga la p\u00e1gina en un momento.",
  "pied.droits": "Oralixia. Todos los derechos reservados. Oralixia es una herramienta de entrenamiento: las preguntas y las correcciones se generan autom\u00e1ticamente y no constituyen ni una evaluaci\u00f3n oficial ni una garant\u00eda de \u00e9xito.",
  "quota.epuisees": "Simulaciones gratuitas agotadas",
  "quota.premium": "Premium \u00b7 simulaciones ilimitadas",
  "quota.restante": "{n} simulaci\u00f3n gratuita restante",
  "quota.restantes": "{n} simulaciones gratuitas restantes",
  "rapport.a_renforcer": "Por reforzar",
  "rapport.ce_qui_fonctionne": "Lo que funciona",
  "rapport.micro_pour_mesure": "Responde con el micr\u00f3fono para poder medirlo",
  "rapport.mots_min": "{n} palabras/min",
  "rapport.mots_par_phrase": "{n} palabras por frase de media",
  "rapport.non_mesure": "sin medir",
  "rapport.question_passee": "Pregunta omitida.",
  "rapport.reponse_reecrite": "Respuesta reescrita",
  "rapport.rythme_ideal": "Ritmo ideal",
  "rapport.s_de_parole": "{n} s de habla",
  "rapport.titre_pdf": "Oralixia - informe del {date}",
  "rapport.trop_rapide": "Demasiado r\u00e1pido",
  "rapport.un_peu_lent": "Algo lento",
  "rapport.verdict.base": "Buena base, hay que afinar",
  "rapport.verdict.pret": "Est\u00e1s preparado",
  "rapport.verdict.pret_detail": "Tus respuestas est\u00e1n estructuradas y apoyadas en hechos. Retoma solo las preguntas m\u00e1s flojas de abajo y haz otra pasada en condiciones reales.",
  "rapport.verdict.retravailler": "Hay que trabajarlo antes del d\u00eda de la prueba",
  "rapport.verdict.retravailler_detail": "Trabaja primero los puntos se\u00f1alados pregunta a pregunta y luego lanza otra simulaci\u00f3n: la repetici\u00f3n es lo que instala los reflejos.",
  "rapport.vocabulaire_enrichir": "Vocabulario por enriquecer",
  "rapport.vocabulaire_varie": "Vocabulario variado",
  "rapport.votre_reponse": "Lo que has respondido",
  "refus.coach": "Has agotado tus {n} intercambios de hoy con el coach. Vuelve ma\u00f1ana o p\u00e1sate a Premium para tener acceso ilimitado.",
  "refus.connexion": "Crea una cuenta gratuita para lanzar una simulaci\u00f3n: tus {n} simulaciones gratuitas van asociadas a ella.",
  "refus.defaut": "Cuota agotada.",
  "refus.quota": "Has usado tus {n} simulaciones gratuitas. P\u00e1sate a Premium para continuar.",
  "relecture.envoyer_au_coach": "Analizar con el coach",
  "relecture.lu_entete": "Simulaci\u00f3n del {date}.",
  "relecture.telecharger": "Descargar en PDF",
  "relecture.titre_pdf": "{type} del {date}",
  "secours.brevet.0.cat": "Presentaci\u00f3n",
  "secours.brevet.0.q": "Presenta en unas frases {sujet|tus pr\u00e1cticas o tu proyecto}.",
  "secours.brevet.1.cat": "Descubrimiento",
  "secours.brevet.1.q": "Describe un d\u00eda normal: \u00bfqu\u00e9 hac\u00edas concretamente?",
  "secours.brevet.2.cat": "An\u00e1lisis",
  "secours.brevet.2.q": "\u00bfQu\u00e9 es lo que m\u00e1s te ha sorprendido, para bien o para mal?",
  "secours.brevet.3.cat": "Profesiones",
  "secours.brevet.3.q": "\u00bfQu\u00e9 profesi\u00f3n has observado y en qu\u00e9 consiste realmente?",
  "secours.brevet.4.cat": "Competencias",
  "secours.brevet.4.q": "\u00bfQu\u00e9 cualidades hacen falta para ejercer esa profesi\u00f3n?",
  "secours.brevet.5.cat": "Orientaci\u00f3n",
  "secours.brevet.5.q": "\u00bfEsta experiencia ha cambiado algo en tu proyecto?",
  "secours.brevet.6.cat": "Perspectiva",
  "secours.brevet.6.q": "Si pudieras repetir estas pr\u00e1cticas, \u00bfqu\u00e9 har\u00edas de otra manera?",
  "secours.concours.0.cat": "Motivaci\u00f3n",
  "secours.concours.0.q": "\u00bfPor qu\u00e9 esta escuela y no otra del mismo nivel?",
  "secours.concours.1.cat": "Personalidad",
  "secours.concours.1.q": "\u00bfCu\u00e1l es la decisi\u00f3n m\u00e1s dif\u00edcil que has tomado?",
  "secours.concours.2.cat": "Trayectoria",
  "secours.concours.2.q": "Tu expediente menciona {0|tu formaci\u00f3n}: \u00bfqu\u00e9 sacas de ella?",
  "secours.concours.3.cat": "Cultura general",
  "secours.concours.3.q": "\u00bfQu\u00e9 tema de actualidad te ha marcado estos \u00faltimos meses y por qu\u00e9?",
  "secours.concours.4.cat": "Caso pr\u00e1ctico",
  "secours.concours.4.q": "Diriges un grupo que est\u00e1 bloqueado a tres d\u00edas de la entrega. \u00bfQu\u00e9 haces?",
  "secours.concours.5.cat": "Compromiso",
  "secours.concours.5.q": "H\u00e1blame de un compromiso asociativo, deportivo o personal que te defina.",
  "secours.concours.6.cat": "Proyecto",
  "secours.concours.6.q": "\u00bfD\u00f3nde te ves cinco a\u00f1os despu\u00e9s de salir de la escuela?",
  "secours.concours.7.cat": "Presi\u00f3n",
  "secours.concours.7.q": "\u00bfQu\u00e9 podr\u00eda hacer dudar al tribunal en tu expediente?",
  "secours.entretien.0.cat": "Trayectoria",
  "secours.entretien.0.q": "Pres\u00e9ntate en dos minutos, qued\u00e1ndote solo con lo que ilumina este puesto.",
  "secours.entretien.1.cat": "Motivaci\u00f3n",
  "secours.entretien.1.q": "\u00bfQu\u00e9 te atrae exactamente de esta oferta, m\u00e1s all\u00e1 del sector?",
  "secours.entretien.2.cat": "Competencias",
  "secours.entretien.2.q": "El anuncio insiste en \u00ab{0|el rigor}\u00bb. Cu\u00e9ntame una situaci\u00f3n en la que lo demostraste.",
  "secours.entretien.3.cat": "Caso pr\u00e1ctico",
  "secours.entretien.3.q": "Tu primera semana trata sobre {1|un expediente desconocido}. \u00bfPor d\u00f3nde empiezas?",
  "secours.entretien.4.cat": "Competencias",
  "secours.entretien.4.q": "H\u00e1blame de un trabajo sobre {2|un proyecto con cifras}: \u00bfcu\u00e1l fue tu aportaci\u00f3n concreta?",
  "secours.entretien.5.cat": "Perspectiva",
  "secours.entretien.5.q": "Cu\u00e9ntame un fracaso profesional o acad\u00e9mico y qu\u00e9 sacaste de \u00e9l.",
  "secours.entretien.6.cat": "Trabajo en equipo",
  "secours.entretien.6.q": "Un desacuerdo con un compa\u00f1ero sobre un m\u00e9todo: \u00bfc\u00f3mo lo gestionas?",
  "secours.entretien.7.cat": "Proyecci\u00f3n",
  "secours.entretien.7.q": "\u00bfD\u00f3nde quieres estar dentro de tres a\u00f1os y en qu\u00e9 contribuye este puesto?",
  "secours.entretien.8.cat": "Presi\u00f3n",
  "secours.entretien.8.q": "A tu perfil le falta experiencia en este \u00e1mbito. \u00bfPor qu\u00e9 t\u00fa y no un candidato con m\u00e1s recorrido?",
  "secours.grand-oral.0.cat": "Tema",
  "secours.grand-oral.0.q": "Presenta tu pregunta y explica por qu\u00e9 la elegiste.",
  "secours.grand-oral.1.cat": "Argumentaci\u00f3n",
  "secours.grand-oral.1.q": "\u00bfCu\u00e1l es tu tesis principal y en qu\u00e9 argumentos se apoya?",
  "secours.grand-oral.2.cat": "Conocimientos",
  "secours.grand-oral.2.q": "Define con precisi\u00f3n \u00ab{0|el concepto central}\u00bb de tu tema.",
  "secours.grand-oral.3.cat": "Contraargumento",
  "secours.grand-oral.3.q": "Alguien defiende exactamente lo contrario de tu conclusi\u00f3n. \u00bfQu\u00e9 le respondes?",
  "secours.grand-oral.4.cat": "Ejemplo",
  "secours.grand-oral.4.q": "Da un ejemplo concreto, con cifras o hist\u00f3rico, que apoye tu demostraci\u00f3n.",
  "secours.grand-oral.5.cat": "V\u00ednculo con tu proyecto",
  "secours.grand-oral.5.q": "\u00bfEn qu\u00e9 ilumina este trabajo tu proyecto de orientaci\u00f3n?",
  "secours.grand-oral.6.cat": "Apertura",
  "secours.grand-oral.6.q": "\u00bfQu\u00e9 l\u00edmite le ves a tu propia respuesta?",
  "secours.grand-oral.7.cat": "M\u00e9todo",
  "secours.grand-oral.7.q": "\u00bfQu\u00e9 fuentes has usado y c\u00f3mo has verificado su fiabilidad?",
  "secours.langue-de.0.cat": "Presentaci\u00f3n",
  "secours.langue-de.1.cat": "Descripci\u00f3n",
  "secours.langue-de.2.cat": "Opini\u00f3n",
  "secours.langue-de.3.cat": "Argumentaci\u00f3n",
  "secours.langue-de.4.cat": "Situaci\u00f3n",
  "secours.langue-de.5.cat": "Proyecci\u00f3n",
  "secours.langue-es.0.cat": "Presentaci\u00f3n",
  "secours.langue-es.1.cat": "Descripci\u00f3n",
  "secours.langue-es.2.cat": "Opini\u00f3n",
  "secours.langue-es.3.cat": "Argumentaci\u00f3n",
  "secours.langue-es.4.cat": "Situaci\u00f3n",
  "secours.langue-es.5.cat": "Proyecci\u00f3n",
  "secours.langue.0.cat": "Pregunta personal",
  "secours.langue.1.cat": "Descripci\u00f3n",
  "secours.langue.2.cat": "Opini\u00f3n",
  "secours.langue.3.cat": "Argumentaci\u00f3n",
  "secours.langue.4.cat": "Situaci\u00f3n",
  "secours.langue.5.cat": "Comparaci\u00f3n",
  "secours.langue.6.cat": "Proyecci\u00f3n",
  "secours.matiere.0.cat": "Definici\u00f3n",
  "secours.matiere.0.q": "Define \u00ab{0|el concepto central del tema}\u00bb.",
  "secours.matiere.1.cat": "Conocimientos",
  "secours.matiere.1.q": "\u00bfCu\u00e1les son los puntos esenciales que hay que retener sobre {sujet|este tema}?",
  "secours.matiere.2.cat": "Cronolog\u00eda",
  "secours.matiere.2.q": "Sit\u00faa este tema en su contexto: cu\u00e1ndo, d\u00f3nde, por qu\u00e9.",
  "secours.matiere.3.cat": "An\u00e1lisis",
  "secours.matiere.3.q": "Explica la relaci\u00f3n entre {1|las causas} y {2|las consecuencias}.",
  "secours.matiere.4.cat": "Ejemplo",
  "secours.matiere.4.q": "Da un ejemplo preciso que ilustre lo que acabas de explicar.",
  "secours.matiere.5.cat": "Profundizaci\u00f3n",
  "secours.matiere.5.q": "\u00bfCu\u00e1l es la principal dificultad o controversia sobre este punto?",
  "secours.matiere.6.cat": "S\u00edntesis",
  "secours.matiere.6.q": "Resume lo esencial en un minuto, como si se lo explicaras a un compa\u00f1ero.",
  "secours.pitch.0.cat": "Problema",
  "secours.pitch.0.q": "En una frase: \u00bfqu\u00e9 problema resuelves y para qui\u00e9n?",
  "secours.pitch.1.cat": "Soluci\u00f3n",
  "secours.pitch.1.q": "\u00bfQu\u00e9 hace que tu soluci\u00f3n sea dif\u00edcil de copiar?",
  "secours.pitch.2.cat": "Mercado",
  "secours.pitch.2.q": "\u00bfCu\u00e1l es el tama\u00f1o de tu mercado y c\u00f3mo lo has estimado?",
  "secours.pitch.3.cat": "Modelo",
  "secours.pitch.3.q": "\u00bfC\u00f3mo ganas dinero y a partir de qu\u00e9 volumen?",
  "secours.pitch.4.cat": "Competencia",
  "secours.pitch.4.q": "\u00bfPor qu\u00e9 tus clientes no se quedan simplemente con {0|la soluci\u00f3n actual}?",
  "secours.pitch.5.cat": "Objeci\u00f3n",
  "secours.pitch.5.q": "\u00bfEst\u00e1 validada tu hip\u00f3tesis principal? \u00bfCon qu\u00e9?",
  "secours.pitch.6.cat": "Equipo",
  "secours.pitch.6.q": "\u00bfPor qu\u00e9 es tu equipo el adecuado para ejecutar este proyecto?",
  "secours.pitch.7.cat": "Tracci\u00f3n",
  "secours.pitch.7.q": "\u00bfQu\u00e9 cifras puedes ense\u00f1ar hoy?",
  "sim.1_min": "1 min",
  "sim.2_min": "2 min",
  "sim.5_min": "5 min",
  "sim.a_l_ecoute": "Escuchando\u2026",
  "sim.aide_completer": "Rellena los dos campos para empezar.",
  "sim.aide_compte": "\u00daltimo paso: una cuenta gratuita, para asociar tus dos simulaciones de regalo.",
  "sim.aide_duree": "Duraci\u00f3n estimada: unos {n} minutos.",
  "sim.aide_quota": "Has usado tus simulaciones gratuitas: pasa a Premium para continuar.",
  "sim.arreter_dictee": "Parar",
  "sim.bienveillant": "Cercano",
  "sim.ca_vous_a_servi": "\u00bfTe ha servido?",
  "sim.ce_bilan_est_enregistre": "Este informe est\u00e1 guardado",
  "sim.choisis_ton_epreuve_depose_tes_documents_regle_le_fo": "Elige tu prueba, sube tus documentos, ajusta el formato. La primera pregunta llega treinta segundos despu\u00e9s.",
  "sim.chrono_bascule": "Condiciones reales: paso autom\u00e1tico en {n} s.",
  "sim.chrono_depasse": "Est\u00e1s superando el tiempo recomendado. Ve concluyendo.",
  "sim.chrono_en_pause": "En pausa.",
  "sim.chrono_sans_pause": "Condiciones reales: sin pausa.",
  "sim.chrono_tourne": "El cron\u00f3metro corre, pero no te corta.",
  "sim.clarte": "Claridad",
  "sim.completez_les_deux_champs_pour_demarrer": "Completa los dos campos para empezar.",
  "sim.debit_de_parole": "Ritmo del habla",
  "sim.dictee_indisponible": "El dictado no est\u00e1 disponible en este navegador.",
  "sim.dicter": "Dictar",
  "sim.documents_lus_navigateur": "Documentos le\u00eddos en tu navegador, nunca almacenados",
  "sim.eloquence_et_voix": "Elocuencia y voz",
  "sim.enregistrement_arrete": "Grabaci\u00f3n detenida. Relee y corrige si hace falta.",
  "sim.exigeant": "Exigente",
  "sim.importer_fichier": "Importar un archivo o arr\u00e1stralo aqu\u00ed",
  "sim.intitule_missions_profil_recherche": "Puesto, funciones, perfil buscado",
  "sim.jecoute": "Te escucho: pulsa para parar",
  "sim.l_offre_d_emploi": "La oferta de empleo",
  "sim.laisser_un_avis": "Dejar una opini\u00f3n",
  "sim.le_format_de_l_epreuve": "El formato de la prueba",
  "sim.lecture_auto": "El examinador habla",
  "sim.lecture_auto_aide": "Cada pregunta se lee en voz alta, como el d\u00eda del examen.",
  "sim.matiere": "Asignatura",
  "sim.micro_echec": "El micr\u00f3fono no ha podido iniciarse.",
  "sim.minimum": "M\u00ednimo {n} caracteres.",
  "sim.minimum_150_caracteres": "M\u00ednimo 150 caracteres.",
  "sim.minimum_200_caracteres": "M\u00ednimo 200 caracteres.",
  "sim.mode_demo": "Modo demo: la API no ha respondido, las preguntas y la correcci\u00f3n se han generado localmente. Esta simulaci\u00f3n no descuenta de tu cuota gratuita.",
  "sim.mode_reel": "Modo condiciones reales",
  "sim.mode_reel_actif": "Condiciones reales: cron\u00f3metro estricto, sin pausa.",
  "sim.mode_reel_aide": "Cron\u00f3metro estricto, sin pausa, paso autom\u00e1tico a la siguiente pregunta.",
  "sim.modifier_mes_documents": "Cambiar mis documentos",
  "sim.mot": "{n} palabra",
  "sim.mots": "{n} palabras",
  "sim.mots_reponse": "Palabras / respuesta",
  "sim.nombre_de_questions": "N\u00famero de preguntas",
  "sim.parcours_missions_resultats": "Trayectoria, funciones, resultados",
  "sim.parlez": "Habla con normalidad, tu respuesta se escribe sola.",
  "sim.parlez_normalement_votre_reponse_s_ecrit_toute_seule": "Habla con naturalidad: tu respuesta se escribe sola.",
  "sim.passer_cette_question": "Saltar esta pregunta",
  "sim.pause": "Pausar",
  "sim.pause_interdite": "El modo condiciones reales no permite pausar.",
  "sim.pdf_word_image_ou_texte_colle_tes_fichiers_sont_lus_": "PDF, Word, imagen o texto pegado. Tus archivos se leen en tu navegador, nunca se almacenan.",
  "sim.pendant_que_vous_attendez": "Mientras esperas",
  "sim.placeholder_cv": "Pega o importa tu CV\u2026",
  "sim.placeholder_offre": "Pega la oferta completa\u2026",
  "sim.placeholder_reponse": "Tambi\u00e9n puedes escribir directamente aqu\u00ed.",
  "sim.preparation_de_votre_oral": "Preparando tu oral",
  "sim.quel_oral_prepares_tu": "\u00bfQu\u00e9 oral est\u00e1s preparando?",
  "sim.quelques_secondes_l_examinateur_se_prepare": "Unos segundos, el examinador se est\u00e1 preparando.",
  "sim.question": "Pregunta",
  "sim.questions": "Preguntas",
  "sim.quitter": "Salir",
  "sim.rapport_de_simulation": "Informe de la simulaci\u00f3n",
  "sim.reecouter": "Volver a escuchar la pregunta",
  "sim.refaire_une_simulation": "Hacer otra simulaci\u00f3n",
  "sim.repondre_a_l_oral": "Responder en voz alta",
  "sim.repondre_oral": "Responder en voz alta",
  "sim.reponse_par_reponse": "Respuesta por respuesta",
  "sim.reprendre": "Reanudar",
  "sim.retrouvez_le_quand_vous_voulez_dans_mes_simulations_": "Encu\u00e9ntralo cuando quieras en \u00abMis simulaciones anteriores\u00bb, con las preguntas planteadas, tus respuestas y la correcci\u00f3n completa del examinador.",
  "sim.richesse_du_vocabulaire": "Riqueza de vocabulario",
  "sim.simulation": "Simulaci\u00f3n",
  "sim.standard": "Est\u00e1ndar",
  "sim.sur": "de",
  "sim.sur_100": "sobre 100",
  "sim.telecharger_le_bilan_en_pdf": "Descargar el informe en PDF",
  "sim.temps_de_parole": "Tiempo de habla",
  "sim.temps_par_reponse": "Tiempo por respuesta",
  "sim.terminer": "Terminar y ver el informe",
  "sim.tes_documents": "Tus documentos",
  "sim.ton_de_l_examinateur": "Tono del examinador",
  "sim.valider": "Validar y continuar",
  "sim.voix_absente": "La respuesta por voz no est\u00e1 disponible en este navegador. Usa Chrome, Edge o Safari, o escribe tu respuesta.",
  "sim.votre_cv": "Tu CV",
  "sim.votre_reponse": "Tu respuesta",
  "sim.votre_retour_aide_les_prochains_candidats_a_se_lance": "Tu opini\u00f3n ayuda a los pr\u00f3ximos candidatos a dar el paso. Se verifica antes de publicarse.",
  "sim.zero_mot": "0 palabras",
  "temoin.a_votre_tour": "Te toca.",
  "temoin.chaque_avis_publie_ici_a_ete_depose_par_une_personne": "Cada opini\u00f3n publicada aqu\u00ed la ha dejado alguien que hizo una simulaci\u00f3n, y se verifica antes de publicarse. Ning\u00fan testimonio lo escribimos nosotros.",
  "temoin.deux_simulations_offertes_sans_carte": "Dos simulaciones completas gratis al crear tu cuenta, sin tarjeta.",
  "temoin.envoyer_mon_avis": "Enviar mi opini\u00f3n",
  "temoin.epreuve_preparee": "Prueba preparada",
  "temoin.merci_votre_avis_part_en_verification_il_apparaitra_": "Gracias. Tu opini\u00f3n est\u00e1 en verificaci\u00f3n y aparecer\u00e1 en esta p\u00e1gina una vez aprobada.",
  "temoin.note_sur_5": "Puntuaci\u00f3n sobre 5",
  "temoin.placeholder_avis": "Lo que te ayud\u00f3, lo que cambi\u00f3 el d\u00eda del examen\u2026",
  "temoin.placeholder_nom": "Nombre A., tu situaci\u00f3n",
  "temoin.prenom_et_statut": "Nombre y situaci\u00f3n",
  "temoin.racontez_ce_qui_vous_a_servi_et_ce_qui_vous_a_manque": "Cu\u00e9ntanos qu\u00e9 te sirvi\u00f3 y qu\u00e9 te falt\u00f3. Tu opini\u00f3n se verifica antes de publicarse: no retiramos las opiniones negativas, solo las ilegibles, ofensivas o fuera de tema.",
  "temoin.votre_note": "Tu valoraci\u00f3n",
  "temoin.votre_retour": "Tu opini\u00f3n",
  "temoin.vous_avez_passe_votre_oral": "\u00bfYa has hecho tu oral?",
  "titre.auth_volet": "Una cuenta, y<br>el tribunal puede esperar.",
  "titre.ce_que_disent": "Lo que dicen<br class=\"hidden sm:block\"> nuestros usuarios",
  "titre.chaque_oral": "Cada oral tiene <span class=\"marqueur\">sus c\u00f3digos</span>.",
  "titre.debit_clarte": "Tu ritmo,<br>tu claridad, tus nervios",
  "titre.examinateur_parle": "El examinador<br>te habla de verdad",
  "titre.hero_accueil": "Aprueba tu oral<br><span class=\"marqueur\">a la primera</span>.",
  "titre.hero_simulateur": "Tu oral en <span class=\"marqueur\">tres pasos</span>.",
  "titre.hero_temoignages": "Sus palabras, <span class=\"marqueur\">no nuestras promesas</span>.",
  "titre.jour_j": "El d\u00eda se\u00f1alado no debe ser <span class=\"marqueur\">tu primera vez</span>.",
  "titre.ou_tu_perds": "Ve exactamente<br>d\u00f3nde pierdes puntos",
  "titre.plateforme": "Tu plataforma <span class=\"marqueur\">todo en uno</span><br class=\"hidden sm:block\"> para preparar tu oral.",
  "type.brevet.categorie.0": "Presentaci\u00f3n",
  "type.brevet.categorie.1": "Lo que descubriste",
  "type.brevet.categorie.2": "An\u00e1lisis",
  "type.brevet.categorie.3": "Proyecci\u00f3n",
  "type.brevet.champA.aide": "Pr\u00e1cticas, orientaci\u00f3n, proyecto interdisciplinar, proyecto art\u00edstico",
  "type.brevet.champA.label": "Tu tema de exposici\u00f3n",
  "type.brevet.champA.placeholder": "Ej. \u00abMis pr\u00e1cticas en una asesor\u00eda contable\u00bb",
  "type.brevet.champB.aide": "C\u00f3mo fue, los oficios que viste, lo que sacaste en claro",
  "type.brevet.champB.label": "Lo que quieres contar",
  "type.brevet.champB.placeholder": "Tus apuntes, tu presentaci\u00f3n, tu informe\u2026",
  "type.brevet.court": "Brevet / 3.\u00ba ESO",
  "type.brevet.critere.0": "Claridad de la exposici\u00f3n",
  "type.brevet.critere.1": "Riqueza del contenido",
  "type.brevet.critere.2": "Respuestas a las preguntas",
  "type.brevet.critere.3": "Expresi\u00f3n oral",
  "type.brevet.nom": "Oral del brevet (defensa de pr\u00e1cticas o de proyecto)",
  "type.concours.categorie.0": "Motivaci\u00f3n",
  "type.concours.categorie.1": "Personalidad",
  "type.concours.categorie.2": "Cultura general",
  "type.concours.categorie.3": "Actualidad",
  "type.concours.categorie.4": "Caso pr\u00e1ctico",
  "type.concours.champA.aide": "Formaci\u00f3n, experiencias, compromisos",
  "type.concours.champA.label": "Tu CV o tu trayectoria",
  "type.concours.champA.placeholder": "Pega o importa tu CV\u2026",
  "type.concours.champB.aide": "Programa, valores, expectativas del tribunal",
  "type.concours.champB.label": "La escuela, la oposici\u00f3n o el puesto al que aspiras",
  "type.concours.champB.placeholder": "Descripci\u00f3n de la escuela, del itinerario, de la oposici\u00f3n\u2026",
  "type.concours.court": "Oposici\u00f3n / Escuela",
  "type.concours.critere.0": "Coherencia del proyecto",
  "type.concours.critere.1": "Conocimiento de la escuela",
  "type.concours.critere.2": "Cultura general y actualidad",
  "type.concours.critere.3": "Actitud y seguridad",
  "type.concours.nom": "Entrevista de motivaci\u00f3n, oposici\u00f3n o escuela selectiva",
  "type.entretien.categorie.0": "Trayectoria",
  "type.entretien.categorie.1": "Motivaci\u00f3n",
  "type.entretien.categorie.2": "Competencias",
  "type.entretien.categorie.3": "Caso pr\u00e1ctico",
  "type.entretien.categorie.4": "Perspectiva",
  "type.entretien.categorie.5": "Proyecci\u00f3n",
  "type.entretien.champA.aide": "Trayectoria, funciones, resultados",
  "type.entretien.champA.label": "Tu CV",
  "type.entretien.champA.placeholder": "Pega o importa tu CV\u2026",
  "type.entretien.champB.aide": "Puesto, funciones, perfil buscado",
  "type.entretien.champB.label": "La oferta de empleo",
  "type.entretien.champB.placeholder": "Pega el anuncio completo\u2026",
  "type.entretien.court": "Entrevista / Pr\u00e1cticas",
  "type.entretien.critere.0": "Estructura de la respuesta",
  "type.entretien.critere.1": "Encaje con la oferta",
  "type.entretien.critere.2": "Pruebas y cifras",
  "type.entretien.critere.3": "Concisi\u00f3n",
  "type.entretien.nom": "Entrevista de trabajo o de pr\u00e1cticas",
  "type.grand-oral.categorie.0": "Tema",
  "type.grand-oral.categorie.1": "Argumentaci\u00f3n",
  "type.grand-oral.categorie.2": "Contraargumento",
  "type.grand-oral.categorie.3": "V\u00ednculo con el proyecto",
  "type.grand-oral.categorie.4": "Apertura",
  "type.grand-oral.champA.aide": "La pregunta elegida y su planteamiento",
  "type.grand-oral.champA.label": "Tu pregunta del Grand Oral",
  "type.grand-oral.champA.placeholder": "Ej. \u00ab\u00bfHasta qu\u00e9 punto condiciona la deuda p\u00fablica\u2026?\u00bb",
  "type.grand-oral.champB.aide": "Esquema detallado, argumentos, ejemplos, v\u00ednculo con tu proyecto",
  "type.grand-oral.champB.label": "Tus apuntes o tu esquema",
  "type.grand-oral.champB.placeholder": "Pega o importa tu esquema, tus fichas\u2026",
  "type.grand-oral.court": "Grand Oral",
  "type.grand-oral.critere.0": "Dominio del tema",
  "type.grand-oral.critere.1": "Calidad de la argumentaci\u00f3n",
  "type.grand-oral.critere.2": "Perspectiva y proyecto",
  "type.grand-oral.critere.3": "Expresi\u00f3n y convicci\u00f3n",
  "type.grand-oral.nom": "Grand Oral del bachillerato franc\u00e9s",
  "type.langue.categorie.0": "Pregunta personal",
  "type.langue.categorie.1": "Descripci\u00f3n",
  "type.langue.categorie.2": "Opini\u00f3n",
  "type.langue.categorie.3": "Argumentaci\u00f3n",
  "type.langue.categorie.4": "Situaci\u00f3n",
  "type.langue.champA.aide": "Nivel actual, puntuaci\u00f3n objetivo, plazo",
  "type.langue.champA.label": "Tu nivel y tu objetivo",
  "type.langue.champA.placeholder": "Ej. \u00abB1 s\u00f3lido, busco 850 en el TOEIC en marzo\u00bb",
  "type.langue.champB.aide": "Temas del examen, vocabulario que repasar",
  "type.langue.champB.label": "Temas que trabajar",
  "type.langue.champB.placeholder": "Trabajo, estudios, medio ambiente, tecnolog\u00eda\u2026",
  "type.langue.court": "Oral de idioma",
  "type.langue.critere.0": "Fluidez",
  "type.langue.critere.1": "Gram\u00e1tica y estructuras",
  "type.langue.critere.2": "Riqueza l\u00e9xica",
  "type.langue.critere.3": "Pronunciaci\u00f3n y entonaci\u00f3n",
  "type.langue.nom": "Certificaci\u00f3n de idioma (TOEIC, TOEFL, IELTS\u2026)",
  "type.langue.souschoix.0": "TOEIC Speaking",
  "type.langue.souschoix.1": "TOEFL iBT Speaking",
  "type.langue.souschoix.2": "IELTS Speaking",
  "type.langue.souschoix.3": "Cambridge B2 First",
  "type.langue.souschoix.4": "Cambridge C1 Advanced",
  "type.langue.souschoix.5": "DELE (espa\u00f1ol)",
  "type.langue.souschoix.6": "Goethe-Zertifikat (alem\u00e1n)",
  "type.langue.souschoix.7": "Otra",
  "type.langue.souschoix.label": "Certificaci\u00f3n",
  "type.matiere.categorie.0": "Definici\u00f3n",
  "type.matiere.categorie.1": "Conocimientos",
  "type.matiere.categorie.2": "An\u00e1lisis",
  "type.matiere.categorie.3": "Ejemplo",
  "type.matiere.categorie.4": "Profundizaci\u00f3n",
  "type.matiere.champA.aide": "Aquello sobre lo que te van a preguntar",
  "type.matiere.champA.label": "El tema o el cap\u00edtulo",
  "type.matiere.champA.placeholder": "Ej. \u00abLa Guerra Fr\u00eda, 1947-1991\u00bb",
  "type.matiere.champB.aide": "El contenido que debes dominar",
  "type.matiere.champB.label": "Tus apuntes o tus fichas",
  "type.matiere.champB.placeholder": "Pega o importa tus apuntes, tus fichas de repaso\u2026",
  "type.matiere.court": "Oral de asignatura",
  "type.matiere.critere.0": "Exactitud de los conocimientos",
  "type.matiere.critere.1": "Estructura de la respuesta",
  "type.matiere.critere.2": "Vocabulario de la asignatura",
  "type.matiere.critere.3": "Ejemplos utilizados",
  "type.matiere.nom": "Oral de asignatura",
  "type.matiere.souschoix.0": "Historia y geograf\u00eda",
  "type.matiere.souschoix.1": "Franc\u00e9s",
  "type.matiere.souschoix.10": "Otra",
  "type.matiere.souschoix.2": "Matem\u00e1ticas",
  "type.matiere.souschoix.3": "Econom\u00eda y ciencias sociales",
  "type.matiere.souschoix.4": "F\u00edsica y qu\u00edmica",
  "type.matiere.souschoix.5": "Biolog\u00eda y geolog\u00eda",
  "type.matiere.souschoix.6": "Filosof\u00eda",
  "type.matiere.souschoix.7": "Espa\u00f1ol",
  "type.matiere.souschoix.8": "Alem\u00e1n",
  "type.matiere.souschoix.9": "Derecho",
  "type.matiere.souschoix.label": "Asignatura",
  "type.pitch.categorie.0": "Problema",
  "type.pitch.categorie.1": "Soluci\u00f3n",
  "type.pitch.categorie.2": "Mercado",
  "type.pitch.categorie.3": "Modelo de negocio",
  "type.pitch.categorie.4": "Objeci\u00f3n",
  "type.pitch.champA.aide": "Problema resuelto, soluci\u00f3n, mercado, modelo",
  "type.pitch.champA.label": "Tu proyecto",
  "type.pitch.champA.placeholder": "Describe tu proyecto, tu producto, tu startup\u2026",
  "type.pitch.champB.aide": "Tribunal, inversores, cliente, profesores",
  "type.pitch.champB.label": "Tu p\u00fablico",
  "type.pitch.champB.placeholder": "\u00bfAnte qui\u00e9n presentas y qu\u00e9 esperan?",
  "type.pitch.court": "Pitch / Presentaci\u00f3n",
  "type.pitch.critere.0": "Claridad del problema",
  "type.pitch.critere.1": "Solidez del modelo",
  "type.pitch.critere.2": "Impacto del relato",
  "type.pitch.critere.3": "Respuestas a las objeciones",
  "type.pitch.nom": "Presentaci\u00f3n o pitch de proyecto",
  "voix.arreter": "Detener",
  "voix.ecouter": "Escuchar"
};
